# Generated by Django 5.1.4 on 2024-12-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchquery',
            name='source',
            field=models.CharField(choices=[('nextbot', 'NestBot'), ('frontend', 'Frontend')], default='frontend', max_length=50),
        ),
    ]
