"""AI app constants."""

DEFAULT_CHUNKS_RETRIEVAL_LIMIT = 32
DEFAULT_LAST_REQUEST_OFFSET_SECONDS = 2
DEFAULT_MAX_ITERATIONS = 3
DEFAULT_REASONING_MODEL = "gpt-4o"
DEFAULT_SIMILARITY_THRESHOLD = 0.1
DELIMITER = "\n\n"
GITHUB_REQUEST_INTERVAL_SECONDS = 0.5
MIN_REQUEST_INTERVAL_SECONDS = 1.2
QUEUE_RESPONSE_TIME_MINUTES = 1
