"""AI app constants."""

DEFAULT_LAST_REQUEST_OFFSET_SECONDS = 2
DEFAULT_CHUNKS_RETRIEVAL_LIMIT = 5
DEFAULT_SIMILARITY_THRESHOLD = 0.4
DELIMITER = "\n\n"
GITHUB_REQUEST_INTERVAL_SECONDS = 0.5
MIN_REQUEST_INTERVAL_SECONDS = 1.2
QUEUE_RESPONSE_TIME_MINUTES = 1
