# Generated by Django 5.1.1 on 2024-10-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0004_remove_project_top_contributors"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AddField(
            model_name="chapter",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude"),
        ),
    ]
