# Generated by Django 5.1.1 on 2024-10-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0005_chapter_latitude_chapter_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="currency",
            field=models.CharField(blank=True, default="", max_length=10, verbose_name="Currency"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="level",
            field=models.CharField(blank=True, default="", max_length=5, verbose_name="Level"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="meetup_group",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Meetup group"
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="postal_code",
            field=models.CharField(
                blank=True, default="", max_length=15, verbose_name="Postal code"
            ),
        ),
    ]
