# Generated by Django 5.1.1 on 2024-10-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0009_chapter_created_at_chapter_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="invalid_urls",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Project invalid related URLs"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="topics",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Topics"),
        ),
    ]
