# Generated by Django 5.1.1 on 2024-10-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0010_alter_chapter_invalid_urls_alter_chapter_leaders_raw_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="invalid_urls",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Entity invalid related URLs"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="leaders_raw",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Entity leaders list"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="related_urls",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Entity related URLs"
            ),
        ),
    ]
