# Generated by Django 5.1.2 on 2024-11-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0012_committee_invalid_urls_committee_leaders_raw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="track_issues",
            field=models.BooleanField(default=True, verbose_name="Track issues"),
        ),
    ]
