# Generated by Django 5.1.4 on 2024-12-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0013_project_track_issues"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="custom_tags",
            field=models.JSONField(default=list, verbose_name="Custom tags"),
        ),
    ]
