# Generated by Django 5.1.6 on 2025-03-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0018_merge_20250302_1945"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("appsec_days", "AppSec Days"),
                    ("global", "Global"),
                    ("other", "Other"),
                    ("partner", "Partner"),
                ],
                default="other",
                max_length=11,
                verbose_name="Category",
            ),
        ),
    ]
