# Generated by Django 5.1.6 on 2025-03-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0020_snapshot_key_snapshot_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snapshot",
            name="key",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
