# Generated by Django 5.1.5 on 2025-03-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0021_alter_snapshot_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="Key"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "sort_name",
                    models.CharField(max_length=255, verbose_name="Sort Name"),
                ),
                ("url", models.URLField(blank=True, verbose_name="Website URL")),
                ("job_url", models.URLField(blank=True, verbose_name="Job URL")),
                (
                    "image_url",
                    models.CharField(blank=True, max_length=255, verbose_name="Image Path"),
                ),
                (
                    "is_member",
                    models.BooleanField(default=False, verbose_name="Is Corporate Sponsor"),
                ),
                (
                    "member_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Platinum", "Platinum"),
                            ("Gold", "Gold"),
                            ("Silver", "Silver"),
                        ],
                        default="Silver",
                        max_length=20,
                        verbose_name="Member Type",
                    ),
                ),
                (
                    "sponsor_type",
                    models.CharField(
                        choices=[
                            ("Diamond", "Diamond"),
                            ("Platinum", "Platinum"),
                            ("Gold", "Gold"),
                            ("Silver", "Silver"),
                            ("Supporter", "Supporter"),
                            ("Not a Sponsor", "Not Sponsor"),
                        ],
                        default="Not a Sponsor",
                        max_length=20,
                        verbose_name="Sponsor Type",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sponsors",
                "db_table": "owasp_sponsors",
            },
        ),
    ]
