# Generated by Django 5.1.7 on 2025-03-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0025_remove_event_country_remove_event_postal_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="leaders_raw",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Entity leaders list"
            ),
        ),
    ]
