# Generated by Django 5.1.7 on 2025-03-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0026_chapter_leaders_raw"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="invalid_urls",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Entity invalid related URLs"
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="related_urls",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Entity related URLs"
            ),
        ),
    ]
