# Generated by Django 5.1.7 on 2025-03-13 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0026_post"),
        ("owasp", "0027_chapter_invalid_urls_chapter_related_urls"),
    ]

    operations = []
