# Generated by Django 5.2 on 2025-05-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0031_alter_chapter_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Description"
            ),
        ),
    ]
