# Generated by Django 5.2 on 2025-05-10 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0031_chapter_leaders_chapter_suggested_leaders_and_more"),
        ("owasp", "0032_alter_chapter_description_and_more"),
    ]

    operations = []
