# Generated by Django 5.2 on 2025-05-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0026_alter_organization_company_and_more"),
        ("owasp", "0033_merge_20250510_0037"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="leaders",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_%(class)s",
                to="github.user",
                verbose_name="Leaders",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="suggested_leaders",
            field=models.ManyToManyField(
                blank=True,
                related_name="matched_%(class)s",
                to="github.user",
                verbose_name="Suggested leaders",
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="leaders",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_%(class)s",
                to="github.user",
                verbose_name="Leaders",
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="suggested_leaders",
            field=models.ManyToManyField(
                blank=True,
                related_name="matched_%(class)s",
                to="github.user",
                verbose_name="Suggested leaders",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="leaders",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_%(class)s",
                to="github.user",
                verbose_name="Leaders",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="suggested_leaders",
            field=models.ManyToManyField(
                blank=True,
                related_name="matched_%(class)s",
                to="github.user",
                verbose_name="Suggested leaders",
            ),
        ),
    ]
