# Generated by Django 5.2.2 on 2025-06-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0037_alter_projecthealthmetrics_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projecthealthmetrics",
            name="is_project_leaders_requirements_compliant",
        ),
        migrations.AddField(
            model_name="projecthealthmetrics",
            name="is_leaders_requirements_compliant",
            field=models.BooleanField(
                default=False, verbose_name="Is project leaders requirements compliant"
            ),
        ),
    ]
