# Generated by Django 5.2.2 on 2025-06-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "owasp",
            "0039_rename_is_leaders_requirements_compliant_projecthealthmetrics_is_leader_requirements_compliant",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecthealthmetrics",
            name="is_leader_requirements_compliant",
            field=models.BooleanField(
                default=False, verbose_name="Is leader requirements compliant"
            ),
        ),
    ]
