# Generated by Django 5.2.2 on 2025-06-14 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0041_projecthealthrequirements_is_funding_requirements_compliant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecthealthmetrics",
            name="score",
            field=models.FloatField(
                blank=True,
                help_text="0-100",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
                verbose_name="Project health score",
            ),
        ),
    ]
