# Generated by Django 5.2.3 on 2025-06-21 18:25

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0042_alter_projecthealthmetrics_score"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="projecthealthmetrics",
            constraint=models.UniqueConstraint(
                django.db.models.functions.datetime.TruncDate("nest_created_at"),
                models.F("project"),
                name="unique_daily_project_health_metrics",
            ),
        ),
    ]
