# Generated by Django 5.2.4 on 2025-07-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0032_user_github_user_created_at_desc_and_more"),
        ("owasp", "0043_projecthealthmetrics_unique_daily_project_health_metrics"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(fields=["-updated_at"], name="chapter_updated_at_desc_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["-updated_at"], name="project_updated_at_desc_idx"),
        ),
    ]
