# Generated by Django 5.2.4 on 2025-08-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0044_chapter_chapter_updated_at_desc_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "css_class",
                    models.CharField(default="", max_length=255, verbose_name="CSS Class"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Description"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Name")),
                ("weight", models.PositiveSmallIntegerField(default=0, verbose_name="Weight")),
            ],
            options={
                "verbose_name_plural": "Badges",
                "db_table": "owasp_badges",
                "ordering": ["weight", "name"],
            },
        ),
    ]
