# Generated by Django 5.2.5 on 2025-08-10 09:18

from django.db import migrations, models

import apps.owasp.models.enums.project


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0044_chapter_chapter_updated_at_desc_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="audience",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[apps.owasp.models.enums.project.validate_audience],
                verbose_name="Audience",
            ),
        ),
    ]
