# Generated by Django 5.2.7 on 2025-10-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0053_entitychannel"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["-end_date"], name="event_end_date_desc_idx"),
        ),
    ]
