# Generated by Django 5.2.7 on 2025-10-18 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "github",
            "0037_rename_github_rele_created_d51966_idx_release_created_at_desc_idx_and_more",
        ),
        ("owasp", "0054_event_event_end_date_desc_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owasp_slack_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Member's Slack user ID in OWASP workspace",
                        max_length=20,
                        verbose_name="OWASP Slack ID",
                    ),
                ),
                (
                    "github_user",
                    models.OneToOneField(
                        help_text="Associated GitHub user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owasp_profile",
                        to="github.user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Member Profiles",
                "db_table": "owasp_member_profiles",
            },
        ),
    ]
