# Generated by Django 5.2.7 on 2025-10-19 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "github",
            "0037_rename_github_rele_created_d51966_idx_release_created_at_desc_idx_and_more",
        ),
        ("owasp", "0055_memberprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_at",
                    models.DateTimeField(
                        help_text="Start of the snapshot period", verbose_name="Start Date"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        help_text="End of the snapshot period", verbose_name="End Date"
                    ),
                ),
                (
                    "issues_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of issues created during this period",
                        verbose_name="Issues Count",
                    ),
                ),
                (
                    "pull_requests_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of pull requests created during this period",
                        verbose_name="Pull Requests Count",
                    ),
                ),
                (
                    "discussions_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of discussions participated in during this period",
                        verbose_name="Discussions Count",
                    ),
                ),
                (
                    "commits_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of commits made during this period",
                        verbose_name="Commits Count",
                    ),
                ),
                (
                    "github_user",
                    models.ForeignKey(
                        help_text="GitHub user for this snapshot",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contribution_snapshots",
                        to="github.user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Member Snapshots",
                "db_table": "owasp_member_snapshots",
                "unique_together": {("github_user", "start_at", "end_at")},
            },
        ),
    ]
