# Generated by Django 5.2.7 on 2025-10-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0057_remove_membersnapshot_commits_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membersnapshot",
            name="contribution_heatmap_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Daily contribution counts (YYYY-MM-DD -> count mapping)",
                verbose_name="Contribution Heatmap Data",
            ),
        ),
    ]
