# Generated by Django 5.2.7 on 2025-10-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0062_memberprofile_board_staff_flags"),
        ("slack", "0018_conversation_sync_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="membersnapshot",
            name="channel_communications",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Top 5 Slack channels by message count (channel_name -> count mapping)",
                verbose_name="Channel Communications",
            ),
        ),
        migrations.AddField(
            model_name="membersnapshot",
            name="communication_heatmap_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Daily Slack message counts (YYYY-MM-DD -> count mapping)",
                verbose_name="Communication Heatmap Data",
            ),
        ),
        migrations.AddField(
            model_name="membersnapshot",
            name="messages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Slack messages sent by the user during this period",
                related_name="member_snapshots",
                to="slack.message",
                verbose_name="Slack Messages",
            ),
        ),
    ]
