# Generated by Django 6.0.8 on 2026-08-31 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0072_project_project_name_gin_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardDiscussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("topic", models.CharField(max_length=500)),
                (
                    "participants",
                    models.ManyToManyField(blank=True, related_name="+", to="owasp.entitymember"),
                ),
            ],
            options={
                "verbose_name_plural": "Board Discussions",
                "db_table": "owasp_board_discussions",
            },
        ),
        migrations.CreateModel(
            name="BoardMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("call_in_url", models.URLField(blank=True, default="")),
                ("date", models.DateTimeField()),
                ("guests", models.JSONField(blank=True, default=list)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("quorum_present", models.BooleanField(blank=True, null=True)),
                ("recording_url", models.URLField(blank=True, default="")),
                ("source_checksum", models.CharField(blank=True, default="", max_length=64)),
                ("source_path", models.CharField(max_length=500, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("public", "Public"),
                            ("special", "Special"),
                            ("summit", "Summit"),
                        ],
                        default="public",
                        max_length=7,
                    ),
                ),
                (
                    "absentees",
                    models.ManyToManyField(blank=True, related_name="+", to="owasp.entitymember"),
                ),
                (
                    "attendees",
                    models.ManyToManyField(blank=True, related_name="+", to="owasp.entitymember"),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="owasp.boardofdirectors",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Board Meetings",
                "db_table": "owasp_board_meetings",
            },
        ),
        migrations.CreateModel(
            name="BoardMotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("background", models.TextField(blank=True, default="")),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("references", models.JSONField(blank=True, default=list)),
                ("title", models.CharField(max_length=500)),
                (
                    "amends_motion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="owasp.boardmotion",
                    ),
                ),
                (
                    "second",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="owasp.entitymember",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="owasp.entitymember",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Board Motions",
                "db_table": "owasp_board_motions",
            },
        ),
        migrations.CreateModel(
            name="BoardOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("in_progress", "In Progress"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=11,
                    ),
                ),
                (
                    "assignees",
                    models.ManyToManyField(blank=True, related_name="+", to="owasp.entitymember"),
                ),
            ],
            options={
                "verbose_name_plural": "Board Outcomes",
                "db_table": "owasp_board_outcomes",
            },
        ),
        migrations.CreateModel(
            name="BoardVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("deferred", "Deferred"),
                            ("failed", "Failed"),
                            ("passed", "Passed"),
                            ("tabled", "Tabled"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=9,
                    ),
                ),
                ("tally", models.CharField(blank=True, default="", max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("e_vote", "E-Vote"), ("vote", "Vote")],
                        default="vote",
                        max_length=6,
                    ),
                ),
                (
                    "abstain",
                    models.ManyToManyField(blank=True, related_name="+", to="owasp.entitymember"),
                ),
                (
                    "against",
                    models.ManyToManyField(blank=True, related_name="+", to="owasp.entitymember"),
                ),
                (
                    "in_favor",
                    models.ManyToManyField(blank=True, related_name="+", to="owasp.entitymember"),
                ),
                (
                    "motion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="owasp.boardmotion",
                    ),
                ),
                (
                    "recused",
                    models.ManyToManyField(blank=True, related_name="+", to="owasp.entitymember"),
                ),
            ],
            options={
                "verbose_name_plural": "Board Votes",
                "db_table": "owasp_board_votes",
            },
        ),
        migrations.CreateModel(
            name="BoardMeetingAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "discussion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="owasp.boarddiscussion",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="owasp.boardmeeting",
                    ),
                ),
                (
                    "motion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="owasp.boardmotion",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="owasp.boardoutcome",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Board Meeting Actions",
                "db_table": "owasp_board_meeting_actions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("meeting", "order"),
                        name="board_meeting_action_unique_meeting_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("discussion__isnull", False),
                                ("motion__isnull", True),
                                ("outcome__isnull", True),
                            ),
                            models.Q(
                                ("discussion__isnull", True),
                                ("motion__isnull", False),
                                ("outcome__isnull", True),
                            ),
                            models.Q(
                                ("discussion__isnull", True),
                                ("motion__isnull", True),
                                ("outcome__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="board_meeting_action_exactly_one_target",
                    ),
                ],
            },
        ),
    ]
