# Generated by Django 6.0.5 on 2026-05-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0040_merge_20251117_0136"),
        ("owasp", "0072_project_project_name_gin_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="frequency",
            field=models.CharField(
                choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                default="weekly",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="new_events",
            field=models.ManyToManyField(blank=True, related_name="snapshots", to="owasp.event"),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="new_posts",
            field=models.ManyToManyField(blank=True, related_name="snapshots", to="owasp.post"),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="new_pull_requests",
            field=models.ManyToManyField(
                blank=True, related_name="snapshots", to="github.pullrequest"
            ),
        ),
    ]
