# Generated by Django 6.0.6 on 2026-06-27 07:48

from django.db import migrations, models

import apps.owasp.models.crp.certificate


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0074_alter_certificate_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="id",
            field=models.CharField(
                default=apps.owasp.models.crp.certificate.generate_certificate_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                verbose_name="Certificate ID",
            ),
        ),
    ]
