# Generated by Django 6.0.6 on 2026-07-21 02:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_subscriptions(apps, schema_editor):
    """Migrate existing SnapshotSubscription entity targets to EntitySubscription."""
    snapshot_subscription_model = apps.get_model("owasp", "SnapshotSubscription")
    entity_subscription_model = apps.get_model("owasp", "EntitySubscription")
    max_active = 5

    for sub in snapshot_subscription_model.objects.all():
        chapters = list(sub.subscribed_chapters.all())
        projects = list(sub.subscribed_projects.all())
        active_count = 0

        for chapter in chapters:
            entity_subscription_model.objects.create(
                user=sub.user,
                frequency=sub.frequency,
                is_active=sub.is_active and active_count < max_active,
                chapter=chapter,
            )
            if sub.is_active:
                active_count += 1

        for project in projects:
            entity_subscription_model.objects.create(
                user=sub.user,
                frequency=sub.frequency,
                is_active=sub.is_active and active_count < max_active,
                project=project,
            )
            if sub.is_active:
                active_count += 1


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0075_snapshotsubscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntitySubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "unsubscribe_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_subscriptions",
                        to="owasp.chapter",
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_subscriptions",
                        to="owasp.committee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_subscriptions",
                        to="owasp.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entity Subscriptions",
                "db_table": "owasp_entity_subscriptions",
            },
        ),
        migrations.AddIndex(
            model_name="entitysubscription",
            index=models.Index(fields=["is_active"], name="owasp_entity_sub_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="entitysubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("chapter__isnull", True),
                        ("committee__isnull", True),
                        ("project__isnull", False),
                    ),
                    models.Q(
                        ("chapter__isnull", False),
                        ("committee__isnull", True),
                        ("project__isnull", True),
                    ),
                    models.Q(
                        ("chapter__isnull", True),
                        ("committee__isnull", False),
                        ("project__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="entity_sub_exactly_one_entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitysubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", False)),
                fields=("user", "project"),
                name="unique_user_project_subscription",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitysubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("chapter__isnull", False)),
                fields=("user", "chapter"),
                name="unique_user_chapter_subscription",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitysubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("committee__isnull", False)),
                fields=("user", "committee"),
                name="unique_user_committee_subscription",
            ),
        ),
        migrations.RunPython(
            migrate_existing_subscriptions,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="snapshotsubscription",
            name="subscribed_chapters",
        ),
        migrations.RemoveField(
            model_name="snapshotsubscription",
            name="subscribed_projects",
        ),
    ]
