# Generated by Django 5.2 on 2026-08-13 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0075_snapshotsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("failed", "Failed")], max_length=10
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="owasp.snapshot",
                    ),
                ),
                (
                    "snapshot_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="owasp.snapshotsubscription",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Email Logs",
                "db_table": "owasp_email_logs",
                "indexes": [
                    models.Index(fields=["-created_at"], name="owasp_email_log_created_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=["snapshot_subscription", "snapshot"],
                        condition=models.Q(status="sent"),
                        name="unique_email_per_subscription_snapshot",
                    )
                ],
            },
        ),
    ]
