# Generated by Django 6.0.8 on 2026-09-14 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0076_emaillog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snapshotsubscription",
            old_name="subscribed_chapters",
            new_name="chapters",
        ),
        migrations.RenameField(
            model_name="snapshotsubscription",
            old_name="subscribed_committees",
            new_name="committees",
        ),
        migrations.RenameField(
            model_name="snapshotsubscription",
            old_name="subscribed_projects",
            new_name="projects",
        ),
    ]
