# Generated by Django 6.0.8 on 2026-08-19 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0044_user_indexes"),
        ("owasp", "0076_remove_certificate_unique_active_cert_per_tier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="recipient",
            field=models.ForeignKey(
                help_text="Recipient GitHub user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="github.user",
            ),
        ),
        migrations.AddConstraint(
            model_name="certificate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tier__in", ["level_1", "level_2", "level_3", "level_4"]),
                    models.Q(
                        models.Q(("title", ""), _negated=True),
                        ("title__isnull", False),
                        models.Q(
                            models.Q(("project__isnull", False), ("chapter__isnull", True)),
                            models.Q(("project__isnull", True), ("chapter__isnull", False)),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="valid_certificate_type",
                violation_error_message="Certificate must be either a valid tier certificate or a generic certificate with a title and associated project/chapter.",
            ),
        ),
    ]
