# Generated by Django 6.0.5 on 2026-06-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0077_boardcandidateclaim_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardcandidateclaim",
            name="key",
            field=models.CharField(max_length=100, verbose_name="Key"),
        ),
        migrations.AlterField(
            model_name="boardcandidateclaim",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="boardcandidateclaimevidence",
            name="key",
            field=models.CharField(max_length=100, verbose_name="Key"),
        ),
        migrations.AlterField(
            model_name="boardcandidateclaimevidence",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AddConstraint(
            model_name="boardcandidateclaim",
            constraint=models.UniqueConstraint(
                fields=("candidate", "key"), name="owasp_claim_candidate_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="boardcandidateclaim",
            constraint=models.UniqueConstraint(
                fields=("candidate", "name"), name="owasp_claim_candidate_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="boardcandidateclaimevidence",
            constraint=models.UniqueConstraint(
                fields=("claim", "key"), name="owasp_evidence_claim_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="boardcandidateclaimevidence",
            constraint=models.UniqueConstraint(
                fields=("claim", "name"), name="owasp_evidence_claim_name_unique"
            ),
        ),
    ]
