# Generated by Django 6.0.8 on 2026-08-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0077_alter_certificate_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Certificate title', max_length=50, verbose_name='Title'),
        ),
    ]
