# Generated by Django 6.0.5 on 2026-06-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0078_alter_boardcandidateclaim_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardcandidateclaimevidence",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
    ]
