# Generated by Django 6.0.6 on 2026-08-07 15:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.owasp.models.board_candidate_claim_evidence
import apps.owasp.validators


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0080_boardcandidateclaimreview_boardofdirectors_reviewers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardcandidateclaim",
            name="source_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The exact text string from the candidate's profile this claim refers to.",
                verbose_name="Source text",
            ),
        ),
        migrations.AlterField(
            model_name="boardcandidateclaimevidence",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.owasp.models.board_candidate_claim_evidence.uuid_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpeg", "jpg", "pdf", "png", "webp"]
                    ),
                    apps.owasp.validators.validate_evidence_file_size,
                ],
                verbose_name="File",
            ),
        ),
        migrations.CreateModel(
            name="BoardCandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "raw_markdown",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The raw markdown content of the candidate's profile.",
                    ),
                ),
                (
                    "candidate",
                    models.OneToOneField(
                        help_text="The candidate this profile belongs to.",
                        limit_choices_to={"role": "candidate"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_profile",
                        to="owasp.entitymember",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Board Candidate Profiles",
                "db_table": "owasp_board_candidate_profile",
            },
        ),
    ]
