# Generated by Django 6.0.8 on 2026-08-29 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0081_boardcandidateclaim_source_text_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="boardcandidateprofile",
            table="owasp_board_candidate_profiles",
        ),
    ]
