# Generated by Django 6.0.6 on 2026-08-08 15:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.owasp.models.board_candidate_claim_evidence
import apps.owasp.validators


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0082_alter_boardcandidateprofile_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardcandidateclaim",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims",
                to="owasp.boardofdirectors",
            ),
        ),
        migrations.AlterField(
            model_name="boardcandidateclaimevidence",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.owasp.models.board_candidate_claim_evidence.uuid_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpeg", "jpg", "pdf", "png", "webp"]
                    ),
                    apps.owasp.validators.validate_evidence_file_size,
                ],
                verbose_name="File",
            ),
        ),
    ]
