# Generated by Django 6.0.6 on 2026-08-08 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0083_alter_boardcandidateclaim_board_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boardofdirectors",
            name="reviewers",
        ),
        migrations.AddField(
            model_name="boardofdirectors",
            name="claim_reviewers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Reviewers for this year's board election claims.",
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Claim reviewers",
            ),
        ),
    ]
