# Generated by Django 5.1.1 on 2024-10-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0011_alter_repository_funding_yml_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=1000, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="languages",
            field=models.JSONField(blank=True, default=dict, verbose_name="Languages"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="topics",
            field=models.JSONField(blank=True, default=list, verbose_name="Topics"),
        ),
    ]
