# Generated by Django 5.1.4 on 2025-01-13 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0014_repository_track_issues"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_releases",
                to="github.user",
            ),
        ),
    ]
