# Generated by Django 5.1.6 on 2025-02-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0015_alter_release_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_bot",
            field=models.BooleanField(default=False, verbose_name="Is bot"),
        ),
    ]
