# Generated by Django 5.1.7 on 2025-03-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0019_issue_github_issu_created_4afbcc_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="repositorycontributor",
            index=models.Index(
                fields=["user", "-contributions_count"], name="user_contributions_count_idx"
            ),
        ),
    ]
