# Generated by Django 5.2 on 2025-04-17 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0021_release_release_published_at_idx"),
        ("github", "0021_user_contributions_count"),
    ]

    operations = []
