# Generated by Django 5.2 on 2025-04-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0022_merge_20250417_1000"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contributions_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Contributions count"),
        ),
    ]
