# Generated by Django 5.2 on 2025-04-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0023_alter_user_contributions_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="twitter_username",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Twitter username"
            ),
        ),
    ]
