# Generated by Django 5.2 on 2025-05-10 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0026_alter_organization_company_and_more"),
        ("github", "0027_alter_milestone_table"),
    ]

    operations = []
