# Generated by Django 5.2.3 on 2025-06-21 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0028_merge_20250510_1542"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="is_owasp_organization",
            new_name="is_owasp_related_organization",
        ),
    ]
