# Generated by Django 5.2.4 on 2025-08-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0032_user_github_user_created_at_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Published at"),
        ),
    ]
