# Generated by Django 5.2.4 on 2025-07-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0032_user_github_user_created_at_desc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_owasp_staff",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the user is an OWASP staff member.",
                verbose_name="OWASP Staff",
            ),
        ),
    ]
