# Generated by Django 5.2.7 on 2025-10-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0036_user_has_public_member_page_alter_organization_name_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="release",
            new_name="release_created_at_desc_idx",
            old_name="github_rele_created_d51966_idx",
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["number"], name="github_issu_number_c195ce_idx"),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(fields=["tag_name"], name="release_tag_name_idx"),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["name"], name="repository_name_idx"),
        ),
    ]
