# Generated by Django 5.2.7 on 2025-10-19 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "github",
            "0037_rename_github_rele_created_d51966_idx_release_created_at_desc_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("node_id", models.CharField(unique=True, verbose_name="Node ID")),
                (
                    "sha",
                    models.CharField(
                        help_text="Git commit SHA hash", max_length=64, verbose_name="SHA"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="The commit message", verbose_name="Commit Message"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        help_text="When the commit was created", verbose_name="Created At"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who authored the commit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_commits",
                        to="github.user",
                    ),
                ),
                (
                    "committer",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who committed the commit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="committed_commits",
                        to="github.user",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        help_text="Repository containing this commit",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="github.repository",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Commits",
                "db_table": "github_commits",
                "indexes": [
                    models.Index(fields=["-created_at"], name="commit_created_at_desc_idx"),
                    models.Index(fields=["sha"], name="commit_sha_idx"),
                    models.Index(
                        fields=["repository", "-created_at"], name="commit_repo_created_idx"
                    ),
                ],
            },
        ),
    ]
