# Generated by Django 5.2.8 on 2025-11-17 01:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0039_merge_20251116_2015"),
        ("github", "0039_remove_commit_commit_repo_created_idx"),
    ]

    operations = []
