# Generated by Django 6.0.1 on 2026-01-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0040_merge_20251117_0136"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contribution_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Aggregated contribution data as date -> count mapping",
                verbose_name="Contribution heatmap data",
            ),
        ),
    ]
