# Generated by Django 6.0.1 on 2026-01-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0042_merge_20260127_2218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contribution_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Aggregated contribution data as date -> count mapping",
                null=True,
                verbose_name="Contribution heatmap data",
            ),
        ),
    ]
