# Generated by Django 6.0.7 on 2026-07-17 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('github', '0044_user_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nest_created_at', models.DateTimeField(auto_now_add=True)),
                ('nest_updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('pr_opened', 'PR Opened'), ('pr_closed', 'PR Closed'), ('pr_merged', 'PR Merged'), ('issue_opened', 'Issue Opened'), ('issue_closed', 'Issue Closed'), ('commit_pushed', 'Commit Pushed'), ('release_published', 'Release Published')], max_length=32, verbose_name='Activity Type')),
                ('occurred_at', models.DateTimeField(help_text='Timestamp when the activity event occurred on GitHub', verbose_name='Occurred at')),
                ('object_id', models.PositiveBigIntegerField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='github.user', verbose_name='Actor')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='github.repository', verbose_name='Repository')),
            ],
            options={
                'verbose_name_plural': 'Activity Events',
                'db_table': 'github_activity_events',
                'indexes': [models.Index(fields=['occurred_at'], name='activity_event_occurred_at_idx'), models.Index(fields=['activity_type'], name='activity_event_type_idx'), models.Index(fields=['repository'], name='activity_event_repository_idx'), models.Index(fields=['actor'], name='activity_event_actor_idx'), models.Index(fields=['content_type', 'object_id'], name='activity_event_source_idx')],
                'constraints': [models.UniqueConstraint(fields=('activity_type', 'content_type', 'object_id'), name='unique_activity_event')],
            },
        ),
    ]
