# Generated by Django 6.0.8 on 2026-09-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0044_user_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_summary_generated',
            field=models.BooleanField(default=False, verbose_name='Is summary generated'),
        ),
    ]
