# Generated by Django 6.0.8 on 2026-09-07 15:10

from django.db import migrations, models


def mark_existing_summaries(apps, schema_editor):
    Issue = apps.get_model("github", "Issue")
    Issue.objects.exclude(summary="").update(is_summary_generated=True)


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0044_user_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_summary_generated',
            field=models.BooleanField(default=False, verbose_name='Is summary generated'),
        ),
        migrations.RunPython(mark_existing_summaries, migrations.RunPython.noop),
    ]
