# Generated by Django 6.0.8 on 2026-09-08 20:00

from django.db import migrations, models


def mark_existing_summaries(apps, schema_editor):
    issue_model = apps.get_model("github", "Issue")
    issue_model.objects.exclude(summary__regex=r"^\s*$").update(summary_is_ai_generated=True)


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0044_user_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="summary_is_ai_generated",
            field=models.BooleanField(
                default=False,
                verbose_name="Summary is AI generated",
            ),
        ),
        migrations.RunPython(
            mark_existing_summaries,
            migrations.RunPython.noop,
        ),
    ]
