# Generated by Django 5.2 on 2025-05-10 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0004_workspace_member_channel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="bot_token",
        ),
    ]
