# Generated by Django 5.2 on 2025-05-10 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0026_alter_organization_company_and_more"),
        ("slack", "0005_remove_workspace_bot_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_bot",
            field=models.BooleanField(default=False, verbose_name="Is bot"),
        ),
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slack_users",
                to="github.user",
                verbose_name="User",
            ),
        ),
    ]
