# Generated by Django 5.2.1 on 2025-05-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0012_alter_conversation_total_members_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="total_members_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Members count"),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="total_members_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Members count"),
        ),
    ]
