# Generated by Django 5.2.2 on 2025-06-11 17:03

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0014_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_thread_parent",
        ),
        migrations.AddField(
            model_name="message",
            name="has_replies",
            field=models.BooleanField(default=False, verbose_name="Has replies"),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 11, 17, 3, 32, 737168, tzinfo=datetime.UTC),
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="slack_message_id",
            field=models.CharField(max_length=50, verbose_name="Slack message ID"),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(verbose_name="Text"),
        ),
    ]
