# Generated by Django 6.0.6 on 2026-06-22 20:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0022_workspace_invite_link_last_alert_message_ts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReactionAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message_ts",
                    models.CharField(
                        help_text="Slack timestamp of the message that triggered the alert.",
                        max_length=32,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        help_text="Report category for the emitted reaction alert.",
                        max_length=64,
                    ),
                ),
                ("reaction_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "alert_message_ts",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Slack timestamp of the posted reaction alert message.",
                        max_length=32,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="slack.conversation"
                    ),
                ),
            ],
            options={
                "db_table": "slack_reaction_alerts",
                "unique_together": {("conversation", "message_ts", "report_type")},
            },
        ),
        migrations.CreateModel(
            name="ReactionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "emoji_name",
                    models.CharField(
                        help_text="Slack emoji name that triggers this reaction rule.",
                        max_length=64,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        help_text="Report category recorded when this reaction rule triggers.",
                        max_length=64,
                    ),
                ),
                (
                    "threshold",
                    models.PositiveSmallIntegerField(
                        default=3, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "alert_channel_id",
                    models.CharField(
                        help_text="Slack channel ID where reaction alerts are posted.",
                        max_length=50,
                    ),
                ),
                ("alert_user_ids", models.JSONField(blank=True, default=list)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="slack.conversation"
                    ),
                ),
            ],
            options={
                "db_table": "slack_reaction_rules",
                "unique_together": {("conversation", "emoji_name")},
            },
        ),
    ]
