# Generated by Django 6.0.8 on 2026-08-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0023_reactionalert_reactionrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="reactionalert",
            name="reporter_user_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Slack user IDs that had the triggering reaction when the alert was posted."
                ),
            ),
        ),
    ]
