# Generated by Django 6.0.8 on 2026-08-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0024_reactionalert_reporter_user_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reactionrule",
            name="report_type",
            field=models.CharField(
                choices=[("spam", "Spam")],
                default="spam",
                help_text="Report category recorded when this reaction rule triggers.",
                max_length=64,
            ),
        ),
    ]
