# Generated by Django 6.0.8 on 2026-08-17 01:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0025_alter_reactionrule_report_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reactionrule",
            old_name="is_enabled",
            new_name="is_active",
        ),
    ]
