# Generated by Django 6.0.8 on 2026-08-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0026_rename_reactionrule_is_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reactionrule",
            name="emoji_name",
            field=models.CharField(
                help_text=(
                    "Slack emoji name that triggers this reaction rule, without leading or "
                    "trailing colons (spam, not :spam:)."
                ),
                max_length=64,
            ),
        ),
    ]
