# Generated by Django 6.0.7 on 2026-08-23 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0036_alter_workspace_invite_link_alert_user_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentreport",
            name="message",
            field=models.ForeignKey(
                blank=True,
                help_text="Stored Slack message when available (required for shortcut/command reports).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_reports",
                to="slack.message",
            ),
        ),
        migrations.AlterField(
            model_name="contentreport",
            name="reaction_count",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Unique emoji reporters at alert time; null for shortcut/command reports.",
                null=True,
            ),
        ),
    ]
