# Generated by Django 5.1 on 2024-08-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.CharField(default="", max_length=500, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="project",
            name="key",
            field=models.CharField(default="", max_length=100, verbose_name="Key"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="Name"),
            preserve_default=False,
        ),
    ]
