# Generated by Django 5.1 on 2024-08-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_project_description_project_key_project_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name_plural": "Projects"},
        ),
        migrations.AlterField(
            model_name="project",
            name="key",
            field=models.CharField(max_length=100, unique=True, verbose_name="Key"),
        ),
        migrations.AlterModelTable(
            name="project",
            table="projects",
        ),
    ]
