# Generated by Django 5.1 on 2024-08-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_project_owasp_repository_project_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="level",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("incubator", "Incubator"),
                    ("lab", "Lab"),
                    ("production", "Production"),
                    ("flagship", "Flagship"),
                ],
                default="unknown",
                max_length=20,
                verbose_name="Level",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("code", "Code"),
                    ("documentation", "Documentation"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
