FROM mcr.microsoft.com/playwright:v1.52.0-jammy

ENV FORCE_COLOR=1

WORKDIR /app

COPY --chmod=444 package.json pnpm-lock.yaml ./
RUN npm install --ignore-scripts -g pnpm && \
    pnpm install --frozen-lockfile --ignore-scripts

COPY __tests__/e2e __tests__/e2e
COPY __tests__/unit/data __tests__/unit/data
COPY next.config.ts postcss.config.js playwright.config.ts tailwind.config.js tsconfig.json ./
COPY public public
COPY src src
