FROM node:22-alpine

ENV FORCE_COLOR=1

WORKDIR /app

COPY --chmod=444 package.json pnpm-lock.yaml ./
RUN npm install --ignore-scripts -g pnpm && \
    pnpm install --frozen-lockfile --ignore-scripts && \
    chown node:node /app

COPY __tests__/unit __tests__/unit
COPY jest.config.ts jest.setup.ts tsconfig.json .pnpmrc ./
COPY public public
COPY src src

USER node
