FROM node:22-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH" \
    NPM_CONFIG_RETRY=5 \
    NPM_CONFIG_TIMEOUT=30000 \
    FORCE_COLOR=1


WORKDIR /app

COPY --chmod=444 package.json pnpm-lock.yaml ./
RUN npm install --ignore-scripts -g pnpm
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile --ignore-scripts && \
    chown node:node /app

COPY __tests__/unit __tests__/unit
COPY .pnpmrc jest.config.ts jest.setup.ts tsconfig.json ./
COPY public public
COPY src src

USER node
