FROM node:22-alpine AS builder

SHELL ["/bin/sh", "-o", "pipefail", "-c"]

ENV FORCE_COLOR=1

WORKDIR /app

COPY --chmod=444 package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && \
    pnpm install

COPY __tests__/unit __tests__/unit
COPY jest.config.ts jest.config.ts
COPY jest.setup.ts jest.setup.ts
COPY public public
COPY src src
COPY tsconfig.json tsconfig.json
