FROM node:22-alpine AS builder

ENV PNPM_HOME="/pnpm"
ENV NPM_CONFIG_RETRY=5 \
    NPM_CONFIG_TIMEOUT=30000 \
    PATH="$PNPM_HOME:$PATH"

WORKDIR /app

COPY --chmod=444 package.json pnpm-lock.yaml ./
RUN npm install --ignore-scripts -g pnpm
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile --ignore-scripts

FROM node:22-alpine

ENV FORCE_COLOR=1

WORKDIR /app

RUN chown node:node /app && \
    npm install --ignore-scripts -g pnpm
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/pnpm-lock.yaml /app/package.json ./

COPY __tests__/unit __tests__/unit
COPY .pnpmrc jest.config.ts jest.setup.ts tsconfig.json ./
COPY src src

USER node
