FROM mcr.microsoft.com/playwright:v1.51.0-noble
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
ENV FORCE_COLOR=1
WORKDIR /app
ADD package.json pnpm-lock.yaml /app/
ADD src/ /app/src/
ADD tests/ /app/tests/
ADD playwright.config.ts tsconfig.json .eslintrc.js /app/
RUN npm install -g pnpm && \
    pnpm install && \
    find /app -type f -exec chmod 644 {} \; && \
    find /app -type d -exec chmod 755 {} \;
