FROM node:22-slim AS builder

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ENV FORCE_COLOR=1

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY __tests__ __tests__
COPY jest.config.ts jest.config.ts
COPY jest.setup.ts jest.setup.ts
COPY public public
COPY src src
COPY tsconfig.json tsconfig.json

FROM node:22-slim

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ENV FORCE_COLOR=1

RUN apt-get update && \
    apt-get install -y --no-install-recommends && \
    apt-get clean -y && rm -rf /var/lib/apt/lists/* && \
    groupadd owasp && \
    useradd --create-home --home-dir /home/owasp -g owasp owasp

WORKDIR /home/owasp


COPY --from=builder /app/__tests__ ./__tests__
COPY --from=builder /app/jest.config.ts ./jest.config.ts
COPY --from=builder /app/jest.setup.ts ./jest.setup.ts
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/src ./src
COPY --from=builder /app/tsconfig.json ./tsconfig.json

USER owasp
