# Generated by Django 5.1.6 on 2025-02-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel_id",
                    models.TextField(default="", max_length=15, verbose_name="Channel ID"),
                ),
                (
                    "channel_name",
                    models.TextField(default="", max_length=100, verbose_name="Channel name"),
                ),
                ("command", models.TextField(default="", max_length=15, verbose_name="Command")),
                ("text", models.TextField(default="", max_length=1000, verbose_name="Text")),
                ("trigger", models.TextField(default="", max_length=100, verbose_name="Trigger")),
                ("user_id", models.TextField(max_length=15, verbose_name="User ID")),
                (
                    "user_name",
                    models.TextField(default="", max_length=100, verbose_name="User name"),
                ),
            ],
            options={
                "verbose_name_plural": "Events",
                "db_table": "slack_events",
            },
        ),
    ]
