# Generated by Django 5.1.7 on 2025-03-23 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0018_alter_issue_managers_alter_pullrequest_managers"),
        ("slack", "0003_remove_event_command"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slack_workspace_id",
                    models.CharField(max_length=50, unique=True, verbose_name="Workspace ID"),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=100, verbose_name="Workspace Name"),
                ),
                (
                    "bot_token",
                    models.CharField(default="", max_length=200, verbose_name="Bot Token"),
                ),
            ],
            options={
                "verbose_name_plural": "Workspaces",
                "db_table": "slack_workspaces",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.CharField(default="", max_length=100, verbose_name="Email")),
                (
                    "real_name",
                    models.CharField(default="", max_length=100, verbose_name="Real Name"),
                ),
                (
                    "slack_user_id",
                    models.CharField(max_length=50, unique=True, verbose_name="User ID"),
                ),
                (
                    "username",
                    models.CharField(default="", max_length=100, verbose_name="Username"),
                ),
                (
                    "suggested_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="matched_slack_users",
                        to="github.user",
                        verbose_name="github_user_suggestions",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slack_user",
                        to="github.user",
                        verbose_name="User",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="slack.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Members",
                "db_table": "slack_members",
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("is_private", models.BooleanField(default=False, verbose_name="Is Private")),
                (
                    "member_count",
                    models.PositiveIntegerField(default=0, verbose_name="Member Count"),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=100, verbose_name="Channel Name"),
                ),
                (
                    "slack_channel_id",
                    models.CharField(max_length=50, unique=True, verbose_name="Channel ID"),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="slack.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Channels",
                "db_table": "slack_channels",
            },
        ),
    ]
