# Generated by Django 5.1.7 on 2025-03-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0004_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="creator_id",
            field=models.CharField(max_length=255, verbose_name="Creator ID"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="entity_id",
            field=models.CharField(max_length=255, unique=True, verbose_name="Entity ID"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="Is Archived"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="is_general",
            field=models.BooleanField(default=False, verbose_name="Is General"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="is_private",
            field=models.BooleanField(default=False, verbose_name="Is Private"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="purpose",
            field=models.TextField(blank=True, default="", verbose_name="Purpose"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="topic",
            field=models.TextField(blank=True, default="", verbose_name="Topic"),
        ),
    ]
