# Generated by Django 5.2 on 2025-05-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0026_alter_organization_company_and_more"),
        ("slack", "0006_member_is_bot_alter_member_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Created at"),
        ),
        migrations.AddField(
            model_name="channel",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="Is archived"),
        ),
        migrations.AddField(
            model_name="channel",
            name="is_general",
            field=models.BooleanField(default=False, verbose_name="Is general"),
        ),
        migrations.AddField(
            model_name="channel",
            name="purpose",
            field=models.TextField(blank=True, default="", verbose_name="Purpose"),
        ),
        migrations.AddField(
            model_name="channel",
            name="slack_creator_id",
            field=models.CharField(default="1", max_length=255, verbose_name="Creator ID"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="channel",
            name="topic",
            field=models.TextField(blank=True, default="", verbose_name="Topic"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="is_private",
            field=models.BooleanField(default=False, verbose_name="Is private"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="member_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Member count"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="member",
            name="suggested_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="suggested_slack_users",
                to="github.user",
                verbose_name="Github user suggestions",
            ),
        ),
    ]
