# Generated by Django 5.2 on 2025-05-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0007_channel_created_at_channel_is_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="is_channel",
            field=models.BooleanField(default=False, verbose_name="Is channel"),
        ),
        migrations.AddField(
            model_name="channel",
            name="is_group",
            field=models.BooleanField(default=False, verbose_name="Is group"),
        ),
        migrations.AddField(
            model_name="channel",
            name="is_im",
            field=models.BooleanField(default=False, verbose_name="Is IM"),
        ),
        migrations.AddField(
            model_name="channel",
            name="is_mpim",
            field=models.BooleanField(default=False, verbose_name="Is MPIM"),
        ),
        migrations.AddField(
            model_name="channel",
            name="is_shared",
            field=models.BooleanField(default=False, verbose_name="Is shared"),
        ),
    ]
