# Generated by Django 5.2.1 on 2025-06-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0009_rename_channel_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='slack_workspace_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Workspace ID'),
        ),
    ]
