# Generated by Django 5.2.1 on 2025-05-23 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0009_rename_channel_conversation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reply_count",
                    models.PositiveIntegerField(default=0, verbose_name="Reply Count"),
                ),
                (
                    "slack_message_id",
                    models.CharField(max_length=50, verbose_name="Slack Message ID"),
                ),
                ("text", models.TextField(blank=True, verbose_name="Message Text")),
                (
                    "thread_timestamp",
                    models.CharField(blank=True, verbose_name="Thread Timestamp"),
                ),
                ("timestamp", models.DateTimeField(blank=True, verbose_name="Message Timestamp")),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="slack.conversation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Messages",
                "db_table": "slack_messages",
                "unique_together": {("conversation", "slack_message_id")},
            },
        ),
    ]
