# Generated by Django 5.2.1 on 2025-05-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0011_remove_conversation_member_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="total_members_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Member count"),
        ),
    ]
