# Generated by Django 5.2.1 on 2025-06-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0013_alter_conversation_total_members_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='total_members_count',
        ),
    ]
