# Generated by Django 5.2.1 on 2025-06-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0010_alter_workspace_slack_workspace_id'),
        ('slack', '0013_alter_conversation_total_members_count_and_more'),
    ]

    operations = [
    ]
