# Generated by Django 5.2.3 on 2025-06-18 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0015_remove_message_is_thread_parent_message_has_replies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="raw_data",
            field=models.JSONField(default=dict, verbose_name="Raw data"),
        ),
        migrations.AlterField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="slack.member",
            ),
        ),
    ]
