# Generated by Django 5.2.3 on 2025-06-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0015_remove_message_is_thread_parent_message_has_replies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_body",
            field=models.JSONField(default=dict, verbose_name="Message body"),
        ),
    ]
