# Generated by Django 5.2.3 on 2025-06-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0016_merge_20250618_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='total_members_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
