# Generated by Django 5.2.3 on 2025-06-21 02:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0016_message_raw_data_alter_message_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="text",
        ),
    ]
