# Generated by Django 5.2.3 on 2025-06-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0017_remove_message_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="sync_messages",
            field=models.BooleanField(default=False, verbose_name="Sync messages"),
        ),
    ]
