# Generated by Django for EntityChannel model

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0018_conversation_sync_messages"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                ("is_main_channel", models.BooleanField(default=False)),
                ("is_reviewed", models.BooleanField(default=False)),
                ("kind", models.CharField(default="slack", max_length=32)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="slack.conversation"
                    ),
                ),
            ],
            options={
                "unique_together": {("content_type", "object_id", "conversation")},
                "verbose_name": "Entity Channel",
                "verbose_name_plural": "Entity Channels",
            },
        ),
    ]
