# Generated by Django 5.2.4 on 2025-09-01 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0018_conversation_sync_messages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(default="", max_length=15, verbose_name="Channel ID"),
                ),
                ("message", models.TextField(verbose_name="Reminder Message")),
                ("remind_at", models.DateTimeField(verbose_name="Reminder Time")),
                ("periodic", models.BooleanField(default=False, verbose_name="Is Periodic")),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders",
                        to="slack.member",
                        verbose_name="Slack Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slack Reminder",
                "verbose_name_plural": "Slack Reminders",
                "db_table": "slack_reminders",
            },
        ),
    ]
