# Generated by Django 5.2.5 on 2025-08-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0018_conversation_sync_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_nest_bot_assistant_enabled",
            field=models.BooleanField(default=False, verbose_name="Is Nest Bot Assistant Enabled"),
        ),
    ]
