# Generated by Django 5.2.4 on 2025-08-11 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0018_conversation_sync_messages"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("access_token", models.TextField(blank=True, verbose_name="Access Token")),
                ("refresh_token", models.TextField(blank=True, verbose_name="Refresh Token")),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Token Expiry"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_auth",
                        to="slack.member",
                        verbose_name="Slack Member",
                    ),
                ),
            ],
        ),
    ]
