# Generated by Django 5.2.6 on 2025-10-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0019_conversation_is_nest_bot_assistant_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="conversation_context",
            field=models.TextField(blank=True, verbose_name="Conversation context"),
        ),
    ]
