# Generated by Django 6.0 on 2026-03-27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0019_conversation_is_nest_bot_assistant_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="invite_link_alert_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Slack channel ID for invite-limit alerts (e.g. C…); empty skips posting. "
                    "Used by slack_check_invite_link when posting warnings."
                ),
                max_length=32,
                verbose_name="Invite link alert channel ID",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="invite_link_alert_user_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    'Optional JSON list of Slack user IDs (e.g. ["U01ABC…"]). '
                    "A trailing cc: line with <@mentions> is added to invite-limit alerts."
                ),
                verbose_name="Invite alert Slack user IDs to mention",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="invite_link_alert_member_offset",
            field=models.PositiveSmallIntegerField(
                default=350,
                help_text=(
                    "Added to invite_link_member_count for the alert threshold (computed, not stored). "
                    "Slack shared invite cap is 400."
                ),
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Member count offset for invite alert threshold",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="invite_link_created_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "Committer time of the latest matching GitHub commit for the public invite include."
                ),
                null=True,
                verbose_name="Public invite link updated at",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="invite_link_commit_sha",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Full Git SHA of the latest matching commit for _includes/slack_invite.html "
                    "(used to link to the commit on GitHub)."
                ),
                max_length=40,
                verbose_name="Public invite link commit SHA",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="invite_link_last_alert_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When slack_check_invite_link last posted an invite-limit alert to Slack.",
                null=True,
                verbose_name="Last invite-limit alert sent at",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="invite_link_member_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "total_members_count from slack_sync_data when baseline was last set for the "
                    "current invite link."
                ),
                null=True,
                verbose_name="Member count when invite baseline was set",
            ),
        ),
    ]
