# Generated by Django 5.2.4 on 2025-08-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0019_googleauth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleauth",
            name="access_token",
            field=models.BinaryField(blank=True, verbose_name="Access Token"),
        ),
        migrations.AlterField(
            model_name="googleauth",
            name="refresh_token",
            field=models.BinaryField(blank=True, verbose_name="Refresh Token"),
        ),
    ]
