# Generated by Django 5.2.4 on 2025-08-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0019_entitychannel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitychannel',
            name='nest_created_at',
        ),
        migrations.RemoveField(
            model_name='entitychannel',
            name='nest_updated_at',
        ),
    ]
