# Generated by Django 5.2.4 on 2025-08-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0020_alter_googleauth_access_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleauth",
            name="access_token",
            field=models.BinaryField(null=True, verbose_name="Access Token"),
        ),
        migrations.AlterField(
            model_name="googleauth",
            name="expires_at",
            field=models.DateTimeField(null=True, verbose_name="Token Expiry"),
        ),
        migrations.AlterField(
            model_name="googleauth",
            name="refresh_token",
            field=models.BinaryField(null=True, verbose_name="Refresh Token"),
        ),
    ]
