# Generated by Django 6.0.3 on 2026-03-28 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0020_workspace_invite_link_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="invite_link_alert_channel_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Slack channel ID for invite-limit alerts (e.g. C…); empty skips posting. Used by slack_check_invite_link when posting warnings.",
                max_length=32,
                null=True,
                verbose_name="Invite link alert channel ID",
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="invite_link_alert_member_offset",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=350,
                help_text="Added to invite_link_member_count for the alert threshold (computed, not stored). Slack shared invite cap is 400. Database may contain NULL on restored legacy rows; those use 350 in application logic.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Member count offset for invite alert threshold",
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="invite_link_alert_user_ids",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='Optional JSON list of Slack user IDs (e.g. ["U01ABC…"]). A trailing cc: line with <@mentions> is added to invite-limit alerts.',
                null=True,
                verbose_name="Invite alert Slack user IDs to mention",
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="invite_link_commit_sha",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Full Git SHA of the latest matching commit for _includes/slack_invite.html (used to link to the commit on GitHub).",
                max_length=40,
                null=True,
                verbose_name="Public invite link commit SHA",
            ),
        ),
    ]
