# Generated by Django 6.0 on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0020_workspace_invite_link_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="invite_link_alert_user_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    'Optional JSON list of Slack user IDs (e.g. ["U01ABC…"]). '
                    "A trailing cc: line with <@mentions> is added to invite-limit alerts."
                ),
                verbose_name="Invite alert Slack user IDs to mention",
            ),
        ),
    ]
