# Generated by Django 6.0.3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0021_alter_workspace_invite_link_alert_channel_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="invite_link_alert_message_ts",
            field=models.CharField(
                blank=True,
                default=None,
                help_text=(
                    "Slack message timestamp (ts) of the last invite-limit alert. "
                    "Used to post a threaded resolution reply when the invite link is updated."
                ),
                max_length=32,
                null=True,
                verbose_name="Invite link alert message timestamp",
            ),
        ),
    ]
