# Generated by Django 5.2.4 on 2025-08-16 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0021_alter_googleauth_access_token_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="googleauth",
            options={"verbose_name_plural": "Google Auths"},
        ),
        migrations.AlterModelTable(
            name="googleauth",
            table="slack_google_auths",
        ),
    ]
