# Generated by Django 5.2.4 on 2025-08-17 15:03

from django.db import migrations

import apps.common.model_fields


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0022_alter_googleauth_options_alter_googleauth_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleauth",
            name="access_token",
            field=apps.common.model_fields.KmsEncryptedField(
                null=True, verbose_name="Access Token"
            ),
        ),
        migrations.AlterField(
            model_name="googleauth",
            name="refresh_token",
            field=apps.common.model_fields.KmsEncryptedField(
                null=True, verbose_name="Refresh Token"
            ),
        ),
    ]
