# Generated by Django 5.2.4 on 2025-08-20 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0022_alter_googleauth_options_alter_googleauth_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GoogleAuth",
        ),
    ]
