# Generated by Django 6.0.6 on 2026-06-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0024_rename_workspace_invite_link_last_alert_message_ts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="invite_link_last_alert_message_ts",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Slack message timestamp (ts) of the last invite-limit alert. Used to post a threaded resolution reply when the invite link is updated.",
                max_length=32,
                verbose_name="Last invite-limit alert message timestamp",
            ),
        ),
    ]
