# Generated by Django 6.0.6 on 2026-06-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0025_alter_workspace_invite_link_last_alert_message_ts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="invite_link_alert_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Slack channel ID for invite-limit alerts (e.g. C…, without # prefix); empty skips posting. Used by slack_check_invite_link when posting warnings.",
                max_length=32,
                verbose_name="Invite link alert channel ID",
            ),
        ),
    ]
