# Generated by Django 6.0.6 on 2026-06-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0026_alter_workspace_invite_link_alert_channel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="invite_link_alert_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Slack channel ID for invite-limit alerts (e.g. C..., without # prefix); empty skips posting. Used by slack_check_invite_link when posting warnings.",
                max_length=32,
                null=True,
                verbose_name="Invite link alert channel ID",
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="invite_link_commit_sha",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Full Git SHA of the latest matching commit for _includes/slack_invite.html (used to link to the commit on GitHub).",
                max_length=40,
                null=True,
                verbose_name="Public invite link commit SHA",
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="invite_link_last_alert_message_ts",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Slack message timestamp (ts) of the last invite-limit alert. Used to post a threaded resolution reply when the invite link is updated.",
                max_length=32,
                null=True,
                verbose_name="Last invite-limit alert message timestamp",
            ),
        ),
    ]
