version: 2
updates:
  - package-ecosystem: docker
    cooldown:
      default-days: 21
    directories:
      - docker/*
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - '*'
    schedule:
      interval: daily
    target-branch: main

  - package-ecosystem: docker-compose
    cooldown:
      default-days: 21
    directories:
      - docker-compose/*
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - '*'
    schedule:
      interval: daily
    target-branch: main

  - package-ecosystem: github-actions
    cooldown:
      default-days: 21
    directories:
      - /
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - '*'
    schedule:
      interval: daily
    target-branch: main

  - package-ecosystem: npm
    cooldown:
      default-days: 21
    directories:
      - cspell
      - frontend
      - frontend/__tests__/e2e
    groups:
      version-updates:
        applies-to: version-updates
        group-by: dependency-name
        patterns:
          - '*'
    schedule:
      interval: daily
    target-branch: main

  - package-ecosystem: pip
    cooldown:
      default-days: 21
    directories:
      - backend
      - docs
    groups:
      version-updates:
        applies-to: version-updates
        group-by: dependency-name
        patterns:
          - '*'
    schedule:
      interval: daily
    target-branch: main
