FROM node:22-slim

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN mkdir -p /home/owasp && \
    chown -R node:node /home/owasp && \
    apt-get update && apt-get upgrade -y && \
    apt-get clean -y && rm -rf /var/lib/apt/lists/*

EXPOSE 3000

USER node

WORKDIR /home/owasp
