FROM node:23 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:stable-alpine

RUN addgroup -S owasp && adduser -S owasp -G owasp

WORKDIR /home/owasp

COPY --from=builder /app/dist /usr/share/nginx/html

RUN chown -R owasp:owasp /usr/share/nginx/html

EXPOSE 80

USER owasp

CMD ["nginx", "-g", "daemon off;"]
