FROM node:22-slim

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ENV FORCE_COLOR=1

RUN groupadd owasp && \
    useradd --create-home --home-dir /home/owasp -g owasp owasp && \
    apt-get update && apt-get upgrade -y && \
    apt-get clean -y && rm -rf /var/lib/apt/lists/*

WORKDIR /home/owasp

COPY __mocks__ __mocks__
COPY __tests__ __tests__
COPY jest.config.ts jest.config.ts
COPY package-lock.json package-lock.json
COPY package.json package.json
COPY public public
COPY jest.setup.ts jest.setup.ts
COPY src src
COPY tsconfig.json tsconfig.json

RUN npm install

USER owasp
