ignoreScripts: true

# 21 days (in minutes)
minimumReleaseAge: 30240

minimumReleaseAgeExclude:
  - '@next/env@16.2.6'
  - '@next/swc-darwin-arm64@16.2.6'
  - '@next/swc-darwin-x64@16.2.6'
  - '@next/swc-linux-arm64-gnu@16.2.6'
  - '@next/swc-linux-arm64-musl@16.2.6'
  - '@next/swc-linux-x64-gnu@16.2.6'
  - '@next/swc-linux-x64-musl@16.2.6'
  - '@next/swc-win32-arm64-msvc@16.2.6'
  - '@next/swc-win32-x64-msvc@16.2.6'
  - brace-expansion@5.0.6
  - fast-uri@3.1.2
  - next@16.2.6
  - postcss@8.5.10
  - protobufjs@7.6.4
  - qs@6.15.2
  - rxjs@7.8.2
  - shell-quote@1.8.4
  - tmp@0.2.7
  - uuid@11.1.1
  - webpack@5.104.1
  - ws@8.21.0
  - dompurify@3.4.9

overrides:
  brace-expansion@5: 5.0.6
  fast-uri: 3.1.2
  glob: 11.1.0
  postcss: 8.5.10
  protobufjs: 7.6.4
  qs: 6.15.2
  rxjs: 7.8.2
  serialize-javascript: 7.0.5
  shell-quote: 1.8.4
  test-exclude: 7.0.2
  tmp: 0.2.7
  uuid: 11.1.1
  webpack@5: 5.104.1
  ws@8: 8.21.0

publicHoistPattern:
  - '*import-in-the-middle*'

saveExact: true

strictDepBuilds: true
