FROM python:3.13.11-alpine3.23 AS builder

ENV APK_CACHE_DIR="/home/owasp/.cache/apk-backend-test" \
    APK_SYMLINK_DIR="/etc/apk/cache" \
    OWASP_GID=1000 \
    OWASP_UID=1000 \
    PIP_CACHE_DIR="/home/owasp/.cache/pip" \
    POETRY_CACHE_DIR="/home/owasp/.cache/pypoetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    PYTHONUNBUFFERED=1

RUN mkdir -p ${APK_CACHE_DIR} ${POETRY_CACHE_DIR} && \
    ln -fns ${APK_CACHE_DIR} ${APK_SYMLINK_DIR}

RUN --mount=type=cache,target=${APK_CACHE_DIR} \
    apk update && apk upgrade && \
    addgroup -S -g ${OWASP_GID} owasp && \
    adduser -S -h /home/owasp -u ${OWASP_UID} -G owasp owasp && \
    chown -R owasp:owasp /home/owasp

RUN --mount=type=cache,target=${PIP_CACHE_DIR} \
    python -m pip install poetry --cache-dir ${PIP_CACHE_DIR}

WORKDIR /home/owasp
USER owasp

COPY --chmod=444 --chown=root:root poetry.lock pyproject.toml ./
RUN --mount=type=cache,target=${POETRY_CACHE_DIR},uid=${OWASP_UID},gid=${OWASP_GID} \
    poetry install --no-root --verbose

# Less likely to cause cache invalidation items go first.
COPY .env.example .env.example
COPY manage.py wsgi.py ./
COPY tests/__init__.py tests/__init__.py
COPY tests/conftest.py tests/conftest.py
COPY settings settings
COPY static static
COPY templates templates
COPY apps apps
COPY tests/apps tests/apps

FROM python:3.13.11-alpine3.23

RUN apk add --no-cache graphviz

RUN addgroup -S owasp && \
    adduser -S -h /home/owasp -G owasp owasp && \
    mkdir -p /home/owasp && \
    chown owasp:owasp /home/owasp

ENV FORCE_COLOR=1 \
    PATH="/home/owasp/.venv/bin:$PATH" \
    PYTHONUNBUFFERED=1

WORKDIR /home/owasp

COPY --from=builder /home/owasp /home/owasp
RUN chown -R owasp:owasp /home/owasp
RUN chmod -R go-w /home/owasp

USER owasp
