FROM python:3.13.7-alpine AS builder

SHELL ["/bin/sh", "-o", "pipefail", "-c"]

ENV PIP_CACHE_DIR="/home/owasp/.cache/pip" \
    PYTHONUNBUFFERED=1 \
    APK_CACHE_DIR="/home/owasp/.cache/apk-fuzz-stage" \
    APK_SYMLINK_DIR="/etc/apk/cache" \
    FORCE_COLOR=1

RUN mkdir -p ${APK_CACHE_DIR} && \
    ln -s ${APK_CACHE_DIR} ${APK_SYMLINK_DIR}

RUN --mount=type=cache,target=${APK_CACHE_DIR} \
    apk update && apk upgrade && \
    apk add curl jq && \
    addgroup -S owasp && \
    adduser -S -h /home/owasp -G owasp owasp

RUN --mount=type=cache,target=${PIP_CACHE_DIR} \
    python -m pip install --upgrade pip && \
    pip install schemathesis --cache-dir ${PIP_CACHE_DIR}

WORKDIR /home/owasp

COPY --chown=root:root --chmod=755 ./entrypoint.fuzz.sh ./entrypoint.sh
COPY --chown=root:root --chmod=755 tests/fuzz tests

RUN chmod +x ./entrypoint.sh

USER owasp
ENTRYPOINT ["./entrypoint.sh"]
