# Generated by Django 5.1 on 2024-08-19 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("github", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("key", models.CharField(max_length=100, unique=True, verbose_name="Key")),
                (
                    "description",
                    models.CharField(default="", max_length=500, verbose_name="Description"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("incubator", "Incubator"),
                            ("lab", "Lab"),
                            ("production", "Production"),
                            ("flagship", "Flagship"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Level",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("code", "Code"),
                            ("documentation", "Documentation"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("tags", models.JSONField(default=list, verbose_name="Tags")),
                (
                    "owasp_repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="github.repository",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Projects",
                "db_table": "projects",
            },
        ),
    ]
