# Generated by Django 5.1.1 on 2024-09-11 16:38

import django.db.models.deletion
from django.db import migrations, models

import apps.owasp.models.common


class Migration(migrations.Migration):
    dependencies = [
        (
            "github",
            "0001_initial",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="Key"),
                ),
                (
                    "description",
                    models.CharField(default="", max_length=500, verbose_name="Description"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("other", "Other"),
                            ("incubator", "Incubator"),
                            ("lab", "Lab"),
                            ("production", "Production"),
                            ("flagship", "Flagship"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Level",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("code", "Code"),
                            ("documentation", "Documentation"),
                            ("other", "Other"),
                            ("tool", "Tool"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("tags", models.JSONField(default=list, verbose_name="Tags")),
                (
                    "owasp_repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="github.repository",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Projects",
                "db_table": "projects",
            },
        ),
        migrations.AlterModelTable(
            name="project",
            table="owasp_projects",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="created_at",
            new_name="nest_created_at",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="updated_at",
            new_name="nest_updated_at",
        ),
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="Key"),
                ),
                (
                    "description",
                    models.CharField(default="", max_length=500, verbose_name="Description"),
                ),
                ("tags", models.JSONField(default=list, verbose_name="Tags")),
                (
                    "owasp_repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="github.repository",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Committees",
                "db_table": "owasp_committees",
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="Key"),
                ),
                (
                    "level",
                    models.CharField(default="", max_length=5, verbose_name="Level"),
                ),
                (
                    "country",
                    models.CharField(default="", max_length=50, verbose_name="Country"),
                ),
                (
                    "region",
                    models.CharField(default="", max_length=50, verbose_name="Region"),
                ),
                (
                    "postal_code",
                    models.CharField(default="", max_length=15, verbose_name="Postal code"),
                ),
                (
                    "currency",
                    models.CharField(default="", max_length=10, verbose_name="Currency"),
                ),
                (
                    "meetup_group",
                    models.CharField(default="", max_length=100, verbose_name="Meetup group"),
                ),
                ("tags", models.JSONField(default=list, verbose_name="Tags")),
                (
                    "owasp_repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="github.repository",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Chapters",
                "db_table": "owasp_chapters",
            },
            bases=(apps.owasp.models.common.GenericEntityModel, models.Model),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="Key"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
                (
                    "level",
                    models.CharField(blank=True, default="", max_length=5, verbose_name="Level"),
                ),
                ("url", models.URLField(blank=True, default="", verbose_name="URL")),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                (
                    "owasp_repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="github.repository",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Events",
                "db_table": "owasp_events",
            },
            bases=(apps.owasp.models.common.GenericEntityModel, models.Model),
        ),
        migrations.AddField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.RemoveField(
            model_name="project",
            name="owasp_repository",
        ),
        migrations.AddField(
            model_name="project",
            name="leaders_raw",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Project leaders list"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="level_raw",
            field=models.CharField(default="", max_length=50, verbose_name="Level raw"),
        ),
        migrations.AddField(
            model_name="project",
            name="type_raw",
            field=models.CharField(default="", max_length=100, verbose_name="Type raw"),
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Created at"),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="project",
            name="commits_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Commits"),
        ),
        migrations.AddField(
            model_name="project",
            name="contributors_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Contributors"),
        ),
        migrations.AddField(
            model_name="project",
            name="forks_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Forks"),
        ),
        migrations.AddField(
            model_name="project",
            name="open_issues_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Open issues"),
        ),
        migrations.AddField(
            model_name="project",
            name="releases_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Releases"),
        ),
        migrations.AddField(
            model_name="project",
            name="stars_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Stars"),
        ),
        migrations.AddField(
            model_name="project",
            name="subscribers_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Subscribers"),
        ),
        migrations.AddField(
            model_name="project",
            name="watchers_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Watchers"),
        ),
        migrations.AddField(
            model_name="project",
            name="pushed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Pushed at"),
        ),
        migrations.AddField(
            model_name="project",
            name="released_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Released at"),
        ),
        migrations.AddField(
            model_name="project",
            name="languages",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Languages"),
        ),
        migrations.AddField(
            model_name="project",
            name="licenses",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Licenses"),
        ),
        migrations.AddField(
            model_name="project",
            name="topics",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Topics"),
        ),
        migrations.AddField(
            model_name="project",
            name="has_active_repositories",
            field=models.BooleanField(default=True, verbose_name="Has active repositories"),
        ),
        migrations.AddField(
            model_name="project",
            name="owasp_repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="github.repository",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="organizations",
            field=models.ManyToManyField(
                blank=True, to="github.organization", verbose_name="Organizations"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="repositories",
            field=models.ManyToManyField(
                blank=True, to="github.repository", verbose_name="Repositories"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="owners",
            field=models.ManyToManyField(blank=True, to="github.user", verbose_name="Owners"),
        ),
        migrations.AddField(
            model_name="project",
            name="invalid_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                verbose_name="Invalid project related URLs",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="related_urls",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Project related URLs"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.JSONField(default=list, verbose_name="OWASP metadata tags"),
        ),
    ]
