# Generated by Django 5.1.6 on 2025-02-21 16:46

import django.db.models.deletion
from django.db import migrations, models

import apps.owasp.models.common


class Migration(migrations.Migration):
    replaces = [
        ("owasp", "0001_initial"),
        ("owasp", "0002_project_summary"),
        ("owasp", "0003_project_top_contributors"),
        ("owasp", "0004_remove_project_top_contributors"),
        ("owasp", "0005_chapter_latitude_chapter_longitude"),
        ("owasp", "0006_alter_chapter_currency_alter_chapter_level_and_more"),
        ("owasp", "0007_chapter_suggested_location"),
        ("owasp", "0008_chapter_description_chapter_has_active_repositories_and_more"),
        ("owasp", "0009_chapter_created_at_chapter_updated_at_and_more"),
        ("owasp", "0010_alter_chapter_invalid_urls_alter_chapter_leaders_raw_and_more"),
        ("owasp", "0011_alter_project_invalid_urls_alter_project_leaders_raw_and_more"),
        ("owasp", "0012_committee_invalid_urls_committee_leaders_raw_and_more"),
        ("owasp", "0013_project_track_issues"),
        ("owasp", "0014_project_custom_tags"),
        ("owasp", "0015_snapshot"),
        ("owasp", "0016_snapshot_new_issues_snapshot_new_releases_and_more"),
        ("owasp", "0017_alter_snapshot_options_and_more"),
        ("owasp", "0018_alter_snapshot_options_and_more"),
        ("owasp", "0019_alter_snapshot_options_and_more"),
    ]

    initial = True

    dependencies = [
        ("github", "0001_initial"),
        ("github", "0009_remove_repositorycontributor_node_id"),
        ("github", "0012_alter_repository_description_and_more"),
        ("github", "0015_alter_release_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("key", models.CharField(max_length=100, unique=True, verbose_name="Key")),
                (
                    "description",
                    models.CharField(default="", max_length=500, verbose_name="Description"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("other", "Other"),
                            ("incubator", "Incubator"),
                            ("lab", "Lab"),
                            ("production", "Production"),
                            ("flagship", "Flagship"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Level",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("code", "Code"),
                            ("documentation", "Documentation"),
                            ("other", "Other"),
                            ("tool", "Tool"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("tags", models.JSONField(default=list, verbose_name="Tags")),
                (
                    "owasp_repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="github.repository",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Projects",
                "db_table": "projects",
            },
        ),
        migrations.AlterModelTable(
            name="project",
            table="owasp_projects",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="created_at",
            new_name="nest_created_at",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="updated_at",
            new_name="nest_updated_at",
        ),
        migrations.AddField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.RemoveField(
            model_name="project",
            name="owasp_repository",
        ),
        migrations.AddField(
            model_name="project",
            name="level_raw",
            field=models.CharField(default="", max_length=50, verbose_name="Level raw"),
        ),
        migrations.AddField(
            model_name="project",
            name="type_raw",
            field=models.CharField(default="", max_length=100, verbose_name="Type raw"),
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Created at"),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="project",
            name="commits_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Commits"),
        ),
        migrations.AddField(
            model_name="project",
            name="contributors_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Contributors"),
        ),
        migrations.AddField(
            model_name="project",
            name="forks_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Forks"),
        ),
        migrations.AddField(
            model_name="project",
            name="open_issues_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Open issues"),
        ),
        migrations.AddField(
            model_name="project",
            name="releases_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Releases"),
        ),
        migrations.AddField(
            model_name="project",
            name="stars_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Stars"),
        ),
        migrations.AddField(
            model_name="project",
            name="subscribers_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Subscribers"),
        ),
        migrations.AddField(
            model_name="project",
            name="watchers_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Watchers"),
        ),
        migrations.AddField(
            model_name="project",
            name="pushed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Pushed at"),
        ),
        migrations.AddField(
            model_name="project",
            name="released_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Released at"),
        ),
        migrations.AddField(
            model_name="project",
            name="languages",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Languages"),
        ),
        migrations.AddField(
            model_name="project",
            name="licenses",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Licenses"),
        ),
        migrations.AddField(
            model_name="project",
            name="has_active_repositories",
            field=models.BooleanField(default=True, verbose_name="Has active repositories"),
        ),
        migrations.AddField(
            model_name="project",
            name="owasp_repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="github.repository",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="organizations",
            field=models.ManyToManyField(
                blank=True, to="github.organization", verbose_name="Organizations"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="repositories",
            field=models.ManyToManyField(
                blank=True, to="github.repository", verbose_name="Repositories"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="owners",
            field=models.ManyToManyField(blank=True, to="github.user", verbose_name="Owners"),
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.JSONField(default=list, verbose_name="OWASP metadata tags"),
        ),
        migrations.AddField(
            model_name="project",
            name="summary",
            field=models.TextField(blank=True, default="", verbose_name="Summary"),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("key", models.CharField(max_length=100, unique=True, verbose_name="Key")),
                (
                    "description",
                    models.CharField(default="", max_length=500, verbose_name="Description"),
                ),
                (
                    "level",
                    models.CharField(blank=True, default="", max_length=5, verbose_name="Level"),
                ),
                ("url", models.URLField(blank=True, default="", verbose_name="URL")),
                ("tags", models.JSONField(default=list, verbose_name="OWASP metadata tags")),
                (
                    "owasp_repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="github.repository",
                    ),
                ),
                (
                    "has_active_repositories",
                    models.BooleanField(default=True, verbose_name="Has active repositories"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("summary", models.TextField(blank=True, default="", verbose_name="Summary")),
                (
                    "topics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="GitHub repository topics",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name_plural": "Events",
                "db_table": "owasp_events",
            },
            bases=(apps.owasp.models.common.GenericEntityModel, models.Model),
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("key", models.CharField(max_length=100, unique=True, verbose_name="Key")),
                (
                    "level",
                    models.CharField(blank=True, default="", max_length=5, verbose_name="Level"),
                ),
                ("country", models.CharField(default="", max_length=50, verbose_name="Country")),
                ("region", models.CharField(default="", max_length=50, verbose_name="Region")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, default="", max_length=15, verbose_name="Postal code"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "meetup_group",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Meetup group"
                    ),
                ),
                ("tags", models.JSONField(default=list, verbose_name="OWASP metadata tags")),
                (
                    "owasp_repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="github.repository",
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True, verbose_name="Latitude")),
                ("longitude", models.FloatField(blank=True, null=True, verbose_name="Longitude")),
                (
                    "suggested_location",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Suggested location"
                    ),
                ),
                (
                    "description",
                    models.CharField(default="", max_length=500, verbose_name="Description"),
                ),
                (
                    "has_active_repositories",
                    models.BooleanField(default=True, verbose_name="Has active repositories"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("summary", models.TextField(blank=True, default="", verbose_name="Summary")),
                (
                    "topics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="GitHub repository topics",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name_plural": "Chapters",
                "db_table": "owasp_chapters",
            },
            bases=(apps.owasp.models.common.GenericEntityModel, models.Model),
        ),
        migrations.AddField(
            model_name="project",
            name="topics",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Topics"),
        ),
        migrations.AddField(
            model_name="project",
            name="invalid_urls",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Entity invalid related URLs"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="leaders_raw",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Entity leaders list"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="related_urls",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Entity related URLs"
            ),
        ),
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("key", models.CharField(max_length=100, unique=True, verbose_name="Key")),
                (
                    "description",
                    models.CharField(default="", max_length=500, verbose_name="Description"),
                ),
                ("tags", models.JSONField(default=list, verbose_name="OWASP metadata tags")),
                (
                    "owasp_repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="github.repository",
                    ),
                ),
                (
                    "has_active_repositories",
                    models.BooleanField(default=True, verbose_name="Has active repositories"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is active")),
                ("summary", models.TextField(blank=True, default="", verbose_name="Summary")),
                (
                    "topics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="GitHub repository topics",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Updated at"),
                ),
                (
                    "invalid_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Entity invalid related URLs",
                    ),
                ),
                (
                    "leaders_raw",
                    models.JSONField(
                        blank=True, default=list, null=True, verbose_name="Entity leaders list"
                    ),
                ),
                (
                    "related_urls",
                    models.JSONField(
                        blank=True, default=list, null=True, verbose_name="Entity related URLs"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Committees",
                "db_table": "owasp_committees",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="track_issues",
            field=models.BooleanField(default=True, verbose_name="Track issues"),
        ),
        migrations.AddField(
            model_name="project",
            name="custom_tags",
            field=models.JSONField(default=list, verbose_name="Custom tags"),
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "new_chapters",
                    models.ManyToManyField(
                        blank=True, related_name="snapshots", to="owasp.chapter"
                    ),
                ),
                (
                    "new_projects",
                    models.ManyToManyField(
                        blank=True, related_name="snapshots", to="owasp.project"
                    ),
                ),
                (
                    "new_issues",
                    models.ManyToManyField(
                        blank=True, related_name="snapshots", to="github.issue"
                    ),
                ),
                (
                    "new_releases",
                    models.ManyToManyField(
                        blank=True, related_name="snapshots", to="github.release"
                    ),
                ),
                (
                    "new_users",
                    models.ManyToManyField(blank=True, related_name="snapshots", to="github.user"),
                ),
            ],
            options={
                "indexes": [],
                "verbose_name_plural": "Snapshots",
            },
        ),
        migrations.AlterModelTable(
            name="snapshot",
            table="owasp_snapshots",
        ),
        migrations.AlterModelOptions(
            name="snapshot",
            options={"ordering": ["-start_at"], "verbose_name_plural": "Snapshots"},
        ),
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(fields=["status"], name="owasp_snaps_status_3f1675_idx"),
        ),
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(
                fields=["start_at", "end_at"], name="owasp_snaps_start_a_871170_idx"
            ),
        ),
        migrations.AlterModelOptions(
            name="snapshot",
            options={"verbose_name_plural": "Snapshots"},
        ),
        migrations.RemoveIndex(
            model_name="snapshot",
            name="owasp_snaps_status_3f1675_idx",
        ),
        migrations.RemoveIndex(
            model_name="snapshot",
            name="owasp_snaps_start_a_871170_idx",
        ),
    ]
