# Generated by Django 5.1.1 on 2024-09-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="summary",
            field=models.TextField(blank=True, default="", verbose_name="Summary"),
        ),
    ]
