# Generated by Django 5.1.1 on 2024-09-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0009_remove_repositorycontributor_node_id"),
        ("owasp", "0002_project_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="top_contributors",
            field=models.ManyToManyField(
                blank=True, to="github.repositorycontributor", verbose_name="Top contributors"
            ),
        ),
    ]
