# Generated by Django 5.1 on 2024-08-21 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0002_alter_project_level_alter_project_type"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="project",
            table="owasp_projects",
        ),
    ]
