# Generated by Django 5.1 on 2024-08-21 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0003_alter_project_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="created_at",
            new_name="nest_created_at",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="updated_at",
            new_name="nest_updated_at",
        ),
    ]
