# Generated by Django 5.1 on 2024-08-22 19:18

import django.db.models.deletion
from django.db import migrations, models

import apps.owasp.models.common


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0022_alter_organization_login_alter_user_login"),
        ("owasp", "0005_committee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("key", models.CharField(max_length=100, unique=True, verbose_name="Key")),
                ("level", models.CharField(default="", max_length=5, verbose_name="Level")),
                ("country", models.CharField(default="", max_length=50, verbose_name="Country")),
                ("region", models.CharField(default="", max_length=50, verbose_name="Region")),
                (
                    "postal_code",
                    models.CharField(default="", max_length=15, verbose_name="Postal code"),
                ),
                ("currency", models.CharField(default="", max_length=10, verbose_name="Currency")),
                (
                    "meetup_group",
                    models.CharField(default="", max_length=100, verbose_name="Meetup group"),
                ),
                ("tags", models.JSONField(default=list, verbose_name="Tags")),
                (
                    "owasp_repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="github.repository",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Chapters",
                "db_table": "owasp_chapters",
            },
            bases=(apps.owasp.models.common.MarkdownMetadata, models.Model),
        ),
    ]
