# Generated by Django 5.1.1 on 2024-10-04 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0012_alter_repository_description_and_more"),
        ("owasp", "0007_chapter_suggested_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="description",
            field=models.CharField(default="", max_length=500, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="chapter",
            name="has_active_repositories",
            field=models.BooleanField(default=True, verbose_name="Has active repositories"),
        ),
        migrations.AddField(
            model_name="chapter",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="chapter",
            name="summary",
            field=models.TextField(blank=True, default="", verbose_name="Summary"),
        ),
        migrations.AddField(
            model_name="chapter",
            name="topics",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                verbose_name="GitHub repository topics",
            ),
        ),
        migrations.AddField(
            model_name="committee",
            name="has_active_repositories",
            field=models.BooleanField(default=True, verbose_name="Has active repositories"),
        ),
        migrations.AddField(
            model_name="committee",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="committee",
            name="summary",
            field=models.TextField(blank=True, default="", verbose_name="Summary"),
        ),
        migrations.AddField(
            model_name="committee",
            name="topics",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                verbose_name="GitHub repository topics",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="has_active_repositories",
            field=models.BooleanField(default=True, verbose_name="Has active repositories"),
        ),
        migrations.AddField(
            model_name="event",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AddField(
            model_name="event",
            name="summary",
            field=models.TextField(blank=True, default="", verbose_name="Summary"),
        ),
        migrations.AddField(
            model_name="event",
            name="topics",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                verbose_name="GitHub repository topics",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="owasp_repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="github.repository",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="tags",
            field=models.JSONField(default=list, verbose_name="OWASP metadata tags"),
        ),
        migrations.AlterField(
            model_name="committee",
            name="owasp_repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="github.repository",
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="tags",
            field=models.JSONField(default=list, verbose_name="OWASP metadata tags"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(default="", max_length=500, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=models.JSONField(default=list, verbose_name="OWASP metadata tags"),
        ),
        migrations.AlterField(
            model_name="project",
            name="topics",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                verbose_name="GitHub repository topics",
            ),
        ),
    ]
