# Generated by Django 5.1 on 2024-08-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0008_alter_event_description_alter_event_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="level_raw",
            field=models.CharField(default="", max_length=50, verbose_name="Level raw"),
        ),
        migrations.AddField(
            model_name="project",
            name="type_raw",
            field=models.CharField(default="", max_length=50, verbose_name="Type raw"),
        ),
    ]
