# Generated by Django 5.1 on 2024-08-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0010_project_is_active_project_repositories_urls"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="repositories_urls",
        ),
        migrations.AddField(
            model_name="project",
            name="owasp_leaders",
            field=models.JSONField(default=list, verbose_name="OWASP site leaders list"),
        ),
        migrations.AddField(
            model_name="project",
            name="owasp_repositories_urls",
            field=models.JSONField(default=list, verbose_name="OWASP site repositories URLs list"),
        ),
    ]
