# Generated by Django 5.1.2 on 2024-10-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0011_alter_project_invalid_urls_alter_project_leaders_raw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="committee",
            name="invalid_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                verbose_name="Entity invalid related URLs",
            ),
        ),
        migrations.AddField(
            model_name="committee",
            name="leaders_raw",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Entity leaders list"
            ),
        ),
        migrations.AddField(
            model_name="committee",
            name="related_urls",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Entity related URLs"
            ),
        ),
    ]
