# Generated by Django 5.1 on 2024-08-25 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0026_repository_commits_count"),
        ("owasp", "0013_remove_project_owasp_repository_project_repositories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="repositories",
        ),
        migrations.AddField(
            model_name="project",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="github.repository",
            ),
        ),
    ]
