# Generated by Django 5.1 on 2024-08-25 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0026_repository_commits_count"),
        ("owasp", "0014_remove_project_repositories_project_repository"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="repository",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="github.repository",
                verbose_name="OWASP repository",
            ),
        ),
    ]
