# Generated by Django 5.1.5 on 2025-01-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0014_project_custom_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Anonymous", max_length=100)),
                ("email", models.EmailField(default="Anonymous", max_length=254)),
                ("message", models.TextField()),
                ("isAnonymous", models.BooleanField(default=True)),
                ("isNestbot", models.BooleanField(default=False)),
                ("s3_file_path", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedbacks",
            },
        ),
    ]
