# Generated by Django 5.1.5 on 2025-02-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0014_project_custom_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Category"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="category_description",
            field=models.TextField(blank=True, default="", verbose_name="Category Description"),
        ),
        migrations.AddField(
            model_name="event",
            name="dates",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Dates"),
        ),
        migrations.AddField(
            model_name="event",
            name="optional_text",
            field=models.TextField(blank=True, default="", verbose_name="Additional Text"),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start Date"),
        ),
    ]
