# Generated by Django 5.1.6 on 2025-02-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0015_projecthealthmetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHealthRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nest_created_at', models.DateTimeField(auto_now_add=True)),
                ('nest_updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('other', 'Other'), ('incubator', 'Incubator'), ('lab', 'Lab'), ('production', 'Production'), ('flagship', 'Flagship')], max_length=20, unique=True, verbose_name='Project Level')),
                ('contributors_count', models.PositiveIntegerField(default=0, verbose_name='Minimum Contributors')),
                ('creation_days', models.PositiveIntegerField(default=0, verbose_name='Minimum Project Age (days)')),
                ('forks_count', models.PositiveIntegerField(default=0, verbose_name='Minimum Forks')),
                ('last_release_days', models.PositiveIntegerField(default=0, verbose_name='Max Days Since Last Release')),
                ('last_commit_days', models.PositiveIntegerField(default=0, verbose_name='Max Days Since Last Commit')),
                ('open_issues_count', models.PositiveIntegerField(default=0, verbose_name='Max Open Issues')),
                ('open_pull_requests_count', models.PositiveIntegerField(default=0, verbose_name='Max Open PRs')),
                ('owasp_page_update_days', models.PositiveIntegerField(default=0, verbose_name='Max Days Since OWASP Update')),
                ('last_pull_request_days', models.PositiveIntegerField(default=0, verbose_name='Max Days Since Last PR')),
                ('recent_releases_count', models.PositiveIntegerField(default=0, verbose_name='Min Recent Releases')),
                ('recent_releases_window', models.PositiveIntegerField(default=0, verbose_name='Recent Releases Window')),
                ('stars_count', models.PositiveIntegerField(default=0, verbose_name='Minimum Stars')),
                ('total_pull_requests_count', models.PositiveIntegerField(default=0, verbose_name='Min Total PRs')),
                ('total_releases_count', models.PositiveIntegerField(default=0, verbose_name='Min Total Releases')),
                ('unanswered_issues_count', models.PositiveIntegerField(default=0, verbose_name='Max Unanswered Issues')),
                ('unassigned_issues_count', models.PositiveIntegerField(default=0, verbose_name='Max Unassigned Issues')),
            ],
            options={
                'verbose_name_plural': 'Project Health Reqauirements',
                'db_table': 'owasp_project_health_requirements',
                'ordering': ['level'],
            },
        ),
    ]
