# Generated by Django 5.1.5 on 2025-02-28 07:53

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0015_snapshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="event",
            name="has_active_repositories",
        ),
        migrations.RemoveField(
            model_name="event",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="event",
            name="level",
        ),
        migrations.RemoveField(
            model_name="event",
            name="owasp_repository",
        ),
        migrations.RemoveField(
            model_name="event",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="event",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="event",
            name="topics",
        ),
        migrations.RemoveField(
            model_name="event",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("global", "Global"),
                    ("appsec_days", "AppSec Days"),
                    ("partner", "Partner"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End Date"),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 28, 7, 53, 17, 155842, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Start Date",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
    ]
