# Generated by Django 5.1 on 2024-08-25 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0026_repository_commits_count"),
        ("owasp", "0015_alter_project_repository"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="repository",
        ),
        migrations.AddField(
            model_name="project",
            name="owasp_repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="github.repository",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="repositories",
            field=models.ManyToManyField(
                related_name="+", to="github.repository", verbose_name="Repositories"
            ),
        ),
    ]
