# Generated by Django 5.1 on 2024-08-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0026_repository_commits_count"),
        ("owasp", "0016_remove_project_repository_project_owasp_repository_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="leaders_raw",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Project leaders list"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="repositories",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="+",
                to="github.repository",
                verbose_name="Repositories",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="repositories_raw",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Project repositories list"
            ),
        ),
    ]
