# Generated by Django 5.1.6 on 2025-02-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0016_projecthealthmetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHealthRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nest_created_at', models.DateTimeField(auto_now_add=True)),
                ('nest_updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('other', 'Other'), ('incubator', 'Incubator'), ('lab', 'Lab'), ('production', 'Production'), ('flagship', 'Flagship')], max_length=10, unique=True, verbose_name='Project Level')),
                ('age_days', models.PositiveIntegerField(default=0, verbose_name='Project age (days)')),
                ('contributors_count', models.PositiveIntegerField(default=0, verbose_name='Contributors')),
                ('forks_count', models.PositiveIntegerField(default=0, verbose_name='Forks')),
                ('last_release_days', models.PositiveIntegerField(default=0, verbose_name='Days since last release')),
                ('last_commit_days', models.PositiveIntegerField(default=0, verbose_name='Days since last commit')),
                ('open_issues_count', models.PositiveIntegerField(default=0, verbose_name='Open issues')),
                ('open_pull_requests_count', models.PositiveIntegerField(default=0, verbose_name='Open PRs')),
                ('owasp_page_last_update_days', models.PositiveIntegerField(default=0, verbose_name='Days since OWASP update')),
                ('last_pull_request_days', models.PositiveIntegerField(default=0, verbose_name='Days since last PR')),
                ('recent_releases_count', models.PositiveIntegerField(default=0, verbose_name='Recent releases')),
                ('recent_releases_time_window_days', models.PositiveIntegerField(default=0, verbose_name='Recent releases window')),
                ('stars_count', models.PositiveIntegerField(default=0, verbose_name='Stars')),
                ('total_pull_requests_count', models.PositiveIntegerField(default=0, verbose_name='Total PRs')),
                ('total_releases_count', models.PositiveIntegerField(default=0, verbose_name='Total releases')),
                ('unanswered_issues_count', models.PositiveIntegerField(default=0, verbose_name='Unanswered issues')),
                ('unassigned_issues_count', models.PositiveIntegerField(default=0, verbose_name='Unassigned issues')),
            ],
            options={
                'verbose_name_plural': 'Project Health Requirements',
                'db_table': 'owasp_project_health_requirements',
                'ordering': ['level'],
            },
        ),
        migrations.DeleteModel(
            name='ProjectHealthMetrics',
        ),
    ]
