# Generated by Django 5.1.6 on 2025-02-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0016_snapshot_new_issues_snapshot_new_releases_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="snapshot",
            options={"verbose_name_plural": "Snapshots"},
        ),
        migrations.RemoveIndex(
            model_name="snapshot",
            name="owasp_snaps_status_a0cde6_idx",
        ),
        migrations.RemoveIndex(
            model_name="snapshot",
            name="owasp_snaps_start_a_025dfc_idx",
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterModelTable(
            name="snapshot",
            table="owasp_snapshots",
        ),
    ]
