# Generated by Django 5.1 on 2024-08-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0026_repository_commits_count"),
        ("owasp", "0017_alter_project_leaders_raw_alter_project_repositories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="repositories",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="github.repository", verbose_name="Repositories"
            ),
        ),
    ]
