# Generated by Django 5.1.6 on 2025-02-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0015_alter_release_author"),
        ("owasp", "0017_alter_snapshot_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="snapshot",
            options={"ordering": ["-start_at"], "verbose_name_plural": "Snapshots"},
        ),
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(fields=["status"], name="owasp_snaps_status_3f1675_idx"),
        ),
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(
                fields=["start_at", "end_at"], name="owasp_snaps_start_a_871170_idx"
            ),
        ),
    ]
