# Generated by Django 5.1.6 on 2025-03-02 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0016_remove_event_created_at_and_more"),
        ("owasp", "0017_projecthealthrequirements_and_more"),
    ]

    operations = []
