# Generated by Django 5.1.6 on 2025-02-20 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0018_alter_snapshot_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="snapshot",
            options={"verbose_name_plural": "Snapshots"},
        ),
        migrations.RemoveIndex(
            model_name="snapshot",
            name="owasp_snaps_status_3f1675_idx",
        ),
        migrations.RemoveIndex(
            model_name="snapshot",
            name="owasp_snaps_start_a_871170_idx",
        ),
    ]
