# Generated by Django 5.1 on 2024-08-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0018_alter_project_repositories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="level_raw",
            field=models.CharField(default="", max_length=100, verbose_name="Level raw"),
        ),
    ]
