# Generated by Django 5.1 on 2024-08-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0019_alter_project_level_raw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="level_raw",
            field=models.CharField(default="", max_length=50, verbose_name="Level raw"),
        ),
    ]
