# Generated by Django 5.1.6 on 2025-03-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0019_alter_event_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="key",
            field=models.CharField(default="", max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="snapshot",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
