# Generated by Django 5.1 on 2024-08-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0020_alter_project_level_raw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type_raw",
            field=models.CharField(default="", max_length=100, verbose_name="Type raw"),
        ),
    ]
