# Generated by Django 5.1 on 2024-08-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0021_alter_project_type_raw"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Created at"),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Updated at"),
        ),
    ]
