# Generated by Django 5.1.7 on 2025-03-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0022_sponsor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("entity_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                ("is_private", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_general", models.BooleanField(default=False)),
                ("topic", models.TextField(blank=True, default="")),
                ("purpose", models.TextField(blank=True, default="")),
                ("creator_id", models.CharField(max_length=255)),
                ("updated_at", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Conversations",
                "db_table": "slack_conversations",
            },
        ),
    ]
