# Generated by Django 5.1 on 2024-08-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0022_project_created_at_project_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="commits_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Commits"),
        ),
        migrations.AddField(
            model_name="project",
            name="contributors_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Contributors"),
        ),
        migrations.AddField(
            model_name="project",
            name="forks_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Forks"),
        ),
        migrations.AddField(
            model_name="project",
            name="open_issues_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Open issues"),
        ),
        migrations.AddField(
            model_name="project",
            name="releases_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Releases"),
        ),
        migrations.AddField(
            model_name="project",
            name="stars_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Stars"),
        ),
        migrations.AddField(
            model_name="project",
            name="subscribers_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Subscribers"),
        ),
        migrations.AddField(
            model_name="project",
            name="watchers_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Watchers"),
        ),
    ]
