# Generated by Django 5.1.6 on 2025-03-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0022_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nest_created_at', models.DateTimeField(auto_now_add=True)),
                ('nest_updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(verbose_name='Author name')),
                ('author_image', models.URLField(blank=True, null=True, verbose_name='Author image URL')),
                ('date', models.DateTimeField(verbose_name='Publication date')),
                ('title', models.CharField(verbose_name='Title')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'db_table': 'owasp_post',
            },
        ),
    ]
