# Generated by Django 5.1 on 2024-08-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0023_project_commits_count_project_contributors_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="pushed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Pushed at"),
        ),
        migrations.AddField(
            model_name="project",
            name="released_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Released at"),
        ),
    ]
