# Generated by Django 5.1.7 on 2025-03-07 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0023_conversation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="conversation",
            name="nest_created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conversation",
            name="nest_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name="conversation",
            table="owasp_slack_conversations",
        ),
    ]
