# Generated by Django 5.1.7 on 2025-03-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0023_event_latitude_event_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(default='', max_length=50, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='event',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.CharField(default='', max_length=50, verbose_name='Region'),
        ),
    ]
