# Generated by Django 5.1 on 2024-08-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0024_project_pushed_at_project_released_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="languages",
            field=models.JSONField(default=list, verbose_name="Languages"),
        ),
        migrations.AddField(
            model_name="project",
            name="licenses",
            field=models.JSONField(default=list, verbose_name="Licenses"),
        ),
        migrations.AddField(
            model_name="project",
            name="topics",
            field=models.JSONField(default=list, verbose_name="Topics"),
        ),
    ]
