# Generated by Django 5.1 on 2024-08-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0025_project_languages_project_licenses_project_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="languages",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Languages"),
        ),
        migrations.AlterField(
            model_name="project",
            name="licenses",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Licenses"),
        ),
        migrations.AlterField(
            model_name="project",
            name="topics",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Topics"),
        ),
    ]
