# Generated by Django 5.1 on 2024-08-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0026_alter_project_languages_alter_project_licenses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="has_active_repositories",
            field=models.BooleanField(default=True, verbose_name="Has active repositories"),
        ),
    ]
