# Generated by Django 5.1.1 on 2024-09-06 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0040_alter_issue_options_alter_issue_url"),
        ("owasp", "0027_project_has_active_repositories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="owasp_repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="github.repository",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="repositories",
            field=models.ManyToManyField(
                blank=True,
                related_name="project",
                to="github.repository",
                verbose_name="Repositories",
            ),
        ),
    ]
