# Generated by Django 5.1.7 on 2025-03-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0028_merge_20250313_1853"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="custom_tags",
            field=models.JSONField(blank=True, default=list, verbose_name="Custom tags"),
        ),
    ]
