# Generated by Django 5.1.1 on 2024-09-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0040_alter_issue_options_alter_issue_url"),
        ("owasp", "0028_alter_project_owasp_repository_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="repositories",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="github.repository",
                verbose_name="Repositories",
            ),
        ),
    ]
