# Generated by Django 5.1.1 on 2024-09-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0040_alter_issue_options_alter_issue_url"),
        ("owasp", "0029_alter_project_repositories"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="github.organization",
                verbose_name="Organizations",
            ),
        ),
    ]
