# Generated by Django 5.1.1 on 2024-09-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0040_alter_issue_options_alter_issue_url"),
        ("owasp", "0030_project_organizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="owners",
            field=models.ManyToManyField(blank=True, to="github.user", verbose_name="Users"),
        ),
        migrations.AlterField(
            model_name="project",
            name="organizations",
            field=models.ManyToManyField(
                blank=True, to="github.organization", verbose_name="Organizations"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="repositories",
            field=models.ManyToManyField(
                blank=True, to="github.repository", verbose_name="Repositories"
            ),
        ),
    ]
