# Generated by Django 5.1.7 on 2025-03-20 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0015_chapter_leaders_chapter_suggested_leaders_and_more"),
        ("owasp", "0030_chapter_is_leaders_policy_compliant_and_more"),
    ]

    operations = []
