# Generated by Django 5.2 on 2025-04-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0020_repositorycontributor_user_contrib_idx'),
        ('owasp', '0030_chapter_is_leaders_policy_compliant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(default=None, verbose_name='Created at'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['-created_at'], name='chapter_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-start_date'], name='event_start_date_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published_at'], name='post_published_at_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_at'], name='project_created_at_idx'),
        ),
    ]
