# Generated by Django 5.2 on 2025-04-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "github",
            "0024_alter_organization_email_alter_organization_location_and_more",
        ),
        ("owasp", "0031_alter_chapter_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="leaders",
            field=models.ManyToManyField(
                blank=True, related_name="led_projects", to="github.user"
            ),
        ),
    ]
