# Generated by Django 5.1.1 on 2024-09-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0040_alter_issue_options_alter_issue_url"),
        ("owasp", "0031_project_owners_alter_project_organizations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="owners",
            field=models.ManyToManyField(blank=True, to="github.user", verbose_name="Owners"),
        ),
    ]
