# Generated by Django 5.1.1 on 2024-09-07 01:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0032_alter_project_owners"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="repositories_raw",
            new_name="related_urls",
        ),
    ]
