# Generated by Django 5.1.1 on 2024-09-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0033_rename_repositories_raw_project_related_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="invalid_urls",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Invalid project related URLs"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="related_urls",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Project related URLs"
            ),
        ),
    ]
