# Generated by Django 5.1.1 on 2024-09-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0034_project_invalid_urls_alter_project_related_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.JSONField(default=list, verbose_name="OWASP metadata tags"),
        ),
    ]
