# Generated by Django 5.2.1 on 2025-06-03 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0034_alter_chapter_leaders_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projecthealthmetrics",
            old_name="total_pull_request_count",
            new_name="total_pull_requests_count",
        ),
    ]
