# Generated by Django 5.2.1 on 2025-06-08 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0036_alter_projecthealthmetrics_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecthealthmetrics",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_metrics",
                to="owasp.project",
            ),
        ),
    ]
