# Generated by Django 5.2.1 on 2025-06-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0037_alter_projecthealthmetrics_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecthealthmetrics",
            name="has_long_open_issues",
            field=models.BooleanField(default=False, verbose_name="Has long open issues"),
        ),
        migrations.AddField(
            model_name="projecthealthmetrics",
            name="has_long_unanswered_issues",
            field=models.BooleanField(default=False, verbose_name="Has long unanswered issues"),
        ),
        migrations.AddField(
            model_name="projecthealthmetrics",
            name="has_long_unassigned_issues",
            field=models.BooleanField(default=False, verbose_name="Has long unassigned issues"),
        ),
        migrations.AddField(
            model_name="projecthealthmetrics",
            name="has_no_recent_commits",
            field=models.BooleanField(default=False, verbose_name="Has no recent commits"),
        ),
    ]
