# Generated by Django 5.2.2 on 2025-06-12 23:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "owasp",
            "0038_remove_projecthealthmetrics_is_project_leaders_requirements_compliant_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="projecthealthmetrics",
            old_name="is_leaders_requirements_compliant",
            new_name="is_leader_requirements_compliant",
        ),
    ]
