# Generated by Django 5.2.1 on 2025-06-13 03:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0038_projecthealthmetrics_has_long_open_issues_and_more"),
        ("owasp", "0040_alter_projecthealthmetrics_is_leader_requirements_compliant"),
    ]

    operations = []
