# Generated by Django 5.2.2 on 2025-06-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0040_alter_projecthealthmetrics_is_leader_requirements_compliant"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecthealthrequirements",
            name="is_funding_requirements_compliant",
            field=models.BooleanField(
                default=True, verbose_name="Is funding requirements compliant"
            ),
        ),
        migrations.AddField(
            model_name="projecthealthrequirements",
            name="is_leader_requirements_compliant",
            field=models.BooleanField(
                default=True, verbose_name="Is leader requirements compliant"
            ),
        ),
    ]
