# Generated by Django 5.2.1 on 2025-06-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0041_merge_20250613_0336"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projecthealthmetrics",
            name="has_no_recent_commits",
        ),
        migrations.AddField(
            model_name="projecthealthmetrics",
            name="has_recent_commits",
            field=models.BooleanField(default=False, verbose_name="Has recent commits"),
        ),
    ]
