# Generated by Django 5.2.1 on 2025-06-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0042_remove_projecthealthmetrics_has_no_recent_commits_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projecthealthmetrics",
            name="has_recent_commits",
        ),
        migrations.AddField(
            model_name="projecthealthmetrics",
            name="has_no_recent_commits",
            field=models.BooleanField(default=False, verbose_name="Has no recent commits"),
        ),
    ]
