# Generated by Django 5.2.1 on 2025-06-15 03:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0042_alter_projecthealthmetrics_score"),
        ("owasp", "0043_remove_projecthealthmetrics_has_recent_commits_and_more"),
    ]

    operations = []
