# Generated by Django 5.2.4 on 2025-08-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0044_chapter_chapter_updated_at_desc_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="audience",
            field=models.JSONField(blank=True, default=list, verbose_name="Audience"),
        ),
    ]
