# Generated by Django 5.2.5 on 2025-08-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0033_alter_release_published_at"),
        ("owasp", "0044_chapter_chapter_updated_at_desc_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        help_text="Award category (e.g., 'WASPY', 'Lifetime Achievement')",
                        max_length=100,
                        verbose_name="Category",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Award name/title (e.g., 'Event Person of the Year')",
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Award description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True,
                        help_text="Year the award was given (null for category definitions)",
                        null=True,
                        verbose_name="Year",
                    ),
                ),
                (
                    "winner_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of the award recipient",
                        max_length=200,
                        verbose_name="Winner Name",
                    ),
                ),
                (
                    "winner_info",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed information about the winner",
                        verbose_name="Winner Information",
                    ),
                ),
                (
                    "winner_image",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path to winner's image",
                        max_length=500,
                        verbose_name="Winner Image",
                    ),
                ),
                (
                    "award_type",
                    models.CharField(
                        choices=[("category", "Category"), ("award", "Award")],
                        default="award",
                        help_text="Type of entry: category definition or individual award",
                        max_length=20,
                        verbose_name="Award Type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated GitHub user (if matched)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awards",
                        to="github.user",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Award",
                "verbose_name_plural": "Awards",
                "db_table": "owasp_awards",
                "indexes": [
                    models.Index(fields=["category", "year"], name="owasp_award_category_year"),
                    models.Index(fields=["-year"], name="owasp_award_year_desc"),
                    models.Index(fields=["name"], name="owasp_award_name"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "year", "category"), name="unique_award_name_year_category"
                    )
                ],
            },
        ),
    ]
