# Generated by Django 5.2.5 on 2025-08-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0033_alter_release_published_at"),
        ("owasp", "0044_chapter_chapter_updated_at_desc_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("WASPY", "WASPY"),
                            (
                                "Distinguished Lifetime Memberships",
                                "Distinguished Lifetime Memberships",
                            ),
                        ],
                        help_text="Award category (e.g., 'WASPY', 'Distinguished Lifetime Memberships')",
                        max_length=100,
                        verbose_name="Category",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Award name/title (e.g., 'Event Person of the Year')",
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Award description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="Year the award was given",
                        verbose_name="Year",
                    ),
                ),
                (
                    "winner_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of the award recipient",
                        max_length=200,
                        verbose_name="Winner Name",
                    ),
                ),
                (
                    "winner_info",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed information about the winner",
                        verbose_name="Winner Information",
                    ),
                ),
                (
                    "winner_image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL to winner's image",
                        verbose_name="Winner Image URL",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated GitHub user (if matched)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awards",
                        to="github.user",
                        verbose_name="User",
                    ),
                ),
                (
                    "is_reviewed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user matching has been verified by a human",
                        verbose_name="Is Reviewed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Award",
                "verbose_name_plural": "Awards",
                "db_table": "owasp_awards",
            },
        ),
    ]
