# Generated by Django 5.2.1 on 2025-06-17 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0044_merge_20250615_0346"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projecthealthmetrics",
            name="has_long_open_issues",
        ),
        migrations.RemoveField(
            model_name="projecthealthmetrics",
            name="has_long_unanswered_issues",
        ),
        migrations.RemoveField(
            model_name="projecthealthmetrics",
            name="has_long_unassigned_issues",
        ),
        migrations.RemoveField(
            model_name="projecthealthmetrics",
            name="has_no_recent_commits",
        ),
    ]
