# Generated by Django 5.2.4 on 2025-08-10 22:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0045_badge"),
        ("owasp", "0045_project_audience"),
    ]

    operations = []
