# Generated by Django 5.2.5 on 2025-08-13 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("github", "0034_merge_20250804_1817"),
        ("owasp", "0046_merge_0045_badge_0045_project_audience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="leaders",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="suggested_leaders",
        ),
        migrations.RemoveField(
            model_name="committee",
            name="leaders",
        ),
        migrations.RemoveField(
            model_name="committee",
            name="suggested_leaders",
        ),
        migrations.RemoveField(
            model_name="project",
            name="leaders",
        ),
        migrations.RemoveField(
            model_name="project",
            name="suggested_leaders",
        ),
        migrations.CreateModel(
            name="EntityMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional role or description"),
                ),
                (
                    "is_reviewed",
                    models.BooleanField(
                        default=False, help_text="Indicates if the membership is verified"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order/priority of members"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("leader", "Leader")], default="leader", max_length=20
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_memberships",
                        to="github.user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entity Members",
                "db_table": "owasp_entity_members",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="owasp_entit_content_969a6f_idx"
                    ),
                    models.Index(fields=["member"], name="owasp_entit_member__6e516f_idx"),
                ],
                "unique_together": {("content_type", "object_id", "member", "kind")},
            },
        ),
    ]
