# Generated by Django 5.2.5 on 2025-08-13 03:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0046_merge_0045_badge_0045_project_audience"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Badge",
        ),
    ]
