# Generated by Django 5.2.5 on 2025-08-14 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("github", "0034_merge_20250804_1817"),
        ("owasp", "0047_delete_badge"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Optional role or description"
                    ),
                ),
                ("entity_id", models.PositiveIntegerField()),
                (
                    "is_reviewed",
                    models.BooleanField(
                        default=False, help_text="Indicates if the membership is verified"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("leader", "Leader")], default="leader", max_length=6
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order/priority of members"
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="github.user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entity members",
                "db_table": "owasp_entity_members",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="owasp_entit_entity__dda41b_idx"
                    ),
                    models.Index(fields=["member"], name="owasp_entit_member__6e516f_idx"),
                ],
                "unique_together": {("entity_type", "entity_id", "member", "kind")},
            },
        ),
    ]
