# Generated by Django 5.2.5 on 2025-08-17 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("github", "0034_merge_20250804_1817"),
        ("owasp", "0047_delete_badge"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional note or role description",
                        max_length=100,
                    ),
                ),
                ("entity_id", models.PositiveBigIntegerField()),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Indicates if the membership is active"
                    ),
                ),
                (
                    "is_reviewed",
                    models.BooleanField(
                        default=False, help_text="Indicates if the membership is reviewed"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Display order/priority of members"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("leader", "Leader"), ("member", "Member")],
                        default="leader",
                        max_length=6,
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="github.user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entity members",
                "db_table": "owasp_entity_members",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="owasp_entit_entity__dda41b_idx"
                    ),
                    models.Index(fields=["member"], name="owasp_entit_member__6e516f_idx"),
                ],
                "unique_together": {("entity_type", "entity_id", "member", "role")},
            },
        ),
    ]
