# Generated by Django 5.2.5 on 2025-08-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0047_add_is_level_compliant_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthealthrequirements',
            name='compliance_penalty_weight',
            field=models.FloatField(default=10.0, help_text='Percentage penalty applied to non-compliant projects (0-100)', verbose_name='Compliance penalty weight (%)'),
        ),
    ]
