# Generated by Django 5.2.4 on 2025-08-26 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0048_entitymember"),
        ("slack", "0018_conversation_sync_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="calendar_id",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="Calendar ID"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="channel_id",
            field=models.CharField(default="", max_length=15, verbose_name="Channel ID"),
        ),
        migrations.AddField(
            model_name="event",
            name="member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_events",
                to="slack.member",
                verbose_name="Slack Member",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("tentative", "Tentative"),
                    ("canceled", "Canceled"),
                ],
                default="confirmed",
                max_length=11,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[("calendar", "Calendar"), ("existing", "Existing")],
                default="existing",
                max_length=11,
                verbose_name="Type",
            ),
        ),
    ]
