# Generated by Django 5.2.5 on 2025-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0048_entitymember"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardOfDirectors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                "verbose_name_plural": "Board of Directors",
                "db_table": "owasp_board_of_directors",
            },
        ),
    ]
