# Generated by Django 5.2.4 on 2025-08-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0048_entitymember"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="calendar_id",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="Calendar ID"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("tentative", "Tentative"),
                    ("canceled", "Canceled"),
                ],
                default="confirmed",
                max_length=11,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[("calendar", "Calendar"), ("existing", "Existing")],
                default="existing",
                max_length=11,
                verbose_name="Type",
            ),
        ),
    ]
