# Generated by Django 5.2.5 on 2025-09-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0049_boardofdirectors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitymember",
            name="role",
            field=models.CharField(
                choices=[("candidate", "Candidate"), ("leader", "Leader"), ("member", "Member")],
                default="leader",
                max_length=9,
            ),
        ),
    ]
