# Generated by Django 5.2.4 on 2025-08-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0049_event_calendar_id_event_channel_id_event_member_and_more"),
        ("slack", "0018_conversation_sync_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("tentative", "Tentative"),
                    ("cancelled", "Cancelled"),
                ],
                default="confirmed",
                max_length=11,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["type"], name="event_type_idx"),
        ),
    ]
