# Generated by Django 5.2.6 on 2025-09-06 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0035_alter_user_bio_alter_user_is_owasp_staff"),
        ("owasp", "0050_alter_entitymember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitymember",
            name="member_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="entitymember",
            name="member_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="entitymember",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="github.user",
            ),
        ),
    ]
