# Generated by Django 5.2.4 on 2025-08-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0050_alter_event_status_event_event_type_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="event",
            name="event_type_idx",
        ),
        migrations.RemoveField(
            model_name="event",
            name="channel_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="member",
        ),
        migrations.RemoveField(
            model_name="event",
            name="type",
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("appsec_days", "AppSec Days"),
                    ("global", "Global"),
                    ("other", "Other"),
                    ("partner", "Partner"),
                    ("community", "Community"),
                ],
                default="other",
                max_length=11,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[("confirmed", "Confirmed")],
                default="confirmed",
                max_length=11,
                verbose_name="Status",
            ),
        ),
    ]
