# Generated by Django 5.2.6 on 2025-09-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("owasp", "0051_entitymember_member_email_entitymember_member_name_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="entitymember",
            name="owasp_entit_member__6e516f_idx",
        ),
        migrations.AlterUniqueTogether(
            name="entitymember",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="entitymember",
            name="member_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="entitymember",
            unique_together={("entity_type", "entity_id", "member_name", "role")},
        ),
    ]
