# Generated by Django 5.2.4 on 2025-09-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0051_remove_event_event_type_idx_remove_event_channel_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="calendar_id",
        ),
        migrations.AddField(
            model_name="event",
            name="google_calendar_id",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="Google Calendar ID"
            ),
        ),
    ]
