# Generated by Django 5.2.4 on 2025-09-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0052_remove_event_calendar_id_event_google_calendar_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="key",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Key"),
        ),
    ]
