# Generated by Django 5.2.6 on 2025-09-18 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0052_remove_entitymember_owasp_entit_member__6e516f_idx_and_more"),
        ("owasp", "0052_remove_event_calendar_id_event_google_calendar_id"),
    ]

    operations = []
