# Generated by Django 5.2.4 on 2025-09-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0052_remove_event_calendar_id_event_google_calendar_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(verbose_name="Start Date"),
        ),
    ]
