# Generated by Django 5.2.6 on 2025-09-30 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("owasp", "0052_remove_entitymember_owasp_entit_member__6e516f_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("channel_id", models.PositiveBigIntegerField()),
                ("entity_id", models.PositiveBigIntegerField()),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Indicates if this channel is active"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this is the main channel for the entity",
                    ),
                ),
                (
                    "is_reviewed",
                    models.BooleanField(
                        default=False, help_text="Indicates if the channel has been reviewed"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("slack", "Slack")],
                        default="slack",
                        help_text="Platform of the channel (e.g., Slack)",
                        max_length=5,
                    ),
                ),
                (
                    "channel_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity channel",
                "verbose_name_plural": "Entity channels",
                "db_table": "owasp_entity_channels",
                "unique_together": {("channel_id", "channel_type", "entity_id", "entity_type")},
            },
        ),
    ]
