# Generated by Django 5.2.4 on 2025-09-08 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0050_alter_entitymember_role"),
        ("owasp", "0053_alter_event_end_date_alter_event_start_date"),
    ]

    operations = []
