# Generated by Django 5.2.6 on 2025-10-08 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0053_merge_20250918_1659"),
        ("owasp", "0054_event_event_end_date_desc_idx"),
    ]

    operations = []
