# Generated by Django 5.2.6 on 2025-09-15 04:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0052_remove_entitymember_owasp_entit_member__6e516f_idx_and_more"),
        ("owasp", "0054_merge_20250908_0549"),
    ]

    operations = []
