# Generated by Django 5.2.6 on 2025-09-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0055_merge_20250915_0411"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
    ]
