# Generated by Django 5.2.7 on 2025-10-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0039_remove_commit_commit_repo_created_idx"),
        ("owasp", "0056_membersnapshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membersnapshot",
            name="commits_count",
        ),
        migrations.RemoveField(
            model_name="membersnapshot",
            name="discussions_count",
        ),
        migrations.RemoveField(
            model_name="membersnapshot",
            name="issues_count",
        ),
        migrations.RemoveField(
            model_name="membersnapshot",
            name="pull_requests_count",
        ),
        migrations.AddField(
            model_name="membersnapshot",
            name="commits",
            field=models.ManyToManyField(
                blank=True,
                help_text="Commits authored by the user during this period",
                related_name="member_snapshots",
                to="github.commit",
                verbose_name="Commits",
            ),
        ),
        migrations.AddField(
            model_name="membersnapshot",
            name="issues",
            field=models.ManyToManyField(
                blank=True,
                help_text="Issues created by the user during this period",
                related_name="member_snapshots",
                to="github.issue",
                verbose_name="Issues",
            ),
        ),
        migrations.AddField(
            model_name="membersnapshot",
            name="pull_requests",
            field=models.ManyToManyField(
                blank=True,
                help_text="Pull requests created by the user during this period",
                related_name="member_snapshots",
                to="github.pullrequest",
                verbose_name="Pull Requests",
            ),
        ),
    ]
