# Generated by Django 5.1.6 on 2025-10-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0058_membersnapshot_contribution_heatmap_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="first_contribution_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date of the member's first contribution to OWASP repositories",
                null=True,
                verbose_name="First OWASP Contribution",
            ),
        ),
    ]
