# Generated by Django 5.1.6 on 2025-10-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0059_memberprofile_first_contribution_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="membersnapshot",
            name="chapter_contributions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Contribution counts per chapter (chapter_key -> count mapping)",
                verbose_name="Chapter Contributions",
            ),
        ),
        migrations.AddField(
            model_name="membersnapshot",
            name="project_contributions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Contribution counts per project (project_key -> count mapping)",
                verbose_name="Project Contributions",
            ),
        ),
    ]
