# Generated by Django 5.2.7 on 2025-10-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0063_membersnapshot_channel_communications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="is_gsoc_mentor",
            field=models.BooleanField(
                default=False,
                help_text="Whether the member is a Google Summer of Code mentor",
                verbose_name="Is GSoC Mentor",
            ),
        ),
        migrations.AlterField(
            model_name="membersnapshot",
            name="channel_communications",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Top 5 Slack channels by message count (channel_name -> message_count)",
                verbose_name="Channel Communications",
            ),
        ),
    ]
