# Generated by Django 5.2.7 on 2025-10-25 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0064_memberprofile_is_gsoc_mentor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="linkedin_page_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="LinkedIn username or custom URL ID (e.g., 'john-doe-123')",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_linkedin_id",
                        message="LinkedIn ID must be 3-100 characters and contain only letters, numbers, and hyphens",
                        regex="^[a-zA-Z0-9\\-]{3,100}$",
                    )
                ],
                verbose_name="LinkedIn Page ID",
            ),
        ),
    ]
