# Generated by Django 5.2.8 on 2025-11-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0065_memberprofile_linkedin_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='contribution_data',
            field=models.JSONField(blank=True, default=dict, help_text='Daily contribution counts (YYYY-MM-DD -> count mapping)', verbose_name='Contribution Data'),
        ),
        migrations.AddField(
            model_name='project',
            name='contribution_data',
            field=models.JSONField(blank=True, default=dict, help_text='Daily contribution counts (YYYY-MM-DD -> count mapping)', verbose_name='Contribution Data'),
        ),
    ]
