# Generated by Django 6.0 on 2025-12-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0067_chapter_contribution_stats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="contribution_stats",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed contribution breakdown (commits, issues, pull requests, releases)",
                verbose_name="Contribution Statistics",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="contribution_stats",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed contribution breakdown (commits, issues, pull requests, releases)",
                verbose_name="Contribution Statistics",
            ),
        ),
    ]
