# Generated by Django 5.2.8 on 2025-11-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0067_memberprofile_backward_compatibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='has_public_member_page',
            field=models.BooleanField(default=True, help_text="Whether the member's profile is publicly visible on the OWASP website", verbose_name='Has Public Member Page'),
        ),
    ]
