# Generated by Django 6.0 on 2026-01-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0068_alter_chapter_contribution_stats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="contribution_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Daily contribution counts (YYYY-MM-DD -> count mapping)",
                null=True,
                verbose_name="Contribution Data",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="contribution_stats",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed contribution breakdown (commits, issues, pull requests, releases)",
                null=True,
                verbose_name="Contribution Statistics",
            ),
        ),
    ]
