# Generated by Django 6.0.1 on 2026-01-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0040_merge_20251117_0136'),
        ('owasp', '0069_alter_project_contribution_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published_releases',
            field=models.ManyToManyField(blank=True, related_name='published_in_projects', to='github.release'),
        ),
    ]
