# Generated by Django 6.0.1 on 2026-01-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0069_alter_project_contribution_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_level_non_compliant",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the project level does not match the official OWASP level",
                verbose_name="Is level non-compliant",
            ),
        ),
        migrations.AddField(
            model_name="projecthealthmetrics",
            name="is_level_non_compliant",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the project level does not match the official OWASP level",
                verbose_name="Is level non-compliant",
            ),
        ),
        migrations.AddField(
            model_name="projecthealthrequirements",
            name="is_level_non_compliant",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the project level does not match the official OWASP level",
                verbose_name="Is level non-compliant",
            ),
        ),
    ]
