# Generated by Django 6.0 on 2026-01-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0040_merge_20251117_0136"),
        ("owasp", "0069_alter_project_contribution_data_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(fields=["-created_at"], name="owasp_snapshot_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(fields=["key", "status"], name="owasp_snapshot_key_status_idx"),
        ),
    ]
