# Generated by Django 6.0 on 2026-01-07 11:29

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0070_snapshot_owasp_snapshot_created_at_idx_and_more"),
    ]

    operations = [
        TrigramExtension(),
    ]
