# Generated by Django 6.0.3 on 2026-05-31 10:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_default_scoring_weights(apps, _schema_editor):
    """Seed default ScoringWeight rows."""
    ScoringWeight = apps.get_model("owasp", "ScoringWeight")
    defaults = [
        {"event_type": "pr_merged", "score": 10, "daily_cap": None, "is_active": True},
        {"event_type": "pr_opened", "score": 5, "daily_cap": None, "is_active": True},
        {"event_type": "issue_opened", "score": 3, "daily_cap": None, "is_active": True},
    ]
    for row in defaults:
        ScoringWeight.objects.update_or_create(event_type=row["event_type"], defaults=row)


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0044_user_indexes'),
        ('owasp', '0072_project_project_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nest_created_at', models.DateTimeField(auto_now_add=True)),
                ('nest_updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('pr_merged', 'Pull Request Merged'), ('pr_opened', 'Pull Request Opened'), ('issue_opened', 'Issue Opened')], help_text='The type of contribution event', max_length=20, unique=True, verbose_name='Event Type')),
                ('score', models.PositiveIntegerField(help_text='Points awarded for this contribution type', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Score')),
                ('daily_cap', models.PositiveIntegerField(blank=True, help_text='Maximum points that can be earned for this event type in a single day', null=True, verbose_name='Daily Cap')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this scoring weight is currently active', verbose_name='Is Active')),
            ],
            options={
                'verbose_name_plural': 'Scoring Weights',
                'db_table': 'recognition_scoring_weights',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('nest_created_at', models.DateTimeField(auto_now_add=True)),
                ('nest_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Certificate ID')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], help_text='The tier at which the certificate was issued', max_length=20, verbose_name='Tier')),
                ('score', models.PositiveIntegerField(help_text="The contributor's score when the certificate was issued", verbose_name='Score')),
                ('issued_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the certificate was issued', verbose_name='Issued At')),
                ('is_revoked', models.BooleanField(default=False, help_text='Whether the certificate has been revoked', verbose_name='Is Revoked')),
                ('github_user', models.ForeignKey(help_text='Associated GitHub user', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='github.user')),
            ],
            options={
                'verbose_name_plural': 'Certificates',
                'db_table': 'recognition_certificates',
                'indexes': [models.Index(fields=['-issued_at'], name='cert_issued_at_desc'), models.Index(fields=['tier'], name='cert_tier_idx'), models.Index(fields=['is_revoked'], name='cert_revoked_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_revoked', False)), fields=('github_user', 'tier'), name='unique_active_cert_per_tier', violation_error_message='Cannot have multiple active certificates for same tier')],
            },
        ),
        migrations.CreateModel(
            name='ContributionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nest_created_at', models.DateTimeField(auto_now_add=True)),
                ('nest_updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveIntegerField(default=0, help_text='Aggregated contribution score', verbose_name='Value')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', help_text='Current contributor tier', max_length=20, verbose_name='Tier')),
                ('github_user', models.OneToOneField(help_text='Associated GitHub user', on_delete=django.db.models.deletion.CASCADE, related_name='contribution_score', to='github.user')),
            ],
            options={
                'verbose_name_plural': 'Contribution Scores',
                'db_table': 'recognition_contribution_scores',
                'indexes': [models.Index(fields=['-value'], name='score_total_desc_idx'), models.Index(fields=['tier'], name='score_tier_idx'), models.Index(fields=['-nest_updated_at'], name='score_updated_desc_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nest_created_at', models.DateTimeField(auto_now_add=True)),
                ('nest_updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(help_text='Date of the snapshot', verbose_name='Snapshot Date')),
                ('global_rank', models.PositiveIntegerField(help_text="Contributor's rank across all OWASP contributions", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Global Rank')),
                ('project_rank', models.PositiveIntegerField(help_text="Contributor's rank within a specific project", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Project Rank')),
                ('chapter_rank', models.PositiveIntegerField(help_text="Contributor's rank within a specific chapter", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Chapter Rank')),
                ('score', models.PositiveIntegerField(default=0, help_text='Total contribution score at the time of snapshot', verbose_name='Score')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], help_text="Contributor's tier at the time of snapshot", max_length=20, verbose_name='Tier')),
                ('chapter', models.ForeignKey(help_text='The chapter to which this ranking applies', on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_snapshots', to='owasp.chapter')),
                ('github_user', models.ForeignKey(help_text='Associated GitHub user', on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_snapshots', to='github.user')),
                ('project', models.ForeignKey(help_text='The project to which this ranking applies', on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_snapshots', to='owasp.project')),
            ],
            options={
                'verbose_name_plural': 'Leaderboard Snapshots',
                'db_table': 'recognition_leaderboard_snapshots',
                'indexes': [models.Index(fields=['-snapshot_date'], name='leaderboard_snapshot_date_desc'), models.Index(fields=['global_rank'], name='leaderboard_global_rank_idx'), models.Index(fields=['project_rank'], name='leaderboard_project_rank_idx'), models.Index(fields=['chapter_rank'], name='leaderboard_chapter_rank_idx'), models.Index(fields=['tier'], name='leaderboard_tier_idx'), models.Index(fields=['snapshot_date', '-global_rank'], name='leaderboard_snapshot_rank_idx')],
                'unique_together': {('github_user', 'project', 'chapter', 'snapshot_date')},
            },
        ),
        migrations.RunPython(
            seed_default_scoring_weights,
            migrations.RunPython.noop,
        ),
    ]
