# Generated by Django 6.0.5 on 2026-05-24 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0072_project_project_name_gin_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardCandidateClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(default="", verbose_name="Description")),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the claim is locked",
                        verbose_name="Is locked",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("DISCARDED", "Discarded"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Claim status",
                    ),
                ),
                ("title", models.CharField(max_length=1000, verbose_name="Title")),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_reason", models.TextField(blank=True)),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claims",
                        to="owasp.boardofdirectors",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="owasp.entitymember",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Board Candidate Claims",
                "db_table": "owasp_board_candidate_claim",
            },
        ),
        migrations.CreateModel(
            name="BoardCandidateClaimEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(default="", verbose_name="Description")),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="%Y/", verbose_name="File"),
                ),
                (
                    "file_name",
                    models.CharField(blank=True, max_length=1000, verbose_name="File Name"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="File Size (Bytes)"
                    ),
                ),
                (
                    "is_removed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the file is removed",
                        verbose_name="Is removed",
                    ),
                ),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("removed_reason", models.TextField(blank=True)),
                ("title", models.CharField(max_length=1000, verbose_name="Title")),
                ("source_url", models.TextField(blank=True, verbose_name="Source URL")),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="owasp.boardcandidateclaim",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Board Candidate Claim Evidences",
                "db_table": "owasp_board_candidate_claim_evidence",
            },
        ),
        migrations.AddIndex(
            model_name="boardcandidateclaim",
            index=models.Index(
                fields=["candidate", "status"], name="owasp_claim_candidate_status"
            ),
        ),
        migrations.AddIndex(
            model_name="boardcandidateclaim",
            index=models.Index(fields=["board", "status"], name="owasp_claim_board_status"),
        ),
        migrations.AddIndex(
            model_name="boardcandidateclaimevidence",
            index=models.Index(fields=["claim", "is_removed"], name="owasp_evidence_claim_active"),
        ),
    ]
