# Generated by Django 6.0.1 on 2026-01-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0041_milestone_github_milestone_created_at_and_more'),
        ('owasp', '0072_project_project_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pull_requests',
            field=models.ManyToManyField(blank=True, related_name='projects', to='github.pullrequest', verbose_name='Pull Requests'),
        ),
    ]
