# Generated by Django 6.0.1 on 2026-01-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0072_project_project_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_level_non_compliant',
            field=models.BooleanField(default=False, help_text='Indicates if the project level does not match the official OWASP level', verbose_name='Is level non-compliant'),
        ),
        migrations.AddField(
            model_name='projecthealthmetrics',
            name='is_level_non_compliant',
            field=models.BooleanField(default=False, help_text='Indicates if the project level does not match the official OWASP level', verbose_name='Is level non-compliant'),
        ),
    ]
