# Generated by Django 6.0 on 2026-01-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0072_project_project_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='contributions_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Contributions count'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='has_public_member_page',
            field=models.BooleanField(default=True, help_text="Whether the member's profile is publicly visible on the OWASP website", verbose_name='Has Public Member Page'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='is_owasp_staff',
            field=models.BooleanField(default=False, help_text='Indicates if the user is OWASP Foundation staff.', verbose_name='Is OWASP Staff'),
        ),
    ]
