# Generated by Django 6.0.1 on 2026-01-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0043_alter_user_contribution_data'),
        ('owasp', '0072_project_project_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='releases',
            field=models.ManyToManyField(blank=True, related_name='Projects', to='github.release', verbose_name='Releases'),
        ),
    ]
