# Generated by Django 6.0.3 on 2026-03-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0072_project_project_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created At'),
        ),
    ]
