# Generated by Django 6.0 on 2026-01-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0041_milestone_github_milestone_created_at_and_more'),
        ('owasp', '0072_project_project_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='recent_milestones',
            field=models.ManyToManyField(blank=True, to='github.milestone', verbose_name='Recent milestones'),
        ),
    ]
