# Generated by Django 6.0.3 on 2026-06-04 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0073_add_snapshot_frequency_events_posts_pull_requests"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snapshot",
            old_name="new_chapters",
            new_name="chapters",
        ),
        migrations.RenameField(
            model_name="snapshot",
            old_name="new_events",
            new_name="events",
        ),
        migrations.RenameField(
            model_name="snapshot",
            old_name="new_issues",
            new_name="issues",
        ),
        migrations.RenameField(
            model_name="snapshot",
            old_name="new_posts",
            new_name="posts",
        ),
        migrations.RenameField(
            model_name="snapshot",
            old_name="new_projects",
            new_name="projects",
        ),
        migrations.RenameField(
            model_name="snapshot",
            old_name="new_pull_requests",
            new_name="pull_requests",
        ),
        migrations.RenameField(
            model_name="snapshot",
            old_name="new_releases",
            new_name="releases",
        ),
        migrations.RenameField(
            model_name="snapshot",
            old_name="new_users",
            new_name="users",
        ),
    ]
