# Generated by Django 6.0.3 on 2026-03-13 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0073_sponsor_contact_email_sponsor_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owasp.chapter'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owasp.project'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Archived', 'Archived')], default='Draft', max_length=20),
        ),
    ]
