# Generated by Django 6.0 on 2026-01-25 12:00

from django.db import migrations


def copy_user_data_to_member_profile(apps, _schema_editor):
    """Copy user data to member profile."""
    User = apps.get_model("github", "User")
    MemberProfile = apps.get_model("owasp", "MemberProfile")
    profiles_to_update = []
    batch_size = 500
    update_fields = [
        "has_public_member_page",
        "is_owasp_staff",
        "contributions_count",
    ]

    for user in User.objects.all().iterator(chunk_size=batch_size):
        profile, _ = MemberProfile.objects.get_or_create(github_user=user)
        profile.has_public_member_page = user.has_public_member_page
        profile.is_owasp_staff = user.is_owasp_staff
        profile.contributions_count = user.contributions_count
        profiles_to_update.append(profile)

        if len(profiles_to_update) >= batch_size:
            MemberProfile.objects.bulk_update(
                profiles_to_update, update_fields, batch_size=batch_size
            )
            profiles_to_update = []

    if profiles_to_update:
        MemberProfile.objects.bulk_update(profiles_to_update, update_fields, batch_size=batch_size)


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0073_memberprofile_contributions_count_and_more"),
        ("github", "0039_remove_commit_commit_repo_created_idx"),
    ]

    operations = [
        migrations.RunPython(copy_user_data_to_member_profile, migrations.RunPython.noop),
    ]
