# Generated by Django 6.0.5 on 2026-06-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0073_boardcandidateclaim_boardcandidateclaimevidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardcandidateclaim",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Display order of the claim within the candidate profile.",
                verbose_name="Order",
            ),
        ),
    ]
