# Generated by Django 5.2 on 2026-04-08 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0073_sponsor_status_contact_email_chapter_project"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE public.owasp_sponsors
            SET status = 'active'
            WHERE status IS NULL;

            ALTER TABLE public.owasp_sponsors
            ALTER COLUMN status SET DEFAULT 'active';

            ALTER TABLE public.owasp_sponsors
            ALTER COLUMN status SET NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
