# Generated by Django 6.0.1 on 2026-02-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0073_notification_subscription'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='owasp_subsc_user_id_33ae6d_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
