# Generated by Django 6.0.3 on 2026-06-12 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0073_scoringweight_certificate_contributionscore_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="certificate",
            table="owasp_crp_recognition_certificates",
        ),
        migrations.AlterModelTable(
            name="contributionscore",
            table="owasp_crp_recognition_contribution_scores",
        ),
        migrations.AlterModelTable(
            name="leaderboardsnapshot",
            table="owasp_crp_recognition_leaderboard_snapshots",
        ),
        migrations.AlterModelTable(
            name="scoringweight",
            table="owasp_crp_recognition_scoring_weights",
        ),
    ]
