# Generated by Django 6.0.3 on 2026-03-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp', '0074_sponsor_chapter_sponsor_project_sponsor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
    ]
