# Generated by Django 6.0.5 on 2026-06-03 11:00

import django.core.validators
from django.db import migrations, models

import apps.owasp.validators


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0074_boardcandidateclaim_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardcandidateclaimevidence",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="bod/claim/evidence/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "csv",
                            "doc",
                            "docx",
                            "jpeg",
                            "jpg",
                            "pdf",
                            "png",
                            "webp",
                            "xls",
                            "xlsx",
                        ]
                    ),
                    apps.owasp.validators.validate_evidence_file_size,
                    apps.owasp.validators.validate_evidence_content_type,
                ],
                verbose_name="File",
            ),
        ),
    ]
