# Generated by Django 6.0.6 on 2026-06-16 14:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0074_rename_snapshot_m2m_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SnapshotSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "unsubscribe_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("include_chapters", models.BooleanField(default=True)),
                ("include_events", models.BooleanField(default=True)),
                ("include_issues", models.BooleanField(default=True)),
                ("include_posts", models.BooleanField(default=True)),
                ("include_projects", models.BooleanField(default=True)),
                ("include_pull_requests", models.BooleanField(default=True)),
                ("include_releases", models.BooleanField(default=True)),
                ("include_users", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot_subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Snapshot Subscriptions",
                "db_table": "owasp_snapshot_subscriptions",
                "indexes": [
                    models.Index(fields=["is_active"], name="owasp_sub_active_idx"),
                ],
            },
        ),
    ]
