# Generated by Django 5.2 on 2026-04-08 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0074_backfill_sponsor_status_not_null"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE public.owasp_sponsors
            SET contact_email = ''
            WHERE contact_email IS NULL;

            ALTER TABLE public.owasp_sponsors
            ALTER COLUMN contact_email SET DEFAULT '';

            ALTER TABLE public.owasp_sponsors
            ALTER COLUMN contact_email SET NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
