# Generated by Django 6.0.6 on 2026-07-21 02:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0075_snapshotsubscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snapshotsubscription",
            name="subscribed_chapters",
        ),
        migrations.RemoveField(
            model_name="snapshotsubscription",
            name="subscribed_projects",
        ),
        migrations.CreateModel(
            name="EntitySubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "unsubscribe_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entity Subscriptions",
                "db_table": "owasp_entity_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="EntitySubscriptionPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("include_issues", models.BooleanField(default=True)),
                ("include_pull_requests", models.BooleanField(default=True)),
                ("include_releases", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_subscription_preferences",
                        to="owasp.chapter",
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_subscription_preferences",
                        to="owasp.committee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_subscription_preferences",
                        to="owasp.project",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_preferences",
                        to="owasp.entitysubscription",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entity Subscription Preferences",
                "db_table": "owasp_entity_subscription_preferences",
            },
        ),
        migrations.AddIndex(
            model_name="entitysubscription",
            index=models.Index(fields=["is_active"], name="owasp_entity_sub_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="entitysubscriptionpreference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("chapter__isnull", True),
                        ("committee__isnull", True),
                        ("project__isnull", False),
                    ),
                    models.Q(
                        ("chapter__isnull", False),
                        ("committee__isnull", True),
                        ("project__isnull", True),
                    ),
                    models.Q(
                        ("chapter__isnull", True),
                        ("committee__isnull", False),
                        ("project__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="exactly_one_entity_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitysubscriptionpreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", False)),
                fields=("subscription", "project"),
                name="unique_subscription_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitysubscriptionpreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("chapter__isnull", False)),
                fields=("subscription", "chapter"),
                name="unique_subscription_chapter",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitysubscriptionpreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("committee__isnull", False)),
                fields=("subscription", "committee"),
                name="unique_subscription_committee",
            ),
        ),
    ]
