# Generated by Django 6.0.5 on 2026-06-11 07:23

from django.db import migrations, models


def _copy_title_to_name(apps, _schema_editor):
    claim = apps.get_model("owasp", "BoardCandidateClaim")
    for row in claim.objects.all():
        row.name = row.title[:200]  # max_length
        row.save(update_fields=["name"])
    evidence = apps.get_model("owasp", "BoardCandidateClaimEvidence")
    for row in evidence.objects.all():
        row.name = row.title[:200]
        row.save(update_fields=["name"])


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0075_alter_boardcandidateclaimevidence_file"),
    ]

    operations = [
        # Add nullable name field
        migrations.AddField(
            model_name="boardcandidateclaim",
            name="name",
            field=models.CharField(max_length=200, null=True, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="boardcandidateclaimevidence",
            name="name",
            field=models.CharField(max_length=200, null=True, verbose_name="Name"),
            preserve_default=False,
        ),
        # Copy title to name
        migrations.RunPython(_copy_title_to_name, migrations.RunPython.noop),
        # Alter name to to be non-nullable and unique
        migrations.AlterField(
            model_name="boardcandidateclaim",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="boardcandidateclaimevidence",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Name"),
        ),
        # Remove title
        migrations.RemoveField(
            model_name="boardcandidateclaim",
            name="title",
        ),
        migrations.RemoveField(
            model_name="boardcandidateclaimevidence",
            name="title",
        ),
    ]
