# Generated by Django 6.0.6 on 2026-07-02 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0075_snapshotsubscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snapshotsubscription",
            name="include_issues",
        ),
        migrations.RemoveField(
            model_name="snapshotsubscription",
            name="include_projects",
        ),
        migrations.RemoveField(
            model_name="snapshotsubscription",
            name="include_pull_requests",
        ),
        migrations.RemoveField(
            model_name="snapshotsubscription",
            name="include_releases",
        ),
        migrations.RemoveField(
            model_name="snapshotsubscription",
            name="subscribed_projects",
        ),
        migrations.RenameField(
            model_name="snapshotsubscription",
            old_name="subscribed_chapters",
            new_name="chapters",
        ),
        migrations.CreateModel(
            name="ProjectSubscriptionPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("include_issues", models.BooleanField(default=True)),
                ("include_pull_requests", models.BooleanField(default=True)),
                ("include_releases", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_preferences",
                        to="owasp.project",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_preferences",
                        to="owasp.snapshotsubscription",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project Subscription Preferences",
                "db_table": "owasp_project_subscription_preferences",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subscription", "project"), name="unique_subscription_project"
                    )
                ],
            },
        ),
    ]
