# Generated by Django 6.0.5 on 2026-06-11 07:23

from django.db import migrations, models
from django.utils.text import slugify


def _backfill_key(apps, _schema_editor):
    claim = apps.get_model("owasp", "BoardCandidateClaim")
    for row in claim.objects.all():
        row.key = slugify(row.name)[:100]
        row.save(update_fields=["key"])
    evidence = apps.get_model("owasp", "BoardCandidateClaimEvidence")
    for row in evidence.objects.all():
        row.key = slugify(row.name)[:100]
        row.save(update_fields=["key"])


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0076_remove_boardcandidateclaim_title_and_more"),
    ]

    operations = [
        # Add nullable key field
        migrations.AddField(
            model_name="boardcandidateclaim",
            name="key",
            field=models.CharField(max_length=100, null=True, verbose_name="Key"),
        ),
        migrations.AddField(
            model_name="boardcandidateclaimevidence",
            name="key",
            field=models.CharField(max_length=100, null=True, verbose_name="Key"),
        ),
        # Backfill key from name
        migrations.RunPython(_backfill_key, migrations.RunPython.noop),
        # Alter key to be non-nullable and unique
        migrations.AlterField(
            model_name="boardcandidateclaim",
            name="key",
            field=models.CharField(max_length=100, unique=True, verbose_name="Key"),
        ),
        migrations.AlterField(
            model_name="boardcandidateclaimevidence",
            name="key",
            field=models.CharField(max_length=100, unique=True, verbose_name="Key"),
        ),
    ]
