# Generated by Django 6.0.5 on 2026-06-27 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0079_alter_boardcandidateclaimevidence_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardofdirectors",
            name="reviews_threshold",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Minimum number of reviews required to finalize a claim.",
                verbose_name="Reviews Threshold",
            ),
        ),
        migrations.CreateModel(
            name="BoardCandidateClaimReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        max_length=8,
                        verbose_name="Review Decision",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="owasp.boardcandidateclaim",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="owasp.entitymember",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Board Candidate Claim Reviews",
                "db_table": "owasp_board_candidate_claim_review",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("claim", "reviewer"), name="owasp_claim_reviewer_unique"
                    )
                ],
            },
        ),
    ]
