# Generated by Django 6.0.5 on 2026-06-30 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0079_alter_boardcandidateclaimevidence_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardCandidateClaimReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "status",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        max_length=8,
                        verbose_name="Review Status",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Board Candidate Claim Reviews",
                "db_table": "owasp_board_candidate_claim_reviews",
            },
        ),
        migrations.AddField(
            model_name="boardofdirectors",
            name="reviewers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Reviewers for this year's board election claims.",
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewers",
            ),
        ),
        migrations.AddField(
            model_name="boardofdirectors",
            name="reviews_threshold",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Minimum number of reviews required to finalize a claim.",
                verbose_name="Reviews Threshold",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardofdirectors",
            constraint=models.CheckConstraint(
                condition=models.Q(("reviews_threshold__gte", 1)), name="reviews_threshold_min_1"
            ),
        ),
        migrations.AddField(
            model_name="boardcandidateclaimreview",
            name="claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="owasp.boardcandidateclaim",
            ),
        ),
        migrations.AddField(
            model_name="boardcandidateclaimreview",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="boardcandidateclaimreview",
            constraint=models.UniqueConstraint(
                fields=("claim", "reviewer"), name="owasp_claim_reviewer_unique"
            ),
        ),
    ]
