ignored:
  - DL3018  # Pinned FROM image guarantees a fixed Alpine package set; per-package version pins are redundant.
  - DL3042  # RUN --mount=type=cache keeps pip cache out of image layers; --no-cache-dir would defeat it.
