copyright: Copyright &copy; 2026 OWASP Nest

docs_dir: docs/src

extra:
  generator: false
  homepage: .
  social:
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/nest.owasp.org
      name: OWASP Nest on Bluesky
    - icon: fontawesome/brands/github
      link: https://github.com/OWASP/Nest
      name: OWASP Nest on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/owasp-nest
      name: OWASP Nest on LinkedIn
    - icon: fontawesome/brands/slack
      link: https://owasp.slack.com/archives/project-nest
      name: OWASP Nest on Slack

extra_css:
  - assets/stylesheets/nest-theme.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      base_path: [.]
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: '!!python/name:pymdownx.superfences.fence_code_format'
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - toc:
      permalink: true

nav:
  - Home:
      - OWASP Nest: index.md
      - Code of Conduct: code-of-conduct.md
      - Contributing: contributing.md
  - API: api/index.md
  - Backend: backend/index.md
  - Frontend: frontend/index.md
  - NestBot: nestbot/index.md
  - Schema: schema/index.md
  - Maintenance: maintenance/index.md

plugins:
  - minify:
      minify_html: true
  - mkdocstrings:
      default_handler: python
  - privacy
  - search
  - tags

repo_url: https://github.com/OWASP/Nest

site_name: OWASP Nest

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  font:
    code: Geist Mono
    text: Geist
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
  language: en
  palette:
    - scheme: dark
      toggle:
        icon: material/weather-sunny
        name: Enable light mode
      primary: teal
      accent: cyan
    - scheme: light
      toggle:
        icon: material/weather-night
        name: Enable dark mode
      primary: teal
      accent: amber
