version: 2

build:
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
      - cd docs && poetry export --format=requirements.txt --output=requirements.txt
      - python docs/scripts/generate_schema_docs.py
  os: ubuntu-24.04
  tools:
    python: '3.13'

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - method: pip
      path: docs
