exit-code: 1

filesystem:
  skip-files:

ignorefile: /.trivyignore.yaml

report: all

scan:
  scanners:
    - misconfig
    - secret
    - vuln
  show-suppressed: true
  skip-dirs:
    - '**/__pycache__'
    - '**/.cache'
    - '**/.lighthouseci'
    - '**/.local'
    - '**/.mypy_cache'
    - '**/.next'
    - '**/.pnpm-store'
    - '**/.pytest_cache'
    - '**/.ruff_cache'
    - '**/.semgrep-cache'
    - '**/.terraform'
    - '**/.trivy-cache'
    - '**/.venv'
    - '**/coverage'
    - '**/node_modules'
    - '**/staticfiles'
  skip-files:
    - '**/.env'
    - '**/*.pem'

severity:
  - CRITICAL
  - HIGH
  - UNKNOWN

timeout: 10m

vulnerability:
  ignore-unfixed: true
