ignoreScripts: true

# 21 days (in minutes)
minimumReleaseAge: 30240

minimumReleaseAgeExclude:
  - brace-expansion@1.1.16
  - brace-expansion@5.0.7
  - immutable@5.1.8

overrides:
  brace-expansion@1: 1.1.16
  brace-expansion@5: 5.0.7
  immutable@5: 5.1.8

saveExact: true

strictDepBuilds: true
