FROM node:24.16-alpine3.23

ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0 \
    FORCE_COLOR=1 \
    PNPM_CONFIG_CACHE="/app/.npm" \
    PNPM_HOME="/pnpm"

ENV PNPM_CONFIG_FETCH_RETRIES=5 \
    PNPM_CONFIG_FETCH_TIMEOUT=30000 \
    PATH="$PNPM_HOME:$PATH"

WORKDIR /app

COPY --chmod=444 --chown=root:root package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    corepack install && corepack enable pnpm && \
    pnpm install --frozen-lockfile --ignore-scripts && \
    chown node:node /app

COPY __tests__/a11y __tests__/a11y
COPY __tests__/mockData __tests__/mockData
COPY __tests__/jest.setup.ts __tests__/jest.setup.ts
COPY .pnpmrc jest.config.ts tsconfig.json ./
COPY public public
COPY src src

USER node
