FROM mcr.microsoft.com/playwright:v1.58.1-jammy

ENV FORCE_COLOR=1 \
    NPM_CACHE="/app/.npm" \
    PNPM_HOME="/pnpm"

ENV NPM_CONFIG_RETRY=5 \
    NPM_CONFIG_TIMEOUT=30000 \
    PATH="$PNPM_HOME:$PATH"

RUN --mount=type=cache,target=${NPM_CACHE} \
    npm install --ignore-scripts -g pnpm --cache ${NPM_CACHE}

WORKDIR /app

RUN pnpm add @playwright/test millify dayjs

COPY .pnpmrc next.config.ts postcss.config.js playwright.config.ts tailwind.config.mjs tsconfig.json ./
COPY src/utils src/utils
COPY __tests__/e2e __tests__/e2e
COPY __tests__/mockData __tests__/mockData

EXPOSE 3800
