FROM node:24.18-alpine3.23@sha256:595398b0081eacda8e1c4c5b97b76cd1020e4d58a8ebcb4843b9bca1e79e7436

ENV CHROME_PATH=/usr/bin/chromium-browser \
    COREPACK_ENABLE_DOWNLOAD_PROMPT=0 \
    FORCE_COLOR=1 \
    NPM_CONFIG_CACHE="/app/.npm" \
    PNPM_HOME="/pnpm"

ENV PATH="$PNPM_HOME:$PATH" \
    PNPM_CONFIG_FETCH_RETRIES=5 \
    PNPM_CONFIG_FETCH_TIMEOUT=30000

RUN --mount=type=cache,target=/var/cache/apk \
    apk --no-cache update && \
    apk --no-cache upgrade && \
    apk --no-cache add chromium nss freetype harfbuzz ttf-freefont

WORKDIR /app

COPY --chmod=444 --chown=root:root package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    corepack install && corepack enable pnpm && \
    pnpm install --frozen-lockfile && \
    chown node:node /app

COPY --chmod=444 --chown=root:root lighthouserc.js ./

USER node
