FROM node:24.17-alpine3.23@sha256:7c078d435026a97c8ff97b00d70e2f6ec6298a440e25a9485a9af414d5d37009

ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0 \
    FORCE_COLOR=1 \
    NPM_CONFIG_CACHE="/app/.npm" \
    PNPM_HOME="/pnpm"

ENV PATH="$PNPM_HOME:$PATH" \
    PNPM_CONFIG_FETCH_RETRIES=5 \
    PNPM_CONFIG_FETCH_TIMEOUT=30000

WORKDIR /app

COPY --chmod=444 --chown=root:root package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    corepack install && corepack enable pnpm && \
    pnpm install --frozen-lockfile && \
    chown node:node /app

COPY __tests__/unit __tests__/unit
COPY __tests__/mockData __tests__/mockData
COPY __tests__/jest.setup.ts __tests__/jest.setup.ts
COPY __tests__/tsconfig.json __tests__/tsconfig.json
COPY jest.config.ts tsconfig.json ./
COPY public public
COPY src src

USER node
