FROM node:24-alpine

ENV FORCE_COLOR=1 \
    NPM_CACHE="/app/.npm" \
    PNPM_HOME="/pnpm"

ENV NPM_CONFIG_RETRY=5 \
    NPM_CONFIG_TIMEOUT=30000 \
    PATH="$PNPM_HOME:$PATH"

RUN --mount=type=cache,target=${NPM_CACHE} \
    npm install --ignore-scripts -g pnpm --cache ${NPM_CACHE}

WORKDIR /app

COPY --chmod=444 --chown=root:root package.json pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile --ignore-scripts && \
    chown node:node /app

COPY __tests__/unit __tests__/unit
COPY .pnpmrc jest.config.ts jest.setup.ts tsconfig.json ./
COPY public public
COPY src src

USER node
