ai-create-chapter-chunks:
	@echo "Creating chapter chunks"
	@CMD="python manage.py ai_create_chapter_chunks" $(MAKE) exec-backend-command

ai-create-chapter-context:
	@echo "Creating chapter context"
	@CMD="python manage.py ai_create_chapter_context" $(MAKE) exec-backend-command

ai-create-committee-chunks:
	@echo "Creating committee chunks"
	@CMD="python manage.py ai_create_committee_chunks" $(MAKE) exec-backend-command

ai-create-committee-context:
	@echo "Creating committee context"
	@CMD="python manage.py ai_create_committee_context" $(MAKE) exec-backend-command

ai-create-event-chunks:
	@echo "Creating event chunks"
	@CMD="python manage.py ai_create_event_chunks" $(MAKE) exec-backend-command

ai-create-event-context:
	@echo "Creating event context"
	@CMD="python manage.py ai_create_event_context" $(MAKE) exec-backend-command

ai-create-project-chunks:
	@echo "Creating project chunks"
	@CMD="python manage.py ai_create_project_chunks" $(MAKE) exec-backend-command

ai-create-project-context:
	@echo "Creating project context"
	@CMD="python manage.py ai_create_project_context" $(MAKE) exec-backend-command

ai-create-slack-message-chunks:
	@echo "Creating Slack message chunks"
	@CMD="python manage.py ai_create_slack_message_chunks" $(MAKE) exec-backend-command

ai-create-slack-message-context:
	@echo "Creating Slack message context"
	@CMD="python manage.py ai_create_slack_message_context" $(MAKE) exec-backend-command

ai-run-rag-tool:
	@echo "Running RAG tool"
	@CMD="python manage.py ai_run_rag_tool" $(MAKE) exec-backend-command
