ai-create-chapter-chunks:
	@echo "Creating chapter chunks"
	@CMD="python manage.py ai_create_chapter_chunks" $(MAKE) exec-backend-command

ai-create-event-chunks:
	@echo "Creating event chunks"
	@CMD="python manage.py ai_create_event_chunks" $(MAKE) exec-backend-command

ai-create-project-chunks:
	@echo "Creating project chunks"
	@CMD="python manage.py ai_create_project_chunks" $(MAKE) exec-backend-command

ai-create-slack-message-chunks:
	@echo "Creating Slack message chunks"
	@CMD="python manage.py ai_create_slack_message_chunks" $(MAKE) exec-backend-command
