ai-create-slack-message-chunks:
	@echo "Creating Slack message chunks"
	@CMD="python manage.py ai_create_slack_message_chunks" $(MAKE) exec-backend-command

ai-create-chapter-chunks:
	@echo "Creating chapter chunks"
	@CMD="python manage.py ai_create_chapter_chunks" $(MAKE) exec-backend-command
