# Generated by Django 5.2.5 on 2025-08-28 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0035_alter_user_bio_alter_user_is_owasp_staff"),
        ("nest", "0003_badge"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the badge assignment is active.",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional note of the user badge.",
                        max_length=255,
                        verbose_name="Note",
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="nest.badge",
                        verbose_name="Badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="github.user",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User badges",
                "db_table": "nest_user_badges",
                "unique_together": {("badge", "user")},
            },
        ),
    ]
