# Generated by Django 5.2.6 on 2025-10-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0006_delete_apikey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="css_class",
            field=models.CharField(
                choices=[
                    ("award", "Award"),
                    ("medal", "Medal"),
                    ("ribbon", "Ribbon"),
                    ("star", "Star"),
                    ("certificate", "Certificate"),
                    ("bug_slash", "Bug Slash"),
                ],
                default="medal",
                max_length=255,
                verbose_name="CSS Class",
            ),
        ),
    ]
