FROM python:3.12-slim

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN groupadd owasp && \
    useradd --create-home --home-dir /home/owasp -g owasp owasp && \
    apt-get update && apt-get upgrade -y && \
    apt-get install -y gcc libpq-dev && \
    apt-get clean -y && rm -rf /var/lib/apt/lists/* && \
    python -m pip install --no-cache-dir poetry

ENV PYTHONUNBUFFERED=1

EXPOSE 8000

USER owasp

VOLUME /home/owasp

WORKDIR /home/owasp
