##@ Backend

include backend/make/apps/ai.mk
include backend/make/apps/github.mk
include backend/make/apps/mentorship.mk
include backend/make/apps/nest.mk
include backend/make/apps/owasp.mk
include backend/make/apps/slack.mk
include backend/make/data.mk
include backend/make/django.mk
include backend/make/exec.mk
include backend/make/image.mk
include backend/make/maintenance.mk
include backend/make/security.mk
include backend/make/test.mk
