ARG OWASP_GID=1000
ARG OWASP_UID=1000

FROM python:3.13.14-alpine3.23@sha256:9fdbf2e3e82628351513560b121e2ee6ce31cac212be9e070c5a5e2769fb5e76 AS builder

ARG OWASP_GID
ARG OWASP_UID

SHELL ["/bin/sh", "-o", "pipefail", "-c"]

ENV APK_CACHE_DIR="/home/owasp/.cache/apk-tools-test" \
    APK_SYMLINK_DIR="/etc/apk/cache" \
    OWASP_GID=${OWASP_GID} \
    OWASP_UID=${OWASP_UID} \
    PIP_CACHE_DIR="/home/owasp/.cache/pip" \
    PYTHONUNBUFFERED=1

RUN mkdir -p "${APK_CACHE_DIR}" && \
    ln -fns "${APK_CACHE_DIR}" "${APK_SYMLINK_DIR}"

RUN --mount=type=cache,target="${APK_CACHE_DIR}" \
    apk --no-cache update && \
    apk --no-cache upgrade && \
    addgroup -S -g "${OWASP_GID}" owasp && \
    adduser -S -h /home/owasp -u "${OWASP_UID}" -G owasp owasp && \
    chown -R owasp:owasp /home/owasp

COPY --chmod=444 --chown=root:root tools/requirements/test.txt /tmp/test.txt
RUN --mount=type=cache,target="${PIP_CACHE_DIR}" \
    python -m pip install --require-hashes --requirement /tmp/test.txt && \
    rm -f /tmp/test.txt

FROM python:3.13.14-alpine3.23@sha256:9fdbf2e3e82628351513560b121e2ee6ce31cac212be9e070c5a5e2769fb5e76

ARG OWASP_GID
ARG OWASP_UID

SHELL ["/bin/sh", "-o", "pipefail", "-c"]

RUN addgroup -S -g "${OWASP_GID}" owasp && \
    adduser -S -h /home/owasp -u "${OWASP_UID}" -G owasp owasp && \
    mkdir -p /home/owasp/.cache/pycache /home/owasp/nest && \
    chown -R owasp:owasp /home/owasp

ENV FORCE_COLOR=1 \
    PATH="/usr/local/bin:${PATH}" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONPYCACHEPREFIX=/home/owasp/.cache/pycache \
    PYTHONUNBUFFERED=1

COPY --from=builder /usr/local /usr/local

USER owasp
WORKDIR /home/owasp/nest

COPY --chown=root:root .github/scripts .github/scripts
COPY --chown=root:root tools/tests tools/tests

CMD ["pytest", "tools/tests"]
