ARG OWASP_GID=1000
ARG OWASP_UID=1000

FROM python:3.13.15-alpine3.23@sha256:7ea3f82de8ea6d4fb7e5d2bbe3fe3c9d931700b7a529f1fe5769e42abe514ca1 AS builder

ARG OWASP_GID
ARG OWASP_UID

SHELL ["/bin/sh", "-o", "pipefail", "-c"]

ENV APK_CACHE_DIR="/home/owasp/.cache/apk-tools-test" \
    APK_SYMLINK_DIR="/etc/apk/cache" \
    OWASP_GID=${OWASP_GID} \
    OWASP_UID=${OWASP_UID} \
    PIP_CACHE_DIR="/home/owasp/.cache/pip" \
    PYTHONUNBUFFERED=1

RUN mkdir -p "${APK_CACHE_DIR}" && \
    ln -fns "${APK_CACHE_DIR}" "${APK_SYMLINK_DIR}"

RUN --mount=type=cache,target="${APK_CACHE_DIR}" \
    apk --no-cache update && \
    apk --no-cache upgrade && \
    addgroup -S -g "${OWASP_GID}" owasp && \
    adduser -S -h /home/owasp -u "${OWASP_UID}" -G owasp owasp && \
    chown -R owasp:owasp /home/owasp

COPY --chmod=444 --chown=root:root tools/requirements/test.txt /tmp/test.txt
RUN --mount=type=cache,target="${PIP_CACHE_DIR}" \
    python -m pip install --require-hashes --requirement /tmp/test.txt && \
    rm -f /tmp/test.txt

FROM python:3.13.15-alpine3.23@sha256:7ea3f82de8ea6d4fb7e5d2bbe3fe3c9d931700b7a529f1fe5769e42abe514ca1

ARG OWASP_GID
ARG OWASP_UID

SHELL ["/bin/sh", "-o", "pipefail", "-c"]

RUN addgroup -S -g "${OWASP_GID}" owasp && \
    adduser -S -h /home/owasp -u "${OWASP_UID}" -G owasp owasp && \
    mkdir -p /home/owasp/.cache/pycache /home/owasp/nest && \
    chown -R owasp:owasp /home/owasp

ENV FORCE_COLOR=1 \
    PATH="/usr/local/bin:${PATH}" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONPYCACHEPREFIX=/home/owasp/.cache/pycache \
    PYTHONUNBUFFERED=1

COPY --from=builder /usr/local /usr/local

# hadolint ignore=DL3018
RUN --mount=type=cache,target=/var/cache/apk \
    apk --no-cache add gnupg

USER owasp
WORKDIR /home/owasp/nest

COPY --chown=root:root .github/scripts .github/scripts
COPY --chown=root:root frontend/public/.well-known frontend/public/.well-known
COPY --chown=root:root tools/security tools/security
COPY --chown=root:root tools/tests tools/tests

CMD ["pytest", "tools/tests"]
