ARG OWASP_GID=1000
ARG OWASP_UID=1000

FROM python:3.13.15-alpine3.23@sha256:7ea3f82de8ea6d4fb7e5d2bbe3fe3c9d931700b7a529f1fe5769e42abe514ca1

ARG OWASP_GID
ARG OWASP_UID

SHELL ["/bin/sh", "-o", "pipefail", "-c"]

ENV APK_CACHE_DIR="/home/owasp/.cache/apk-tools-security" \
    APK_SYMLINK_DIR="/etc/apk/cache" \
    OWASP_GID=${OWASP_GID} \
    OWASP_UID=${OWASP_UID} \
    PYTHONUNBUFFERED=1

RUN mkdir -p "${APK_CACHE_DIR}" && \
    ln -fns "${APK_CACHE_DIR}" "${APK_SYMLINK_DIR}"

# hadolint ignore=DL3018
RUN --mount=type=cache,target="${APK_CACHE_DIR}" \
    apk --no-cache update && \
    apk --no-cache upgrade && \
    apk --no-cache add gnupg && \
    addgroup -S -g "${OWASP_GID}" owasp && \
    adduser -S -h /home/owasp -u "${OWASP_UID}" -G owasp owasp && \
    chown -R owasp:owasp /home/owasp

WORKDIR /work

COPY --chown=root:root --chmod=555 tools/security/renew_security_txt.py \
    /usr/local/bin/renew_security_txt.py

USER owasp

ENTRYPOINT ["python", "/usr/local/bin/renew_security_txt.py"]
