# Generated by Django 5.2.6 on 2025-10-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_prompt_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="text",
            field=models.TextField(blank=True, default="", max_length=3000, verbose_name="Text"),
        ),
    ]
