services:
  backend:
    environment:
      - DJANGO_OTEL_METRICS_ENABLED=true
      - OTEL_SERVICE_NAME=nest-backend
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://o11y-metrics:8428/opentelemetry
      - OTEL_METRIC_EXPORT_INTERVAL=15000

  frontend:
    environment:
      - OTEL_SERVICE_NAME=nest-frontend
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://o11y-metrics:8428/opentelemetry
      - OTEL_METRIC_EXPORT_INTERVAL=15000

  o11y-metrics:
    container_name: nest-o11y-metrics
    command:
      - -retentionPeriod=7d
      - -storageDataPath=/data
    image: victoriametrics/victoria-metrics:v1.145.0@sha256:c014fb5a711d38cb24fd0673197592cd1394bb903dbb16aea565620c9c8a3d70
    healthcheck:
      interval: 5s
      retries: 5
      test: [CMD, wget, --spider, -q, http://127.0.0.1:8428/health]
      timeout: 5s
    networks:
      - nest-network
    ports:
      - 8428:8428
    volumes:
      - o11y-metrics-data:/data

volumes:
  o11y-metrics-data:
