# Generated by Django 5.1.1 on 2024-09-12 19:39
#!/usr/bin/env python3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="summary",
            field=models.TextField(default="", max_length=3000, verbose_name="Summary"),
        ),
    ]
