# Generated by Django 5.1 on 2024-08-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="repository",
            name="unique_key_platform_owner",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="platform",
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                fields=("key", "owner_login"), name="unique_key_owner"
            ),
        ),
        migrations.AlterModelTable(
            name="repository",
            table="github_repositories",
        ),
    ]
