# Generated by Django 5.1 on 2024-08-20 18:55

from django.db import migrations, models

import apps.github.models.common


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0002_remove_repository_unique_key_platform_owner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(default="", max_length=1000, verbose_name="Description"),
                ),
                ("is_verified", models.BooleanField(default=False, verbose_name="Is verified")),
            ],
            options={
                "verbose_name_plural": "Organizations",
                "db_table": "github_organizations",
            },
            bases=(apps.github.models.common.GenericUserModel, models.Model),
        ),
    ]
