# Generated by Django 5.1.1 on 2024-09-14 03:01
#!/usr/bin/env python3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0003_issue_hint_alter_issue_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="hint",
            field=models.TextField(default="", verbose_name="Hint"),
        ),
    ]
