# Generated by Django 5.1 on 2024-08-20 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0003_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="github.organization",
                verbose_name="Organization",
            ),
        ),
    ]
