# Generated by Django 5.1.1 on 2024-09-14 03:04
#!/usr/bin/env python3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0004_alter_issue_hint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="hint",
            field=models.TextField(blank=True, default="", verbose_name="Hint"),
        ),
        migrations.AlterField(
            model_name="issue",
            name="lock_reason",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Lock reason"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="summary",
            field=models.TextField(blank=True, default="", verbose_name="Summary"),
        ),
    ]
