# Generated by Django 5.1.1 on 2024-09-14 03:07
#!/usr/bin/env python3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0005_alter_issue_hint_alter_issue_lock_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="state_reason",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="State reason"
            ),
        ),
    ]
