# Generated by Django 5.1 on 2024-08-20 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0005_organization_avatar_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="twitter_username",
        ),
    ]
