# Generated by Django 5.1 on 2024-08-20 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0006_remove_organization_twitter_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("login", models.CharField(max_length=100, unique=True, verbose_name="Key")),
                ("email", models.EmailField(default="", max_length=100, verbose_name="Email")),
                ("avatar_url", models.URLField(default="", verbose_name="Avatar URL")),
                ("company", models.CharField(default="", max_length=200, verbose_name="Company")),
                (
                    "location",
                    models.CharField(default="", max_length=200, verbose_name="Location"),
                ),
                (
                    "collaborators_count",
                    models.PositiveIntegerField(default=0, verbose_name="Collaborators count"),
                ),
                (
                    "following_count",
                    models.PositiveIntegerField(default=0, verbose_name="Following count"),
                ),
                (
                    "followers_count",
                    models.PositiveIntegerField(default=0, verbose_name="Followers count"),
                ),
                (
                    "public_gists_count",
                    models.PositiveIntegerField(default=0, verbose_name="Public gists count"),
                ),
                (
                    "public_repositories_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Public repositories count"
                    ),
                ),
                ("original_created_at", models.DateTimeField(verbose_name="Original created_at")),
                ("original_updated_at", models.DateTimeField(verbose_name="Original updated_at")),
                ("bio", models.TextField(default="", max_length=1000, verbose_name="Bio")),
                ("is_hireable", models.BooleanField(default=False, verbose_name="Is hireable")),
                (
                    "twitter_username",
                    models.CharField(default="", max_length=50, verbose_name="Twitter username"),
                ),
            ],
            options={
                "verbose_name_plural": "Users",
                "db_table": "github_users",
            },
        ),
        migrations.AddField(
            model_name="repository",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="github.user",
                verbose_name="Owner",
            ),
        ),
    ]
