# Generated by Django 5.1.1 on 2024-09-21 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0006_alter_issue_state_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryContributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("node_id", models.CharField(unique=True, verbose_name="Node ID")),
                (
                    "contributions_count",
                    models.PositiveIntegerField(default=0, verbose_name="Contributions"),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="github.repository",
                        verbose_name="Repository",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="github.user",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contributors",
                "db_table": "github_repository_contributors",
            },
        ),
    ]
