# Generated by Django 5.1.1 on 2024-09-21 19:09
#!/usr/bin/env python3
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0007_repositorycontributor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repositorycontributor",
            options={"verbose_name_plural": "Repository contributors"},
        ),
    ]
