# Generated by Django 5.1 on 2024-08-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0008_remove_organization_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="watchers_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Watchers count"),
        ),
    ]
