# Generated by Django 5.1 on 2024-08-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0009_repository_watchers_count"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="repository",
            name="unique_key_owner",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="owner_login",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="owner_type",
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(fields=("key", "owner"), name="unique_key_owner"),
        ),
    ]
