# Generated by Django 5.1 on 2024-08-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0010_remove_repository_unique_key_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="languages",
            field=models.JSONField(default=dict, verbose_name="Languages"),
        ),
    ]
