# Generated by Django 5.1 on 2024-08-20 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0011_repository_languages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="language",
        ),
    ]
