# Generated by Django 5.1.2 on 2024-10-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0012_alter_repository_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="title",
            field=models.CharField(max_length=1000, verbose_name="Title"),
        ),
    ]
