# Generated by Django 5.1 on 2024-08-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0013_release"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="node_id",
            field=models.CharField(default="", unique=True, verbose_name="Node ID"),
            preserve_default=False,
        ),
    ]
