# Generated by Django 5.1.2 on 2024-11-03 18:36
#!/usr/bin/env python3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0013_alter_issue_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="track_issues",
            field=models.BooleanField(default=True, verbose_name="Track issues"),
        ),
    ]
