# Generated by Django 5.1.4 on 2024-12-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0014_repository_track_issues"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_hireable",
        ),
        migrations.RemoveField(
            model_name="user",
            name="twitter_username",
        ),
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                default="User",
                help_text="Distinguishes between User and Organization accounts",
                max_length=50,
                verbose_name="User type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                default="",
                help_text="User's GitHub biography",
                max_length=1000,
                verbose_name="Bio",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="public_repositories_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of public repositories",
                verbose_name="Public repositories count",
            ),
        ),
    ]
