# Generated by Django 5.1 on 2024-08-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0014_release_node_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="description",
            field=models.TextField(default="", verbose_name="Description"),
        ),
    ]
