# Generated by Django 5.1 on 2024-08-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0015_alter_release_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="node_id",
            field=models.CharField(default="", unique=True, verbose_name="Node ID"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repository",
            name="node_id",
            field=models.CharField(default="", unique=True, verbose_name="Node ID"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="node_id",
            field=models.CharField(default="", unique=True, verbose_name="Node ID"),
            preserve_default=False,
        ),
    ]
