# Generated by Django 5.1.6 on 2025-02-15 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0016_pullrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pullrequest",
            name="comments_count",
        ),
    ]
