# Generated by Django 5.1 on 2024-08-21 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0016_organization_node_id_repository_node_id_user_node_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="created_at",
            new_name="nest_created_at",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="updated_at",
            new_name="nest_updated_at",
        ),
        migrations.RenameField(
            model_name="release",
            old_name="created_at",
            new_name="nest_created_at",
        ),
        migrations.RenameField(
            model_name="release",
            old_name="updated_at",
            new_name="nest_updated_at",
        ),
        migrations.RenameField(
            model_name="repository",
            old_name="created_at",
            new_name="nest_created_at",
        ),
        migrations.RenameField(
            model_name="repository",
            old_name="updated_at",
            new_name="nest_updated_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="created_at",
            new_name="nest_created_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="updated_at",
            new_name="nest_updated_at",
        ),
    ]
