# Generated by Django 5.1 on 2024-08-21 21:08

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0017_rename_created_at_organization_nest_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="original_created_at",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="original_updated_at",
        ),
        migrations.RemoveField(
            model_name="release",
            name="original_created_at",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="original_created_at",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="original_updated_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="original_created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="original_updated_at",
        ),
        migrations.AddField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 21, 21, 8, 41, 7158, tzinfo=datetime.UTC),
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 21, 21, 8, 47, 175920, tzinfo=datetime.UTC),
                verbose_name="Updated at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="release",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 21, 21, 8, 50, 317037, tzinfo=datetime.UTC),
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repository",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 21, 21, 8, 52, 866162, tzinfo=datetime.UTC),
                verbose_name="Created_at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repository",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 21, 21, 8, 54, 572273, tzinfo=datetime.UTC),
                verbose_name="Updated_at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 21, 21, 8, 55, 980536, tzinfo=datetime.UTC),
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 21, 21, 8, 57, 168111, tzinfo=datetime.UTC),
                verbose_name="Updated at",
            ),
            preserve_default=False,
        ),
    ]
