# Generated by Django 5.1.7 on 2025-03-17 02:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0017_alter_issue_managers_alter_issue_sequence_id_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="issue",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="pullrequest",
            managers=[],
        ),
    ]
