# Generated by Django 5.1.7 on 2025-03-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0018_alter_issue_managers_alter_pullrequest_managers"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["-created_at"], name="github_issu_created_4afbcc_idx"),
        ),
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(fields=["-created_at"], name="github_pull_created_190b3c_idx"),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(fields=["-created_at"], name="github_rele_created_d51966_idx"),
        ),
    ]
