# Generated by Django 5.1 on 2024-08-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0018_remove_organization_original_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="has_funding_yml",
            field=models.BooleanField(default=False, verbose_name="Has FUNDING.yml"),
        ),
    ]
