# Generated by Django 5.1.7 on 2025-03-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0019_issue_github_issu_created_4afbcc_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contributions_count",
            field=models.IntegerField(default=0, verbose_name="Contributions count"),
        ),
    ]
