# Generated by Django 5.1 on 2024-08-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0019_repository_has_funding_yml"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="funding_yml",
            field=models.JSONField(default=dict, verbose_name="FUNDING.yml data"),
        ),
    ]
