# Generated by Django 5.2 on 2025-04-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0020_repositorycontributor_user_contrib_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="has_pull_request",
            field=models.BooleanField(default=False),
        ),
    ]
