# Generated by Django 5.1 on 2024-08-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0020_repository_funding_yml"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="is_funding_policy_compliant",
            field=models.BooleanField(default=True, verbose_name="Is funding policy compliant"),
        ),
        migrations.AddField(
            model_name="repository",
            name="is_owasp_site_repository",
            field=models.BooleanField(default=False, verbose_name="Is OWASP site repository"),
        ),
    ]
