# Generated by Django 5.1 on 2024-08-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0021_repository_is_funding_policy_compliant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="login",
            field=models.CharField(max_length=100, unique=True, verbose_name="Login"),
        ),
        migrations.AlterField(
            model_name="user",
            name="login",
            field=models.CharField(max_length=100, unique=True, verbose_name="Login"),
        ),
    ]
