# Generated by Django 5.1 on 2024-08-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0022_alter_organization_login_alter_user_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="is_empty",
            field=models.BooleanField(default=False, verbose_name="Is empty"),
        ),
    ]
