# Generated by Django 5.2 on 2025-04-21 14:45

import django.db.models.deletion
from django.db import migrations, models

import apps.github.models.mixins.issue


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0023_alter_user_contributions_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("node_id", models.CharField(unique=True, verbose_name="Node ID")),
                ("title", models.CharField(max_length=1000, verbose_name="Title")),
                ("body", models.TextField(default="", verbose_name="Body")),
                (
                    "state",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=6,
                        verbose_name="State",
                    ),
                ),
                ("url", models.URLField(default="", max_length=500, verbose_name="URL")),
                ("number", models.PositiveBigIntegerField(default=0, verbose_name="Number")),
                ("sequence_id", models.PositiveBigIntegerField(default=0, verbose_name="ID")),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Closed at"),
                ),
                ("created_at", models.DateTimeField(verbose_name="Created at")),
                ("updated_at", models.DateTimeField(db_index=True, verbose_name="Updated at")),
                ("open_issues_count", models.PositiveIntegerField(default=0)),
                ("closed_issues_count", models.PositiveIntegerField(default=0)),
                ("due_on", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="github.user",
                    ),
                ),
                (
                    "labels",
                    models.ManyToManyField(
                        blank=True, related_name="milestones", to="github.label"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="github.repository",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Milestones",
                "db_table": "github_milestone",
                "ordering": ["-updated_at", "-state"],
            },
            bases=(apps.github.models.mixins.issue.IssueIndexMixin, models.Model),
        ),
    ]
