# Generated by Django 5.1 on 2024-08-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0023_repository_is_empty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
    ]
