# Generated by Django 5.2 on 2025-05-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0024_alter_organization_email_alter_organization_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_owasp_organization",
            field=models.BooleanField(default=True, verbose_name="Is OWASP organization"),
        ),
    ]
