# Generated by Django 5.2 on 2025-04-24 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0024_alter_organization_email_alter_organization_location_and_more"),
        ("github", "0024_milestone"),
    ]

    operations = []
