# Generated by Django 5.1 on 2024-08-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0024_alter_release_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="created_at",
            field=models.DateTimeField(verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="description",
            field=models.CharField(default="", max_length=1000, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="updated_at",
            field=models.DateTimeField(verbose_name="Updated at"),
        ),
    ]
