# Generated by Django 5.2 on 2025-04-24 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0025_merge_20250424_1217"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="github.milestone",
            ),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pull_requests",
                to="github.milestone",
            ),
        ),
    ]
