# Generated by Django 5.2 on 2025-05-05 04:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0026_issue_milestone_pullrequest_milestone"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="milestone",
            table="github_milestones",
        ),
    ]
