# Generated by Django 5.1 on 2024-08-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0026_repository_commits_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="pages_status",
            field=models.CharField(default="", max_length=20, verbose_name="Pages status"),
        ),
    ]
