# Generated by Django 5.1 on 2024-08-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0027_repository_pages_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="contributors_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Contributors count"),
        ),
    ]
