# Generated by Django 5.1 on 2024-08-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0028_repository_contributors_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="sequence_id",
            field=models.PositiveIntegerField(default=0, verbose_name="Release internal ID"),
        ),
    ]
