# Generated by Django 5.1 on 2024-08-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0029_release_sequence_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="sequence_id",
            field=models.PositiveBigIntegerField(default=0, verbose_name="Release internal ID"),
        ),
    ]
