# Generated by Django 5.2.3 on 2025-06-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0029_rename_is_owasp_organization_organization_is_owasp_related_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="is_owasp_related_organization",
            field=models.BooleanField(default=True, verbose_name="Is OWASP related organization"),
        ),
    ]
