# Generated by Django 5.1 on 2024-08-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0031_repository_is_owasp_repository"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="commits_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Commits"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="contributors_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Contributors"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="forks_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Forks"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="open_issues_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Open issues"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="stars_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Stars"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="subscribers_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Subscribers"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="watchers_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Watchers"),
        ),
    ]
