# Generated by Django 5.2.4 on 2025-07-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0031_alter_repository_organization"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["-created_at"], name="github_user_created_at_desc"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["-updated_at"], name="github_user_updated_at_desc"),
        ),
    ]
