# Generated by Django 5.1 on 2024-08-26 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0032_alter_repository_commits_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="releases",
                to="github.repository",
            ),
        ),
    ]
