# Generated by Django 5.2.4 on 2025-08-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0033_alter_release_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="interested_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="interested_issues",
                to="github.user",
                verbose_name="Interested Users",
            ),
        ),
    ]
