# Generated by Django 5.2.4 on 2025-08-04 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0033_alter_release_published_at"),
        ("github", "0033_user_is_owasp_staff"),
    ]

    operations = []
