# Generated by Django 5.2.4 on 2025-08-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0034_merge_20250804_1817"),
        ("owasp", "0045_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="badges",
            field=models.ManyToManyField(
                blank=True,
                help_text="Badges assigned to this user.",
                related_name="users",
                to="owasp.badge",
                verbose_name="Badges",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_owasp_staff",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the user is OWASP Foundation staff.",
                verbose_name="Is OWASP Staff",
            ),
        ),
    ]
