# Generated by Django 5.2.5 on 2025-08-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0034_merge_20250804_1817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=1000, verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_owasp_staff",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the user is OWASP Foundation staff.",
                verbose_name="Is OWASP Staff",
            ),
        ),
    ]
