# Generated by Django 5.1.1 on 2024-09-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0034_label_alter_release_sequence_id_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="issue", to="github.label", verbose_name="Labels"
            ),
        ),
    ]
