# Generated by Django 5.2.4 on 2025-08-16 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0034_merge_20250804_1817"),
        ("mentorship", "0006_remove_task_level_alter_task_assigned_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="level",
            field=models.ForeignKey(
                blank=True,
                help_text="The difficulty level of this task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="mentorship.tasklevel",
            ),
        ),
    ]
