# Generated by Django 5.2.5 on 2025-08-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0034_merge_20250804_1817"),
        ("nest", "0005_alter_userbadge_options_remove_user_badges_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="badges",
            field=models.ManyToManyField(
                blank=True,
                related_name="github_users",
                through="nest.GithubUserBadge",
                through_fields=("github_user", "badge"),
                to="nest.badge",
                verbose_name="Badges",
            ),
        ),
    ]
