# Generated by Django 5.2.5 on 2025-08-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0035_alter_user_bio_alter_user_is_owasp_staff"),
        ("owasp", "0045_badge"),
    ]

    operations = [
        # Add the badges field that was missing
        migrations.AddField(
            model_name="user",
            name="badges",
            field=models.ManyToManyField(
                "owasp.Badge",
                blank=True,
                help_text="Badges assigned to this user.",
                related_name="users",
                verbose_name="Badges",
            ),
        ),
        # Keep the existing field alterations
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=1000, verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_owasp_staff",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the user is OWASP Foundation staff.",
                verbose_name="Is OWASP Staff",
            ),
        ),
    ]
