# Generated by Django 5.2.5 on 2025-09-24 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("github", "0035_alter_user_bio_alter_user_is_owasp_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("github_id", models.BigIntegerField(unique=True, verbose_name="Github ID")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Updated at"
                    ),
                ),
                ("body", models.TextField(verbose_name="Body")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="github.user",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "db_table": "github_comments",
                "ordering": ("-nest_created_at",),
            },
        ),
    ]
