# Generated by Django 5.2.4 on 2025-09-05 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0035_alter_user_bio_alter_user_is_owasp_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("github_id", models.BigIntegerField(unique=True)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="github.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="comments",
            field=models.ManyToManyField(blank=True, related_name="issues", to="github.comment"),
        ),
    ]
