# Generated by Django 5.2.6 on 2025-09-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0035_alter_user_bio_alter_user_is_owasp_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_public_member_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="Name"),
        ),
    ]
