# Generated by Django 5.2.4 on 2025-09-13 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0035_alter_user_bio_alter_user_is_owasp_staff"),
        ("mentorship", "0004_module_key_program_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="level",
            field=models.ForeignKey(
                blank=True,
                help_text="The difficulty level of this issue.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="mentorship.tasklevel",
            ),
        ),
    ]
