# Generated by Django 5.2.4 on 2025-09-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0036_comment_issue_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="last_comment_sync",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Last comment sync"
            ),
        ),
    ]
