# Generated by Django 5.2.5 on 2025-09-25 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0036_user_has_public_member_page_alter_organization_name_and_more"),
        ("mentorship", "0004_module_key_program_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="level",
            field=models.ForeignKey(
                blank=True,
                help_text="The difficulty level of this issue.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="mentorship.tasklevel",
            ),
        ),
    ]
