# Generated by Django 5.1.1 on 2024-09-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0036_alter_issue_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="assignees",
            field=models.ManyToManyField(
                blank=True, related_name="issue", to="github.user", verbose_name="Assignees"
            ),
        ),
    ]
