# Generated by Django 5.2.5 on 2025-09-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("github", "0036_user_has_public_member_page_alter_organization_name_and_more"),
        ("mentorship", "0004_module_key_program_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="level",
            field=models.ForeignKey(
                blank=True,
                help_text="The difficulty level of this issue.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="mentorship.tasklevel",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("github_id", models.BigIntegerField(unique=True, verbose_name="Github ID")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Updated at"
                    ),
                ),
                ("body", models.TextField(verbose_name="Body")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="github.user",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "db_table": "github_comments",
                "ordering": ("-nest_created_at",),
            },
        ),
    ]
