# Generated by Django 5.2.5 on 2025-10-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0037_issue_level_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="related_issues",
            field=models.ManyToManyField(
                blank=True, related_name="pull_requests", to="github.issue", verbose_name="Issues"
            ),
        ),
    ]
