# Generated by Django 5.1.1 on 2024-09-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0037_issue_assignees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="assignee",
        ),
        migrations.AddField(
            model_name="issue",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Closed at"),
        ),
        migrations.AddField(
            model_name="issue",
            name="state_reason",
            field=models.CharField(default="", max_length=200, verbose_name="State reason"),
        ),
    ]
