# Generated by Django 5.1.1 on 2024-09-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0038_remove_issue_assignee_issue_closed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="title",
            field=models.CharField(max_length=300, verbose_name="Title"),
        ),
    ]
