# Generated by Django 5.2.7 on 2025-10-19 03:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0038_commit"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="commit",
            name="commit_repo_created_idx",
        ),
    ]
