# Generated by Django 5.2.6 on 2025-11-16 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0036_comment"),
        ("github", "0037_issue_level"),
        ("github", "0038_pullrequest_related_issues"),
    ]

    operations = []
