# Generated by Django 5.1.1 on 2024-09-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0039_alter_issue_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ("-updated_at", "-state"), "verbose_name_plural": "Issues"},
        ),
        migrations.AlterField(
            model_name="issue",
            name="url",
            field=models.URLField(default="", max_length=500, verbose_name="URL"),
        ),
    ]
