# Generated by Django 6.0 on 2026-01-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0040_merge_20251117_0136"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(fields=["-created_at"], name="github_milestone_created_at"),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(fields=["-updated_at"], name="github_milestone_updated_at"),
        ),
    ]
