# Generated by Django 5.1.1 on 2024-09-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0041_alter_issue_repository"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="title",
            field=models.CharField(max_length=500, verbose_name="Title"),
        ),
    ]
