# Generated by Django 6.0.1 on 2026-01-27 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0041_milestone_github_milestone_created_at_and_more"),
        ("github", "0041_user_contribution_data"),
    ]

    operations = []
