# Generated by Django 5.1.1 on 2024-09-09 21:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0040_alter_issue_url"),
        ("github", "0043_alter_issue_updated_at"),
    ]

    operations = []
