# Generated by Django 6.0.2 on 2026-03-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0043_alter_user_contribution_data"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["name"], name="github_user_name_asc"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["-name"], name="github_user_name_desc"),
        ),
    ]
