# Generated by Django 6.0.3 on 2026-03-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0044_user_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="calculated_score",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="Member ranking score based on contributions and roles",
                verbose_name="Calculated ranking score",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["-calculated_score"], name="idx_calc_score_desc"),
        ),
    ]
