# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0044_user_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="calculated_score",
            field=models.FloatField(
                default=0.0,
                help_text="Composite ranking score based on contributions, leadership, recency, and breadth.",
                verbose_name="Calculated score",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["-calculated_score"],
                name="github_user_calc_score_desc",
            ),
        ),
    ]
