# Generated by Django 6.0.2 on 2026-03-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0044_user_github_user_name_asc_user_github_user_name_desc"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["login"], name="github_user_login_asc"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["-login"], name="github_user_login_desc"),
        ),
    ]
