# Generated by Django 6.0.5 on 2026-06-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0044_user_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_claim_reviewer",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the user is Claim reviewer for BoD candidate elections.",
                verbose_name="Is Claim Reviewer",
            ),
        ),
    ]
