# Generated by Django 5.1.1 on 2024-10-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="Key"),
                ),
                (
                    "text",
                    models.TextField(blank=True, default="", max_length=1000, verbose_name="Text"),
                ),
            ],
            options={
                "verbose_name_plural": "Prompts",
                "db_table": "nest_prompts",
            },
        ),
    ]
