# Generated by Django 5.1.1 on 2024-10-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="key",
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name="Key"),
        ),
    ]
