"""Slack app constants."""

NEST_BOT_NAME = "NestBot"

OWASP_CONTRIBUTE_CHANNEL_ID = "C04DH8HEPTR"
OWASP_GSOC_CHANNEL_ID = "CFJLZNFN1"
OWASP_PROJECT_JUICE_SHOP_CHANNEL_ID = "C255XSY04"
OWASP_PROJECT_NEST_CHANNEL_ID = "C07JLLG2GFQ"
OWASP_PROJECT_NETTACKER_CHANNEL_ID = "CQZGG24FQ"
OWASP_PROJECT_THREAT_DRAGON_CHANNEL_ID = "CURE8PQ68"

FEEDBACK_CHANNEL_MESSAGE = (
    f"💬 You can share feedback on your {NEST_BOT_NAME} experience "
    f"in the <#{OWASP_PROJECT_NEST_CHANNEL_ID}|project-nest> channel."
)

NL = "\n"
NLNL = "\n\n"
