slack-sync-data:
	@echo "Syncing Slack data"
	@CMD="python manage.py slack_sync_data" $(MAKE) exec-backend-command

slack-sync-messages:
	@echo "Syncing Slack messages"
	@CMD="python manage.py slack_sync_messages" $(MAKE) exec-backend-command
