"""Slack bot view for Slack events."""

from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_GET, require_POST
from slack_bolt.adapter.django import SlackRequestHandler

from apps.slack.apps import SlackConfig
from apps.slack.models.google_auth import GoogleAuth

slack_handler = SlackRequestHandler(SlackConfig.app)


@csrf_exempt  # NOSONAR
@require_POST  # NOSONAR
def slack_request_handler(request):
    """Handle Slack requests.

    Args:
        request (HttpRequest): The HTTP request object from Slack.

    Returns:
        HttpResponse: The response generated by the SlackRequestHandler.

    """
    return slack_handler.handle(request)


@require_GET
def google_auth_callback(request):
    """Handle Google OAuth callback.

    Args:
        request (HttpRequest): The HTTP request object from Google.

    Returns:
        HttpResponse: The response generated by the Google OAuth flow.

    """
    # Handle the Google OAuth callback logic here
    member_id = request.GET.get("state")
    auth_response = request.build_absolute_uri()
    GoogleAuth.authenticate_callback(auth_response, member_id)
    return HttpResponse("Google OAuth callback handled successfully.")
