"""Slack bot view for Slack events."""

from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from slack_bolt.adapter.django import SlackRequestHandler

from apps.slack.apps import SlackConfig

slack_handler = SlackRequestHandler(SlackConfig.app)


@csrf_exempt  # NOSONAR # nosemgrep
@require_POST  # NOSONAR
def slack_request_handler(request):
    """Handle Slack requests.

    Args:
        request (HttpRequest): The HTTP request object from Slack.

    Returns:
        HttpResponse: The response generated by the SlackRequestHandler.

    """
    return slack_handler.handle(request)
