export const mockAboutData = {
  project: {
    id: 'project-nest',
    name: 'OWASP Nest',
    contributorsCount: 1200,
    issuesCount: 40,
    forksCount: 60,
    starsCount: 890,
    summary: 'A community-first platform for OWASP collaboration',
    recentMilestones: [
      {
        id: 'milestone-1',
        title: 'NestBot title',
        body: 'NestBot Idea',
        url: 'http/github.com/milestones/5',
        progress: 58,
        state: 'open',
      },
      {
        id: 'milestone-2',
        title: 'Contribution Hub title',
        body: 'Contribution Hub Idea',
        url: 'http/github.com/milestones/8',
        progress: 75,
        state: 'open',
      },
      {
        id: 'milestone-3',
        title: 'Project Dashboard title',
        body: 'Project Dashboard Idea',
        url: 'http/github.com/milestones/10',
        progress: 80,
        state: 'open',
      },
      {
        id: 'milestone-4',
        title: 'Milestone 4',
        body: 'Milestone 4 Idea',
        url: 'http/github.com/milestones/11',
        progress: 20,
        state: 'open',
      },
      {
        id: 'milestone-5',
        title: 'Milestone 5',
        body: 'Milestone 5 Idea',
        url: 'http/github.com/milestones/12',
        progress: 40,
        state: 'open',
      },
    ],
  },
  topContributors: Array.from({ length: 15 }, (_, i) => ({
    id: `contributor-${i + 1}`,
    avatarUrl: `https://avatars.githubusercontent.com/avatar${i + 1}.jpg`,
    login: `contributor${i + 1}`,
    name: `Contributor ${i + 1}`,
  })),
  users: {
    arkid15r: {
      id: 'user-arkid15r',
      avatarUrl: 'https://avatars.githubusercontent.com/u/2201626?v=4',
      login: 'arkid15r',
      name: 'Arkadii Yakovets',
      badgeCount: 0,
      badges: [],
    },
    kasya: {
      id: 'user-kasya',
      avatarUrl: 'https://avatars.githubusercontent.com/u/5873153?v=4',
      login: 'kasya',
      name: 'Kate Golovanova',
      badgeCount: 0,
      badges: [],
    },
    mamicidal: {
      id: 'user-mamicidal',
      avatarUrl: 'https://avatars.githubusercontent.com/u/112129498?v=4',
      login: 'mamicidal',
      name: 'Starr Brown',
      badgeCount: 0,
      badges: [],
    },
  },
}
