export const mockSnapshotDetailsData = {
  snapshot: {
    title: 'New Snapshot',
    key: '2024-12',
    updatedAt: '2025-03-02T19:33:46.000Z',
    createdAt: '2025-03-01T21:40:34.000Z',
    startAt: '2024-12-01T00:00:00.000Z',
    endAt: '2025-01-01T00:00:30.000Z',
    status: 'completed',
    errorMessage: '',
    releases: [
      {
        id: 'release-1',
        name: 'v0.9.2',
        publishedAt: '2024-12-13T14:43:46.000Z',
        tagName: 'v0.9.2',
        projectName: 'test-project-1',
        organizationName: 'owasp',
        repositoryName: 'test-project-1',
        author: {
          id: '1',
          avatarUrl: 'https://avatars.githubusercontent.com/u/2201626?v=4',
          login: 'arkid15r',
          name: 'Arkadii Yakovets',
        },
      },
      {
        id: 'release-2',
        name: 'Latest pre-release',
        publishedAt: '2024-12-13T13:17:30.000Z',
        tagName: 'pre-release',
        projectName: 'test-project-2',
        organizationName: 'owasp',
        repositoryName: 'test-project-2',
        author: {
          id: '2',
          avatarUrl: 'https://avatars.githubusercontent.com/u/97700473?v=4',
          login: 'test-user',
          name: 'test user',
        },
      },
    ],
    projects: [
      {
        key: 'nest',
        name: 'OWASP Nest',
        summary:
          'OWASP Nest is a code project aimed at improving how OWASP manages its collection of projects...',
        starsCount: 14,
        forksCount: 19,
        contributorsCount: 14,
        level: 'INCUBATOR',
        isActive: true,
        repositoriesCount: 2,
        topContributors: [
          {
            avatarUrl: 'https://avatars.githubusercontent.com/u/2201626?v=4',
            login: 'arkid15r',
            name: 'Arkadii Yakovets',
          },
          {
            avatarUrl: 'https://avatars.githubusercontent.com/u/97700473?v=4',
            login: 'test-user',
            name: 'test user',
          },
        ],
      },
      {
        key: 'project-2',
        name: 'OWASP ZAP',
        summary: 'Web app scanner.',
        starsCount: 100,
        forksCount: 50,
        contributorsCount: 30,
        level: 'FLAGSHIP',
        isActive: true,
        repositoriesCount: 5,
        topContributors: [],
      },
      {
        key: 'project-3',
        name: 'OWASP Juice Shop',
        summary: 'Intentionally vulnerable web app.',
        starsCount: 200,
        forksCount: 80,
        contributorsCount: 40,
        level: 'FLAGSHIP',
        isActive: true,
        repositoriesCount: 3,
        topContributors: [],
      },
      {
        key: 'project-4',
        name: 'OWASP ModSecurity',
        summary: 'WAF engine.',
        starsCount: 50,
        forksCount: 20,
        contributorsCount: 10,
        level: 'PRODUCTION',
        isActive: true,
        repositoriesCount: 1,
        topContributors: [],
      },
      {
        key: 'project-5',
        name: 'OWASP ASVS',
        summary: 'Application Security Verification Standard.',
        starsCount: 30,
        forksCount: 15,
        contributorsCount: 8,
        level: 'FLAGSHIP',
        isActive: true,
        repositoriesCount: 1,
        topContributors: [],
      },
      {
        key: 'project-6',
        name: 'OWASP SAMM',
        summary: 'Software Assurance Maturity Model.',
        starsCount: 25,
        forksCount: 10,
        contributorsCount: 5,
        level: 'FLAGSHIP',
        isActive: true,
        repositoriesCount: 2,
        topContributors: [],
      },
    ],
    chapters: [
      {
        key: 'sivagangai',
        name: 'OWASP Sivagangai',
        createdAt: '2024-07-30T10:07:33.000Z',
        suggestedLocation: 'Sivagangai, Tamil Nadu, India',
        region: 'Asia',
        summary:
          'OWASP Sivagangai is a new local chapter that focuses on AI and application security...',
        topContributors: [
          {
            avatarUrl: 'https://avatars.githubusercontent.com/u/95969896?v=4',
            login: 'acs-web-tech',
            name: 'P.ARUN',
          },
          {
            avatarUrl: 'https://avatars.githubusercontent.com/u/56408064?v=4',
            login: 'test-user-1',
            name: '',
          },
        ],
        updatedAt: '2024-09-26T12:22:51.000Z',
        url: 'https://owasp.org/www-chapter-sivagangai',
        relatedUrls: [],
        geoLocation: { lat: 9.96, lng: 78.72 },
        isActive: true,
      },
      {
        key: 'chapter-2',
        name: 'OWASP Berlin',
        createdAt: '2024-08-01T00:00:00.000Z',
        suggestedLocation: 'Berlin, Germany',
        region: 'Europe',
        summary: 'Berlin chapter.',
        topContributors: [],
        updatedAt: '2024-09-01T00:00:00.000Z',
        url: 'https://owasp.org/www-chapter-berlin',
        relatedUrls: [],
        geoLocation: { lat: 52.52, lng: 13.4 },
        isActive: true,
      },
      {
        key: 'chapter-3',
        name: 'OWASP Tokyo',
        createdAt: '2024-08-02T00:00:00.000Z',
        suggestedLocation: 'Tokyo, Japan',
        region: 'Asia',
        summary: 'Tokyo chapter.',
        topContributors: [],
        updatedAt: '2024-09-02T00:00:00.000Z',
        url: 'https://owasp.org/www-chapter-tokyo',
        relatedUrls: [],
        geoLocation: { lat: 35.68, lng: 139.69 },
        isActive: true,
      },
      {
        key: 'chapter-4',
        name: 'OWASP Sydney',
        createdAt: '2024-08-03T00:00:00.000Z',
        suggestedLocation: 'Sydney, Australia',
        region: 'Oceania',
        summary: 'Sydney chapter.',
        topContributors: [],
        updatedAt: '2024-09-03T00:00:00.000Z',
        url: 'https://owasp.org/www-chapter-sydney',
        relatedUrls: [],
        geoLocation: { lat: -33.86, lng: 151.2 },
        isActive: true,
      },
      {
        key: 'chapter-5',
        name: 'OWASP Paris',
        createdAt: '2024-08-04T00:00:00.000Z',
        suggestedLocation: 'Paris, France',
        region: 'Europe',
        summary: 'Paris chapter.',
        topContributors: [],
        updatedAt: '2024-09-04T00:00:00.000Z',
        url: 'https://owasp.org/www-chapter-paris',
        relatedUrls: [],
        geoLocation: { lat: 48.85, lng: 2.35 },
        isActive: true,
      },
      {
        key: 'chapter-6',
        name: 'OWASP London',
        createdAt: '2024-08-05T00:00:00.000Z',
        suggestedLocation: 'London, UK',
        region: 'Europe',
        summary: 'London chapter.',
        topContributors: [],
        updatedAt: '2024-09-05T00:00:00.000Z',
        url: 'https://owasp.org/www-chapter-london',
        relatedUrls: [],
        geoLocation: { lat: 51.5, lng: -0.12 },
        isActive: true,
      },
    ],
    events: [
      {
        id: 'event-1',
        category: 'Other',
        endDate: '2024-12-15',
        key: 'local-meetup',
        name: 'Local Meetup',
        startDate: '2024-12-13',
        suggestedLocation: 'San Francisco, CA',
        summary: 'A local meetup event.',
        url: 'https://owasp.org/events/local-meetup',
      },
      {
        id: 'event-2',
        category: 'Global',
        endDate: '2024-12-20',
        key: 'global-appsec',
        name: 'Global AppSec 2024',
        startDate: '2024-12-18',
        suggestedLocation: 'London, UK',
        summary: 'Global application security conference.',
        url: 'https://owasp.org/events/global-appsec',
      },
      {
        id: 'event-3',
        category: 'AppSec_Days',
        endDate: '2024-12-22',
        key: 'appsec-days',
        name: 'AppSec Days Pacific',
        startDate: '2024-12-21',
        suggestedLocation: 'Tokyo, Japan',
        summary: 'Regional AppSec conference.',
        url: 'https://owasp.org/events/appsec-days',
      },
      {
        id: 'event-4',
        category: 'Partner',
        endDate: '2024-12-25',
        key: 'partner-event',
        name: 'Partner Security Summit',
        startDate: '2024-12-24',
        suggestedLocation: 'Berlin, Germany',
        summary: 'Partner event.',
        url: 'https://owasp.org/events/partner-event',
      },
      {
        id: 'event-5',
        category: 'Other',
        endDate: '2024-12-28',
        key: 'workshop',
        name: 'Security Workshop',
        startDate: '2024-12-27',
        suggestedLocation: null,
        summary: null,
        url: 'https://owasp.org/events/workshop',
      },
      {
        id: 'event-6',
        category: 'Global',
        endDate: '2024-12-31',
        key: 'global-summit',
        name: 'Global Summit',
        startDate: '2024-12-30',
        suggestedLocation: 'Paris, France',
        summary: 'End of year summit.',
        url: 'https://owasp.org/events/global-summit',
      },
    ],
    posts: [
      {
        id: 'post-1',
        authorImageUrl: 'https://avatars.githubusercontent.com/u/2201626?v=4',
        authorName: 'Arkadii Yakovets',
        publishedAt: '2024-12-10T10:00:00.000Z',
        title: 'OWASP Nest: Year in Review',
        url: 'https://owasp.org/blog/nest-review',
      },
      {
        id: 'post-2',
        authorImageUrl: null,
        authorName: 'Jane Doe',
        publishedAt: '2024-12-11T10:00:00.000Z',
        title: 'Post Two',
        url: 'https://owasp.org/blog/post-2',
      },
      {
        id: 'post-3',
        authorImageUrl: 'https://avatars.githubusercontent.com/u/3?v=4',
        authorName: 'Author Three',
        publishedAt: '2024-12-12T10:00:00.000Z',
        title: 'Post Three',
        url: 'https://owasp.org/blog/post-3',
      },
      {
        id: 'post-4',
        authorImageUrl: 'https://avatars.githubusercontent.com/u/4?v=4',
        authorName: 'Author Four',
        publishedAt: '2024-12-13T10:00:00.000Z',
        title: 'Post Four',
        url: 'https://owasp.org/blog/post-4',
      },
      {
        id: 'post-5',
        authorImageUrl: 'https://avatars.githubusercontent.com/u/5?v=4',
        authorName: 'Author Five',
        publishedAt: '2024-12-14T10:00:00.000Z',
        title: 'Post Five',
        url: 'https://owasp.org/blog/post-5',
      },
      {
        id: 'post-6',
        authorImageUrl: 'https://avatars.githubusercontent.com/u/6?v=4',
        authorName: 'Author Six',
        publishedAt: '2024-12-15T10:00:00.000Z',
        title: 'Post Six',
        url: 'https://owasp.org/blog/post-6',
      },
    ],
    pullRequests: [
      {
        id: 'pr-1',
        author: {
          avatarUrl: 'https://avatars.githubusercontent.com/u/2201626?v=4',
          id: '1',
          login: 'arkid15r',
          name: 'Arkadii Yakovets',
        },
        createdAt: '2024-12-12T09:00:00.000Z',
        mergedAt: '2024-12-13T09:00:00.000Z',
        organizationName: 'owasp',
        repositoryName: 'nest',
        state: 'closed',
        title: 'Add snapshot subscription feature',
        url: 'https://github.com/owasp/nest/pull/100',
      },
      {
        id: 'pr-2',
        author: {
          avatarUrl: 'https://avatars.githubusercontent.com/u/2?v=4',
          id: '2',
          login: 'user2',
          name: 'User Two',
        },
        createdAt: '2024-12-13T09:00:00.000Z',
        mergedAt: null,
        organizationName: 'owasp',
        repositoryName: 'nest',
        state: 'open',
        title: 'PR Two',
        url: 'https://github.com/owasp/nest/pull/101',
      },
      {
        id: 'pr-3',
        author: null,
        createdAt: '2024-12-14T09:00:00.000Z',
        mergedAt: null,
        organizationName: 'owasp',
        repositoryName: null,
        state: 'closed',
        title: 'PR Three',
        url: 'https://github.com/owasp/nest/pull/102',
      },
      {
        id: 'pr-4',
        author: {
          avatarUrl: 'https://avatars.githubusercontent.com/u/4?v=4',
          id: '4',
          login: 'user4',
          name: 'User Four',
        },
        createdAt: '2024-12-15T09:00:00.000Z',
        mergedAt: null,
        organizationName: 'owasp',
        repositoryName: 'nest',
        state: 'open',
        title: 'PR Four',
        url: 'https://github.com/owasp/nest/pull/103',
      },
      {
        id: 'pr-5',
        author: {
          avatarUrl: 'https://avatars.githubusercontent.com/u/5?v=4',
          id: '5',
          login: 'user5',
          name: 'User Five',
        },
        createdAt: '2024-12-16T09:00:00.000Z',
        mergedAt: null,
        organizationName: 'owasp',
        repositoryName: 'nest',
        state: 'open',
        title: 'PR Five',
        url: 'https://github.com/owasp/nest/pull/104',
      },
      {
        id: 'pr-6',
        author: {
          avatarUrl: 'https://avatars.githubusercontent.com/u/6?v=4',
          id: '6',
          login: 'user6',
          name: 'User Six',
        },
        createdAt: '2024-12-17T09:00:00.000Z',
        mergedAt: null,
        organizationName: 'owasp',
        repositoryName: 'nest',
        state: 'open',
        title: 'PR Six',
        url: 'https://github.com/owasp/nest/pull/105',
      },
      {
        id: 'pr-7',
        author: {
          avatarUrl: 'https://avatars.githubusercontent.com/u/7?v=4',
          id: '7',
          login: 'user7',
          name: 'User Seven',
        },
        createdAt: '2024-12-18T09:00:00.000Z',
        mergedAt: null,
        organizationName: 'owasp',
        repositoryName: 'nest',
        state: 'open',
        title: 'PR Seven',
        url: 'https://github.com/owasp/nest/pull/106',
      },
    ],
    issues: [
      {
        id: 'issue-1',
        author: {
          avatarUrl: 'https://avatars.githubusercontent.com/u/2201626?v=4',
          id: '1',
          login: 'arkid15r',
          name: 'Arkadii Yakovets',
        },
        createdAt: '2024-12-11T08:00:00.000Z',
        organizationName: 'owasp',
        repositoryName: 'nest',
        state: 'open',
        title: 'Add snapshot email notifications',
        url: 'https://github.com/owasp/nest/issues/50',
      },
      {
        id: 'issue-2',
        author: {
          avatarUrl: 'https://avatars.githubusercontent.com/u/2?v=4',
          id: '2',
          login: 'user2',
          name: 'User Two',
        },
        createdAt: '2024-12-12T08:00:00.000Z',
        organizationName: 'owasp',
        repositoryName: 'nest',
        state: 'closed',
        title: 'Issue Two',
        url: 'https://github.com/owasp/nest/issues/51',
      },
      {
        id: 'issue-3',
        author: null,
        createdAt: '2024-12-13T08:00:00.000Z',
        organizationName: 'owasp',
        repositoryName: null,
        state: 'open',
        title: 'Issue Three',
        url: 'https://github.com/owasp/nest/issues/52',
      },
      {
        id: 'issue-4',
        author: {
          avatarUrl: 'https://avatars.githubusercontent.com/u/4?v=4',
          id: '4',
          login: 'user4',
          name: 'User Four',
        },
        createdAt: '2024-12-14T08:00:00.000Z',
        organizationName: 'owasp',
        repositoryName: 'nest',
        state: 'open',
        title: 'Issue Four',
        url: 'https://github.com/owasp/nest/issues/53',
      },
      {
        id: 'issue-5',
        author: {
          avatarUrl: 'https://avatars.githubusercontent.com/u/5?v=4',
          id: '5',
          login: 'user5',
          name: 'User Five',
        },
        createdAt: '2024-12-15T08:00:00.000Z',
        organizationName: 'owasp',
        repositoryName: 'nest',
        state: 'open',
        title: 'Issue Five',
        url: 'https://github.com/owasp/nest/issues/54',
      },
      {
        id: 'issue-6',
        author: {
          avatarUrl: 'https://avatars.githubusercontent.com/u/6?v=4',
          id: '6',
          login: 'user6',
          name: 'User Six',
        },
        createdAt: '2024-12-16T08:00:00.000Z',
        organizationName: 'owasp',
        repositoryName: 'nest',
        state: 'open',
        title: 'Issue Six',
        url: 'https://github.com/owasp/nest/issues/55',
      },
      {
        id: 'issue-7',
        author: {
          avatarUrl: 'https://avatars.githubusercontent.com/u/7?v=4',
          id: '7',
          login: 'user7',
          name: 'User Seven',
        },
        createdAt: '2024-12-17T08:00:00.000Z',
        organizationName: 'owasp',
        repositoryName: 'nest',
        state: 'open',
        title: 'Issue Seven',
        url: 'https://github.com/owasp/nest/issues/56',
      },
    ],
    users: [
      {
        id: 'user-1',
        avatarUrl: 'https://avatars.githubusercontent.com/u/2201626?v=4',
        login: 'arkid15r',
        name: 'Arkadii Yakovets',
        createdAt: '2024-12-01T00:00:00.000Z',
      },
      {
        id: 'user-2',
        avatarUrl: 'https://avatars.githubusercontent.com/u/97700473?v=4',
        login: 'test-user',
        name: 'Test User',
        createdAt: '2024-12-05T00:00:00.000Z',
      },
      {
        id: 'user-3',
        avatarUrl: 'https://avatars.githubusercontent.com/u/3?v=4',
        login: 'user3',
        name: 'User Three',
        createdAt: '2024-12-03T00:00:00.000Z',
      },
      {
        id: 'user-4',
        avatarUrl: 'https://avatars.githubusercontent.com/u/4?v=4',
        login: 'user4',
        name: 'User Four',
        createdAt: '2024-12-04T00:00:00.000Z',
      },
      {
        id: 'user-5',
        avatarUrl: 'https://avatars.githubusercontent.com/u/5?v=4',
        login: 'user5',
        name: 'User Five',
        createdAt: '2024-12-05T00:00:00.000Z',
      },
      {
        id: 'user-6',
        avatarUrl: 'https://avatars.githubusercontent.com/u/6?v=4',
        login: 'user6',
        name: 'User Six',
        createdAt: '2024-12-06T00:00:00.000Z',
      },
      {
        id: 'user-7',
        avatarUrl: 'https://avatars.githubusercontent.com/u/7?v=4',
        login: 'user7',
        name: 'User Seven',
        createdAt: '2024-12-07T00:00:00.000Z',
      },
      {
        id: 'user-8',
        avatarUrl: 'https://avatars.githubusercontent.com/u/8?v=4',
        login: 'user8',
        name: 'User Eight',
        createdAt: '2024-12-08T00:00:00.000Z',
      },
      {
        id: 'user-9',
        avatarUrl: 'https://avatars.githubusercontent.com/u/9?v=4',
        login: 'user9',
        name: 'User Nine',
        createdAt: '2024-12-09T00:00:00.000Z',
      },
      {
        id: 'user-10',
        avatarUrl: 'https://avatars.githubusercontent.com/u/10?v=4',
        login: 'user10',
        name: 'User Ten',
        createdAt: '2024-12-10T00:00:00.000Z',
      },
      {
        id: 'user-11',
        avatarUrl: 'https://avatars.githubusercontent.com/u/11?v=4',
        login: 'user11',
        name: 'User Eleven',
        createdAt: '2024-12-11T00:00:00.000Z',
      },
      {
        id: 'user-12',
        avatarUrl: 'https://avatars.githubusercontent.com/u/12?v=4',
        login: 'user12',
        name: 'User Twelve',
        createdAt: '2024-12-12T00:00:00.000Z',
      },
      {
        id: 'user-13',
        avatarUrl: 'https://avatars.githubusercontent.com/u/13?v=4',
        login: 'user13',
        name: 'User Thirteen',
        createdAt: '2024-12-13T00:00:00.000Z',
      },
    ],
  },
}

export const mockSnapshotData = {
  snapshots: [
    {
      title: 'New Snapshot',
      key: '2024-12',
      startAt: '2024-12-01T00:00:00.000Z',
      endAt: '2025-01-01T00:00:30.000Z',
    },
  ],
}
