# Generated by Django 5.2.3 on 2025-06-24 22:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("github", "0030_alter_organization_is_owasp_related_organization"),
        ("owasp", "0043_projecthealthmetrics_unique_daily_project_health_metrics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mentee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=12,
                        verbose_name="Experience level",
                    ),
                ),
                (
                    "domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Domain expertise (e.g., Application Security, Threat Modeling, etc)",
                        verbose_name="Domains",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Technologies, languages, frameworks, etc",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "github_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="github.user",
                        verbose_name="GitHub user",
                    ),
                ),
                (
                    "nest_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nest user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mentees",
                "db_table": "mentorship_mentees",
            },
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=12,
                        verbose_name="Experience level",
                    ),
                ),
                (
                    "domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Domain expertise (e.g., Application Security, Threat Modeling, etc)",
                        verbose_name="Domains",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Technologies, languages, frameworks, etc",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "github_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="github.user",
                        verbose_name="GitHub user",
                    ),
                ),
                (
                    "nest_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nest user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mentors",
                "db_table": "mentorship_mentors",
            },
        ),
        migrations.CreateModel(
            name="MentorModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=12,
                        verbose_name="Experience level",
                    ),
                ),
                (
                    "domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Domain expertise (e.g., Application Security, Threat Modeling, etc)",
                        verbose_name="Domains",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Technologies, languages, frameworks, etc",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True, default="Mentor", max_length=100, verbose_name="Role"
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.mentor",
                        verbose_name="Program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentor module",
                "verbose_name_plural": "Mentor modules",
                "db_table": "mentorship_mentor_modules",
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=12,
                        verbose_name="Experience level",
                    ),
                ),
                (
                    "domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Domain expertise (e.g., Application Security, Threat Modeling, etc)",
                        verbose_name="Domains",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Technologies, languages, frameworks, etc",
                        verbose_name="Tags",
                    ),
                ),
                ("ended_at", models.DateTimeField(verbose_name="End date and time")),
                ("started_at", models.DateTimeField(verbose_name="Start date and time")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Description"),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=200, verbose_name="Name"),
                ),
                (
                    "mentors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="modules",
                        through="mentorship.MentorModule",
                        to="mentorship.mentor",
                        verbose_name="Mentors",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="owasp.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Modules",
                "db_table": "mentorship_modules",
            },
        ),
        migrations.AddField(
            model_name="mentormodule",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mentorship.module",
                verbose_name="Module",
            ),
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Domain expertise (e.g., Application Security, Threat Modeling, etc)",
                        verbose_name="Domains",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Technologies, languages, frameworks, etc",
                        verbose_name="Tags",
                    ),
                ),
                ("ended_at", models.DateTimeField(verbose_name="End date and time")),
                ("started_at", models.DateTimeField(verbose_name="Start date and time")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Description"),
                ),
                (
                    "experience_levels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("beginner", "Beginner"),
                                ("intermediate", "Intermediate"),
                                ("advanced", "Advanced"),
                                ("expert", "Expert"),
                            ],
                            max_length=12,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Experience levels",
                    ),
                ),
                (
                    "mentees_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of mentees allowed in this program",
                        null=True,
                        verbose_name="Mentees limit",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="Name")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=9,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True, to="mentorship.mentor", verbose_name="Admins"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Programs",
                "db_table": "mentorship_programs",
            },
        ),
        migrations.AddField(
            model_name="module",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="mentorship.program",
                verbose_name="Program",
            ),
        ),
        migrations.CreateModel(
            name="MenteeProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=12,
                        verbose_name="Experience level",
                    ),
                ),
                ("ended_at", models.DateTimeField(verbose_name="End date and time")),
                ("started_at", models.DateTimeField(verbose_name="Start date and time")),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.mentee",
                        verbose_name="Mentee",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.program",
                        verbose_name="Program",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mentee programs",
                "db_table": "mentorship_mentee_programs",
                "unique_together": {("mentee", "program")},
            },
        ),
        migrations.AddField(
            model_name="mentee",
            name="programs",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentees",
                through="mentorship.MenteeProgram",
                to="mentorship.program",
                verbose_name="Enrolled programs",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mentormodule",
            unique_together={("mentor", "module")},
        ),
        migrations.CreateModel(
            name="MenteeModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(verbose_name="End date and time")),
                ("started_at", models.DateTimeField(verbose_name="Start date and time")),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.mentee",
                        verbose_name="Mentee",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.module",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mentee modules",
                "db_table": "mentorship_mentee_modules",
                "unique_together": {("mentee", "module")},
            },
        ),
    ]
