# Generated by Django 5.2.5 on 2025-09-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0037_issue_level_comment"),
        ("mentorship", "0004_module_key_program_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="level",
        ),
        migrations.AddField(
            model_name="module",
            name="issues",
            field=models.ManyToManyField(
                blank=True,
                help_text="Issues linked to this module via label matching.",
                related_name="mentorship_modules",
                to="github.issue",
                verbose_name="Linked Issues",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the task was assigned to the mentee.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="IssueUserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_interests",
                        to="github.issue",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="mentorship.module",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_interests",
                        to="github.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue User Interest",
                "verbose_name_plural": "Issue User Interests",
                "db_table": "mentorship_issue_user_interests",
                "unique_together": {("module", "issue", "user")},
            },
        ),
    ]
