# Generated by Django 6.0.6 on 2026-06-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0008_module_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="mentees_can_manage_deadlines",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, mentees can set or update deadlines for issues assigned to them in this module.",
                verbose_name="Mentees can manage deadlines",
            ),
        ),
    ]
