blank_issues_enabled: true
contact_links:
  - name: Any issues to discuss regarding Nest?
    url: https://owasp.slack.com/archives/project-nest
    about: Join us on Slack and meet members and contributors.
