# Generated by Django 5.2.3 on 2025-06-26 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
        ("slack", "0018_conversation_sync_messages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chunk",
            old_name="chunk_text",
            new_name="text",
        ),
        migrations.AlterUniqueTogether(
            name="chunk",
            unique_together={("message", "text")},
        ),
    ]
