# Generated by Django 5.2.3 on 2025-06-26 21:45

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0002_rename_chunk_text_chunk_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chunk",
            options={"verbose_name": "Chunk"},
        ),
        migrations.AlterField(
            model_name="chunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=1536, verbose_name="Embedding"),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="text",
            field=models.TextField(verbose_name="Text"),
        ),
    ]
