# Generated by Django 5.2.3 on 2025-07-01 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0003_alter_chunk_options_alter_chunk_embedding_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chunk",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="chunk",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="chunk",
            name="object_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="message",
        ),
        # we need to remove the unique constraint before adding the new one
        # message needs to be removed first and then we can add the new unique constraint
        migrations.AlterUniqueTogether(
            name="chunk",
            unique_together={("content_type", "object_id", "text")},
        ),
    ]
