# Generated by Django 5.2.4 on 2025-07-28 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0004_alter_chunk_unique_together_chunk_content_type_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Context",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("generated_text", models.TextField(verbose_name="Generated Text")),
                ("object_id", models.PositiveIntegerField(default=0)),
                ("source", models.CharField(blank=True, default="", max_length=100)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Context",
                "db_table": "ai_contexts",
            },
        ),
        migrations.AlterUniqueTogether(
            name="chunk",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="chunk",
            name="context",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="ai.context",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chunk",
            unique_together={("context", "text")},
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="object_id",
        ),
    ]
