# Generated by Django 5.2.4 on 2025-07-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0005_context_alter_chunk_unique_together_chunk_context_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="context",
            old_name="generated_text",
            new_name="content",
        ),
        migrations.AlterField(
            model_name="chunk",
            name="context",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="ai.context",
            ),
        ),
    ]
