# Generated by Django 6.0.3 on 2026-04-13 14:06

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0010_alter_context_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="SemanticCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("confidence", models.FloatField(default=0.0, verbose_name="Confidence")),
                (
                    "intent",
                    models.CharField(blank=True, default="", max_length=50, verbose_name="Intent"),
                ),
                (
                    "query_embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=1536, verbose_name="Query Embedding"
                    ),
                ),
                ("query_text", models.TextField(verbose_name="Query Text")),
                ("response_text", models.TextField(verbose_name="Response Text")),
            ],
            options={
                "verbose_name": "Semantic Cache",
                "db_table": "ai_semantic_cache",
            },
        ),
    ]
