terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.5"
    }
  }
}

resource "aws_ssm_parameter" "django_algolia_application_id" {
  description = "Algolia Application ID."
  name        = "/${var.project_name}/${var.environment}/DJANGO_ALGOLIA_APPLICATION_ID"
  tags        = var.common_tags
  type        = "SecureString"
  value       = "to-be-set-in-aws-console"

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "django_algolia_write_api_key" {
  description = "Algolia Write API Key."
  name        = "/${var.project_name}/${var.environment}/DJANGO_ALGOLIA_WRITE_API_KEY"
  tags        = var.common_tags
  type        = "SecureString"
  value       = "to-be-set-in-aws-console"

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "django_allowed_hosts" {
  description = "The allowed hosts."
  name        = "/${var.project_name}/${var.environment}/DJANGO_ALLOWED_HOSTS"
  tags        = var.common_tags
  type        = "String"
  value       = "to-be-set-in-aws-console"

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "django_configuration" {
  description = "The name of the Django configuration to use (e.g., Staging, Production)."
  name        = "/${var.project_name}/${var.environment}/DJANGO_CONFIGURATION"
  tags        = var.common_tags
  type        = "String"
  value       = "to-be-set-in-aws-console"

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "django_db_host" {
  description = "The hostname of the database."
  name        = "/${var.project_name}/${var.environment}/DJANGO_DB_HOST"
  tags        = var.common_tags
  type        = "String"
  value       = var.db_host
}

resource "aws_ssm_parameter" "django_db_name" {
  description = "The name of the database."
  name        = "/${var.project_name}/${var.environment}/DJANGO_DB_NAME"
  tags        = var.common_tags
  type        = "String"
  value       = var.db_name
}

resource "aws_ssm_parameter" "django_db_password" {
  description = "Database password generated by Terraform."
  name        = "/${var.project_name}/${var.environment}/DJANGO_DB_PASSWORD"
  tags        = var.common_tags
  type        = "SecureString"
  value       = var.db_password
}

resource "aws_ssm_parameter" "django_db_port" {
  description = "The port of the database."
  name        = "/${var.project_name}/${var.environment}/DJANGO_DB_PORT"
  tags        = var.common_tags
  type        = "String"
  value       = var.db_port
}

resource "aws_ssm_parameter" "django_db_user" {
  description = "The user for the database."
  name        = "/${var.project_name}/${var.environment}/DJANGO_DB_USER"
  tags        = var.common_tags
  type        = "String"
  value       = var.db_user
}

resource "aws_ssm_parameter" "django_open_ai_secret_key" {
  description = "OpenAI Secret Key."
  name        = "/${var.project_name}/${var.environment}/DJANGO_OPEN_AI_SECRET_KEY"
  tags        = var.common_tags
  type        = "SecureString"
  value       = "to-be-set-in-aws-console"

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "django_redis_host" {
  description = "The hostname of the Redis cache."
  name        = "/${var.project_name}/${var.environment}/DJANGO_REDIS_HOST"
  tags        = var.common_tags
  type        = "String"
  value       = var.redis_host
}

resource "aws_ssm_parameter" "django_redis_password" {
  description = "The password of Redis cache."
  name        = "/${var.project_name}/${var.environment}/DJANGO_REDIS_PASSWORD"
  tags        = var.common_tags
  type        = "SecureString"
  value       = var.redis_password
}

resource "aws_ssm_parameter" "django_secret_key" {
  description = "Django Secret Key generated by Terraform."
  name        = "/${var.project_name}/${var.environment}/DJANGO_SECRET_KEY"
  tags        = var.common_tags
  type        = "SecureString"
  value       = random_string.django_secret_key.result
}

resource "aws_ssm_parameter" "django_settings_module" {
  description = "The location of the Django settings module to use (e.g., settings.staging, settings.production)."
  name        = "/${var.project_name}/${var.environment}/DJANGO_SETTINGS_MODULE"
  tags        = var.common_tags
  type        = "String"
  value       = "to-be-set-in-aws-console"

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "django_sentry_dsn" {
  description = "The DSN for the Sentry project."
  name        = "/${var.project_name}/${var.environment}/DJANGO_SENTRY_DSN"
  tags        = var.common_tags
  type        = "SecureString"
  value       = "to-be-set-in-aws-console"

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "django_slack_bot_token" {
  description = "The bot token for the Slack integration."
  name        = "/${var.project_name}/${var.environment}/DJANGO_SLACK_BOT_TOKEN"
  tags        = var.common_tags
  type        = "SecureString"
  value       = "to-be-set-in-aws-console"

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "django_slack_signing_secret" {
  description = "The signing secret for the Slack integration."
  name        = "/${var.project_name}/${var.environment}/DJANGO_SLACK_SIGNING_SECRET"
  tags        = var.common_tags
  type        = "SecureString"
  value       = "to-be-set-in-aws-console"

  lifecycle {
    ignore_changes = [value]
  }
}

resource "random_string" "django_secret_key" {
  length  = 50
  special = true
}
