locals {
  external_runtime_secrets = merge(
    {
      DJANGO_ALGOLIA_WRITE_API_KEY     = "Algolia write API key."
      DJANGO_OPEN_AI_SECRET_KEY        = "OpenAI API key."
      DJANGO_SENTRY_DSN                = "Django Sentry DSN."
      DJANGO_SLACK_BOT_TOKEN           = "Slack bot token."
      DJANGO_SLACK_SIGNING_SECRET      = "Slack signing secret."
      GITHUB_TOKEN                     = "GitHub API token."
      NEXT_SERVER_GITHUB_CLIENT_SECRET = "GitHub OAuth client secret."
    },
    var.enable_additional_parameters ? {
      NEST_GITHUB_APP_PRIVATE_KEY                     = "GitHub App private key."
      "SLACK_BOT_TOKEN_${var.slack_bot_token_suffix}" = "Slack workspace bot token."
    } : {}
  )
}

resource "aws_secretsmanager_secret" "external_runtime" {
  for_each = local.external_runtime_secrets

  description             = each.value
  kms_key_id              = var.kms_key_arn
  name                    = "/${var.project_name}/${var.environment}/${each.key}"
  recovery_window_in_days = var.secret_recovery_window_in_days
  tags                    = var.common_tags
}

resource "aws_secretsmanager_secret" "django_secret_key" {
  description             = "Django secret key generated by Terraform."
  kms_key_id              = var.kms_key_arn
  name                    = "/${var.project_name}/${var.environment}/DJANGO_SECRET_KEY"
  recovery_window_in_days = var.secret_recovery_window_in_days
  tags                    = var.common_tags
}

resource "aws_secretsmanager_secret_version" "django_secret_key" {
  secret_id     = aws_secretsmanager_secret.django_secret_key.id
  secret_string = random_string.django_secret_key.result
}

resource "aws_secretsmanager_secret" "nextauth_secret" {
  description             = "NextAuth secret generated by Terraform."
  kms_key_id              = var.kms_key_arn
  name                    = "/${var.project_name}/${var.environment}/NEXTAUTH_SECRET"
  recovery_window_in_days = var.secret_recovery_window_in_days
  tags                    = var.common_tags
}

resource "aws_secretsmanager_secret_version" "nextauth_secret" {
  secret_id     = aws_secretsmanager_secret.nextauth_secret.id
  secret_string = random_string.nextauth_secret.result
}
