mentorship-sync-module-issues:
	@CMD="python manage.py sync_module_issues" $(MAKE) exec-backend-command

mentorship-sync-issue-levels:
	@CMD="python manage.py sync_issue_levels" $(MAKE) exec-backend-command
