mentorship-sync-issue-levels:
	@echo "Syncing module issue levels"
	@CMD="python manage.py mentorship_sync_issue_levels" $(MAKE) exec-backend-command

mentorship-sync-module-issues:
	@echo "Syncing module issues"
	@CMD="python manage.py mentorship_sync_module_issues" $(MAKE) exec-backend-command

mentorship-update-comments:
	@echo "Updating issue comments"
	@CMD="python manage.py mentorship_update_comments" $(MAKE) exec-backend-command