# Generated by Django 5.2.4 on 2025-07-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0006_rename_generated_text_context_content_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chunk",
            name="context",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="ai.context"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="context",
            unique_together={("content_type", "object_id")},
        ),
    ]
