# Generated by Django 5.2.4 on 2025-08-10 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0007_alter_chunk_context_alter_context_unique_together"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="context",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="context",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
            ),
        ),
        migrations.AlterField(
            model_name="context",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="context",
            unique_together={("content_type", "object_id", "content")},
        ),
    ]
