# Generated by Django 5.2.5 on 2025-08-15 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0008_alter_context_unique_together_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="context",
            old_name="object_id",
            new_name="entity_id",
        ),
        migrations.RenameField(
            model_name="context",
            old_name="content_type",
            new_name="entity_type",
        ),
        migrations.AlterUniqueTogether(
            name="context",
            unique_together={("entity_type", "entity_id")},
        ),
    ]
