# Generated by Django 5.2.6 on 2025-10-01 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0009_rename_object_id_context_entity_id_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="context",
            unique_together={("entity_type", "entity_id", "source")},
        ),
    ]
