[tool.poetry]
name = "e2e"
version = "0.1.0"
description = "OWASP Nest End to End Tests"
authors = ["Arkadii Yakovets <arkadii.yakovets@owasp.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
