# Generated by Django 5.1 on 2024-08-16 02:17

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="platform_update_at",
        ),
        migrations.AddField(
            model_name="repository",
            name="platform_updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 16, 2, 17, 22, 129471, tzinfo=datetime.UTC),
                verbose_name="Repository last updated time",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="repository",
            name="platform_created_at",
            field=models.DateTimeField(verbose_name="Repository created time"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="platform_pushed_at",
            field=models.DateTimeField(verbose_name="Repository last pushed time"),
        ),
    ]
