# Generated by Django 5.1 on 2024-08-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0002_remove_repository_platform_update_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="owner_login",
            field=models.CharField(default="", max_length=100, verbose_name="Owner login"),
        ),
    ]
