# Generated by Django 5.1 on 2024-08-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0003_alter_repository_owner_login"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="repository",
            name="unique_name_platform",
        ),
        migrations.AddField(
            model_name="repository",
            name="key",
            field=models.CharField(default="", max_length=100, verbose_name="Key"),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                fields=("key", "platform"), name="unique_key_platform"
            ),
        ),
    ]
