# Generated by Django 5.1 on 2024-08-16 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0004_remove_repository_unique_name_platform_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repository",
            options={"verbose_name_plural": "Repositories"},
        ),
    ]
