# Generated by Django 5.1 on 2024-08-17 23:16

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0005_alter_repository_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="platform_created_at",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="platform_pushed_at",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="platform_updated_at",
        ),
        migrations.AddField(
            model_name="repository",
            name="has_pages",
            field=models.BooleanField(default=False, verbose_name="Has pages"),
        ),
        migrations.AddField(
            model_name="repository",
            name="is_template",
            field=models.BooleanField(default=False, verbose_name="Is template"),
        ),
        migrations.AddField(
            model_name="repository",
            name="original_created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 17, 23, 16, 11, 654052, tzinfo=datetime.UTC),
                verbose_name="Original created_at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repository",
            name="original_updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 17, 23, 16, 24, 62565, tzinfo=datetime.UTC),
                verbose_name="Original updated_at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repository",
            name="pushed_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 17, 23, 16, 31, 105230, tzinfo=datetime.UTC),
                verbose_name="Pushed at",
            ),
            preserve_default=False,
        ),
    ]
