# Generated by Django 5.1 on 2024-08-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0006_remove_repository_platform_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="repository",
            name="unique_key_platform",
        ),
        migrations.AddField(
            model_name="repository",
            name="default_branch",
            field=models.CharField(default="", max_length=100, verbose_name="Default branch"),
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                fields=("key", "platform", "owner_login"), name="unique_key_platform_owner"
            ),
        ),
    ]
