# Generated by Django 5.1 on 2024-08-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0007_remove_repository_unique_key_platform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="has_downloads",
            field=models.BooleanField(default=False, verbose_name="Has downloads"),
        ),
        migrations.AddField(
            model_name="repository",
            name="has_issues",
            field=models.BooleanField(default=False, verbose_name="Has issues"),
        ),
        migrations.AddField(
            model_name="repository",
            name="has_projects",
            field=models.BooleanField(default=False, verbose_name="Has projects"),
        ),
        migrations.AddField(
            model_name="repository",
            name="has_wiki",
            field=models.BooleanField(default=False, verbose_name="Has wiki"),
        ),
        migrations.AddField(
            model_name="repository",
            name="homepage",
            field=models.CharField(default="", max_length=100, verbose_name="Homepage"),
        ),
        migrations.AddField(
            model_name="repository",
            name="topics",
            field=models.JSONField(default=list, verbose_name="Topics"),
        ),
    ]
