workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
  OWASP Nest API:
    inputs:
      - location: backend/openapi.json
    output: .speakeasy/out.openapi.yaml
    registry:
      location: registry.speakeasyapi.dev/owasp/nest/owasp-nest-api
targets:
  nest-api:
    target: python
    source: OWASP Nest API
    codeSamples:
      registry:
        location: registry.speakeasyapi.dev/owasp/nest/nest-api-python-sdk
      labelOverride:
        fixedValue: Python (SDK)
      blocking: false
