import * as Types from './graphql';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type GetBoardCandidatesQueryVariables = Types.Exact<{
  year: Types.Scalars['Int']['input'];
}>;


export type GetBoardCandidatesQuery = { boardOfDirectors: { __typename: 'BoardOfDirectorsNode', id: string, owaspUrl: string, year: number, candidates: Array<{ __typename: 'EntityMemberNode', id: string, memberName: string, memberEmail: string, description: string, member: { __typename: 'UserNode', id: string, login: string, name: string, avatarUrl: string, bio: string, createdAt: number, firstOwaspContributionAt: number | null, isOwaspBoardMember: boolean, isFormerOwaspStaff: boolean, isGsocMentor: boolean } | null }> } | null };

export type GetMemberSnapshotQueryVariables = Types.Exact<{
  userLogin: Types.Scalars['String']['input'];
}>;


export type GetMemberSnapshotQuery = { memberSnapshot: { __typename: 'MemberSnapshotNode', channelCommunications: any, chapterContributions: any, commitsCount: number, communicationHeatmapData: any, contributionHeatmapData: any, endAt: any, id: string, issuesCount: number, messagesCount: number, projectContributions: any, pullRequestsCount: number, repositoryContributions: any, startAt: any, totalContributions: number, githubUser: { __typename: 'UserNode', login: string } } | null };

export type GetChapterByKeyQueryVariables = Types.Exact<{
  key: Types.Scalars['String']['input'];
}>;


export type GetChapterByKeyQuery = { chapter: { __typename: 'ChapterNode', id: string, key: string, name: string, url: string } | null };

export type GetProjectByKeyQueryVariables = Types.Exact<{
  key: Types.Scalars['String']['input'];
}>;


export type GetProjectByKeyQuery = { project: { __typename: 'ProjectNode', id: string, key: string, level: string, name: string, type: string, url: string } | null };


export const GetBoardCandidatesDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetBoardCandidates"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"year"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"boardOfDirectors"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"year"},"value":{"kind":"Variable","name":{"kind":"Name","value":"year"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"candidates"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"memberName"}},{"kind":"Field","name":{"kind":"Name","value":"memberEmail"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"member"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"login"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"avatarUrl"}},{"kind":"Field","name":{"kind":"Name","value":"bio"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"firstOwaspContributionAt"}},{"kind":"Field","name":{"kind":"Name","value":"isOwaspBoardMember"}},{"kind":"Field","name":{"kind":"Name","value":"isFormerOwaspStaff"}},{"kind":"Field","name":{"kind":"Name","value":"isGsocMentor"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"owaspUrl"}},{"kind":"Field","name":{"kind":"Name","value":"year"}}]}}]}}]} as unknown as DocumentNode<GetBoardCandidatesQuery, GetBoardCandidatesQueryVariables>;
export const GetMemberSnapshotDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetMemberSnapshot"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"userLogin"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"memberSnapshot"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"userLogin"},"value":{"kind":"Variable","name":{"kind":"Name","value":"userLogin"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"channelCommunications"}},{"kind":"Field","name":{"kind":"Name","value":"chapterContributions"}},{"kind":"Field","name":{"kind":"Name","value":"commitsCount"}},{"kind":"Field","name":{"kind":"Name","value":"communicationHeatmapData"}},{"kind":"Field","name":{"kind":"Name","value":"contributionHeatmapData"}},{"kind":"Field","name":{"kind":"Name","value":"endAt"}},{"kind":"Field","name":{"kind":"Name","value":"githubUser"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"login"}}]}},{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"issuesCount"}},{"kind":"Field","name":{"kind":"Name","value":"messagesCount"}},{"kind":"Field","name":{"kind":"Name","value":"projectContributions"}},{"kind":"Field","name":{"kind":"Name","value":"pullRequestsCount"}},{"kind":"Field","name":{"kind":"Name","value":"repositoryContributions"}},{"kind":"Field","name":{"kind":"Name","value":"startAt"}},{"kind":"Field","name":{"kind":"Name","value":"totalContributions"}}]}}]}}]} as unknown as DocumentNode<GetMemberSnapshotQuery, GetMemberSnapshotQueryVariables>;
export const GetChapterByKeyDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetChapterByKey"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"key"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"chapter"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"key"},"value":{"kind":"Variable","name":{"kind":"Name","value":"key"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"key"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"url"}}]}}]}}]} as unknown as DocumentNode<GetChapterByKeyQuery, GetChapterByKeyQueryVariables>;
export const GetProjectByKeyDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetProjectByKey"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"key"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"project"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"key"},"value":{"kind":"Variable","name":{"kind":"Name","value":"key"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"key"}},{"kind":"Field","name":{"kind":"Name","value":"level"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"url"}}]}}]}}]} as unknown as DocumentNode<GetProjectByKeyQuery, GetProjectByKeyQueryVariables>;