import * as Types from './graphql';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type ChapterMapFieldsFragment = { __typename: 'ChapterNode', key: string, name: string, geoLocation: { __typename: 'GeoLocationType', lat: number, lng: number } | null };

export type ChapterMetadataFieldsFragment = { __typename: 'ChapterNode', id: string, name: string, summary: string };

export type ChapterFieldsFragment = { __typename: 'ChapterNode', isActive: boolean, region: string, relatedUrls: Array<string>, suggestedLocation: string | null, updatedAt: number, url: string, id: string, name: string, summary: string, key: string, geoLocation: { __typename: 'GeoLocationType', lat: number, lng: number } | null };

export const ChapterFieldsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"ChapterFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"ChapterNode"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"ChapterMetadataFields"}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"ChapterMapFields"}},{"kind":"Field","name":{"kind":"Name","value":"isActive"}},{"kind":"Field","name":{"kind":"Name","value":"region"}},{"kind":"Field","name":{"kind":"Name","value":"relatedUrls"}},{"kind":"Field","name":{"kind":"Name","value":"suggestedLocation"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"url"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"ChapterMetadataFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"ChapterNode"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"summary"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"ChapterMapFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"ChapterNode"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"key"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"geoLocation"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"lat"}},{"kind":"Field","name":{"kind":"Name","value":"lng"}}]}}]}}]} as unknown as DocumentNode<ChapterFieldsFragment, unknown>;