FROM python:3.13-slim

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN groupadd owasp && \
    useradd --create-home --home-dir /home/owasp -g owasp owasp && \
    apt-get update && apt-get upgrade -y && \
    apt-get install -y gcc libpq-dev && \
    apt-get clean -y && rm -rf /var/lib/apt/lists/* && \
    python -m pip install --no-cache-dir poetry

ENV FORCE_COLOR=1
ENV PYTHONUNBUFFERED=1

WORKDIR /home/owasp

USER owasp

COPY poetry.lock pyproject.toml ./
RUN poetry install --no-root

COPY *.json ./
COPY tests tests
COPY utils utils
