FROM python:3.13.3-alpine AS builder

RUN addgroup -S owasp && \
    adduser -S -h /home/owasp -G owasp owasp && \
    mkdir -p /home/owasp && \
    chown owasp:owasp /home/owasp && \
    python -m pip install --no-cache-dir poetry

ENV FORCE_COLOR=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    PYTHONUNBUFFERED=1

WORKDIR /home/owasp
USER owasp

COPY --chmod=444 poetry.lock pyproject.toml ./
RUN poetry install --no-root

COPY .env.example .env.example
COPY apps apps
COPY manage.py wsgi.py ./
COPY settings settings
COPY static static
COPY templates templates
COPY tests tests

FROM python:3.13.3-alpine

RUN addgroup -S owasp && \
    adduser -S -h /home/owasp -G owasp owasp && \
    mkdir -p /home/owasp && \
    chown owasp:owasp /home/owasp

ENV FORCE_COLOR=1 \
    PATH="/home/owasp/.venv/bin:$PATH" \
    PYTHONUNBUFFERED=1

WORKDIR /home/owasp
USER owasp

COPY --from=builder --chmod=555 --chown=owasp:owasp /home/owasp /home/owasp
