FROM python:3.13.7-alpine AS builder

SHELL ["/bin/sh", "-o", "pipefail", "-c"]

ENV APK_CACHE_DIR="/home/owasp/.cache/apk-backend-builder" \
    APK_SYMLINK_DIR="/etc/apk/cache" \
    OWASP_GID=1000 \
    OWASP_UID=1000 \
    PIP_CACHE_DIR="/home/owasp/.cache/pip" \
    POETRY_CACHE_DIR="/home/owasp/.cache/pypoetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    PYTHONUNBUFFERED=1

RUN mkdir -p ${APK_CACHE_DIR} ${POETRY_CACHE_DIR} && \
    ln -fns ${APK_CACHE_DIR} ${APK_SYMLINK_DIR}

RUN --mount=type=cache,target=${APK_CACHE_DIR} \
    apk update && apk upgrade && \
    addgroup -S -g ${OWASP_GID} owasp && \
    adduser -S -h /home/owasp -u ${OWASP_UID} -G owasp owasp && \
    chown -R owasp:owasp /home/owasp

RUN --mount=type=cache,target=${PIP_CACHE_DIR} \
    python -m pip install poetry --cache-dir ${PIP_CACHE_DIR}

WORKDIR /home/owasp
USER owasp

# Copy Poetry configuration and install dependencies
COPY --chmod=444 poetry.lock pyproject.toml ./
RUN --mount=type=cache,target=${POETRY_CACHE_DIR},uid=${OWASP_UID},gid=${OWASP_GID} \
    poetry install --no-root

# Copy application files
COPY apps apps
COPY manage.py wsgi.py ./
COPY settings settings
COPY static static
COPY templates templates
COPY fuzz_tests fuzz_tests
COPY data data
COPY fuzz_tests/.env .env
COPY docker/entrypoint_fuzz.sh entrypoint.sh

FROM python:3.13.7-alpine

SHELL ["/bin/sh", "-o", "pipefail", "-c"]

# Install runtime dependencies
RUN addgroup -S owasp && \
    adduser -S -h /home/owasp -G owasp owasp && \
    mkdir -p /home/owasp && \
    chown owasp:owasp /home/owasp

ENV FORCE_COLOR=1 \
    PATH="/home/owasp/.venv/bin:$PATH" \
    PYTHONUNBUFFERED=1

WORKDIR /home/owasp
USER owasp

# Copy built application from the builder stage
COPY --from=builder --chmod=555 --chown=root:root /home/owasp /home/owasp

RUN touch /home/owasp/fuzz_tests.db && \
    chmod +x /home/owasp/fuzz_tests.db /home/owasp/entrypoint.sh


# Expose the running port
EXPOSE 8000

# Run fuzz tests

CMD ["/home/owasp/entrypoint.sh"]
