FROM python:3.13.3-alpine AS builder

ENV APK_CACHE_DIR="/home/owasp/.cache/apk" \
    APK_GH_CACHE_DIR="/home/owasp/gh/apk-cache" \
    APK_SYMLINK_DIR="/etc/apk/cache" \
    OWASP_GID=1000 \
    OWASP_UID=1000 \
    PIP_CACHE_DIR="/home/owasp/.cache/pip" \
    PIP_GH_CACHE_DIR="/home/owasp/gh/pip-cache" \
    POETRY_CACHE_DIR="/home/owasp/.cache/pypoetry" \
    POETRY_GH_CACHE_DIR="/home/owasp/gh/poetry-cache" \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    PYTHONUNBUFFERED=1

RUN mkdir -p ${APK_CACHE_DIR} ${APK_SYMLINK_DIR} ${APK_GH_CACHE_DIR} \
    ${PIP_GH_CACHE_DIR} ${POETRY_GH_CACHE_DIR} && \
    ln -s ${APK_CACHE_DIR} ${APK_SYMLINK_DIR}

RUN --mount=type=cache,target=${APK_CACHE_DIR} \
    apk update && apk upgrade && \
    addgroup -S -g ${OWASP_GID} owasp && \
    adduser -S -h /home/owasp -u ${OWASP_UID} -G owasp owasp && \
    chown -R owasp:owasp /home/owasp && \
    cp -r ${APK_CACHE_DIR} ${APK_GH_CACHE_DIR}

RUN --mount=type=cache,target=${PIP_CACHE_DIR} \
    python -m pip install poetry --cache-dir ${PIP_CACHE_DIR} && \
    cp -r ${PIP_CACHE_DIR} ${PIP_GH_CACHE_DIR}

WORKDIR /home/owasp
USER owasp

COPY --chmod=444 poetry.lock pyproject.toml ./

RUN --mount=type=cache,target=${POETRY_CACHE_DIR},uid=${OWASP_UID},gid=${OWASP_GID} \
    poetry install --no-root && \
    cp -r ${POETRY_CACHE_DIR} ${POETRY_GH_CACHE_DIR}

COPY .env.example .env.example
COPY apps apps
COPY manage.py wsgi.py ./
COPY settings settings
COPY static static
COPY templates templates
COPY tests tests

FROM python:3.13.3-alpine

RUN addgroup -S owasp && \
    adduser -S -h /home/owasp -G owasp owasp && \
    mkdir -p /home/owasp && \
    chown owasp:owasp /home/owasp

ENV FORCE_COLOR=1 \
    PATH="/home/owasp/.venv/bin:$PATH" \
    PYTHONUNBUFFERED=1

WORKDIR /home/owasp
USER owasp

COPY --from=builder --chmod=555 --chown=owasp:owasp /home/owasp /home/owasp
