#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_LIVE_DIR="$(cd "$SCRIPT_DIR/../live" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../" && pwd)"

ENV_FILE="$SCRIPT_DIR/../.env"

if [[ -f "$ENV_FILE" ]]; then
    set -a && source "$ENV_FILE" && set +a
fi

for cmd in localstack jq openssl tflocal awslocal docker; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "ERROR: '$cmd' not found. See infrastructure/README.md prerequisites." >&2
        exit 1
    fi
done

if ! localstack wait -t 60 2>/dev/null; then
    echo "ERROR: LocalStack is not running or not ready." >&2
    echo "Start it in another terminal with: make start-localstack" >&2
    exit 1
fi

GIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || true)
TIMESTAMP=$(date +%Y%m%d%H%M%S)

if [[ -n "$GIT_SHA" ]]; then
    TAG="${GIT_SHA}-${TIMESTAMP}"
else
    TAG="${TIMESTAMP}"
fi

echo "Using image tag: $TAG"

ENVIRONMENT="${ENVIRONMENT:-local}"
DJANGO_CONFIGURATION="${DJANGO_CONFIGURATION:-Local}"
DJANGO_SETTINGS_MODULE="${DJANGO_SETTINGS_MODULE:-settings.local}"
DOMAIN_NAME="${DOMAIN_NAME:-localhost}"
ENABLE_CRON_TASKS="${ENABLE_CRON_TASKS:-false}"

if [[ -z "${DB_PASSWORD:-}" ]]; then
    DB_PASSWORD=$(openssl rand -base64 24)
    echo "" >> "$ENV_FILE"
    echo "# Generated by provision-infra.sh on $(date)" >> "$ENV_FILE"
    echo "DB_PASSWORD=$DB_PASSWORD" >> "$ENV_FILE"
    echo "Generated DB_PASSWORD and saved to $ENV_FILE"
fi

TFVARS_JSON=$(mktemp /tmp/nest-tfvars-XXXXXX.json)
trap 'rm -f "$TFVARS_JSON"' EXIT

_normalize_bool() {
    local raw="$1"
    local val="${raw//\"/}"
    case "$val" in
        [Tt]rue)  echo true ;;
        [Ff]alse) echo false ;;
        *) echo "ERROR: Boolean must be 'true' or 'false', got '$raw'." >&2; exit 1 ;;
    esac
}

jq -n \
    --arg environment "$ENVIRONMENT" \
    --arg backend_image_tag "$TAG" \
    --arg frontend_image_tag "$TAG" \
    --arg django_configuration "$DJANGO_CONFIGURATION" \
    --arg django_settings_module "$DJANGO_SETTINGS_MODULE" \
    --arg domain_name "$DOMAIN_NAME" \
    --argjson enable_cron_tasks "$(_normalize_bool "${ENABLE_CRON_TASKS:-false}")" \
    --argjson force_new_deployment "$(_normalize_bool "${FORCE_NEW_DEPLOYMENT:-true}")" \
    --arg db_password "$DB_PASSWORD" \
    --argjson db_deletion_protection false \
    --argjson db_skip_final_snapshot true \
    --argjson enable_nat_gateway false \
    '$ARGS.named' > "$TFVARS_JSON"

cd "$INFRA_LIVE_DIR"

echo "Initializing Terraform with tflocal..."
tflocal init --reconfigure

echo "Applying Terraform..."
tflocal apply -auto-approve -var-file="$TFVARS_JSON"

echo "Retrieving ECR repository URLs..."
BACKEND_ECR=$(tflocal output -raw backend_ecr_repository_url)
FRONTEND_ECR=$(tflocal output -raw frontend_ecr_repository_url)

export AWS_DEFAULT_REGION=us-east-2

REGISTRY="$(echo "$BACKEND_ECR" | cut -d/ -f1)"
echo "Logging into local ECR at $REGISTRY..."
awslocal ecr get-login-password | docker login --username AWS --password-stdin "$REGISTRY"

echo "Building backend image..."
docker build \
    --target backend \
    -f "$REPO_ROOT/docker/backend/Dockerfile" \
    -t "$BACKEND_ECR:$TAG" \
    "$REPO_ROOT/backend"

echo "Pushing backend image to local ECR..."
docker push "$BACKEND_ECR:$TAG"

FRONTEND_ENV_FILE="frontend/.env"
if [[ ! -f "$REPO_ROOT/$FRONTEND_ENV_FILE" ]]; then
    echo "WARNING: $FRONTEND_ENV_FILE not found, using frontend/.env.example." >&2
    FRONTEND_ENV_FILE="frontend/.env.example"
fi

echo "Building frontend image..."
docker build \
    -f "$REPO_ROOT/docker/frontend/Dockerfile" \
    --build-arg "ENV_FILE=${FRONTEND_ENV_FILE#frontend/}" \
    --build-arg "FORCE_STANDALONE=yes" \
    -t "$FRONTEND_ECR:$TAG" \
    "$REPO_ROOT/frontend"

echo "Pushing frontend image to local ECR..."
docker push "$FRONTEND_ECR:$TAG"

echo "Provisioning complete."
echo "  Tag:              $TAG"
echo "  Backend ECR:      $BACKEND_ECR:$TAG"
echo "  Frontend ECR:     $FRONTEND_ECR:$TAG"
echo "  Django config:    $DJANGO_CONFIGURATION"
echo "  Domain:           $DOMAIN_NAME"
