"""Provision local infrastructure on LocalStack using Terraform."""

from __future__ import annotations

import base64
import datetime
import json
import logging
import os
import secrets
from datetime import UTC
from pathlib import Path

from scripts.aws import aws_client
from scripts.commands import CommandRunner
from scripts.errors import CommandNotFoundError, InfrastructureError
from scripts.localstack import LocalStack

logger = logging.getLogger(__name__)

TFLOCAL = "tflocal"
DOCKER = "docker"

OVERRIDE_FILE = "localstack_providers_override.tf"
FIXTURES_OBJECT_KEY = "nest.dump"
BACKEND_BUILD_TARGET = "backend"
FRONTEND_BUILD_ARGS = ("ENV_FILE=.env.localstack", "FORCE_STANDALONE=yes")


def _bool(value: str) -> bool:
    """Normalize a string to a boolean.

    Args:
        value (str): The raw boolean string.

    Returns:
        bool: The normalized boolean.

    Raises:
        InfrastructureError: If the value is not a valid boolean.

    """
    normalized = value.strip().strip('"').lower()
    if normalized == "true":
        return True
    if normalized == "false":
        return False
    message = f"Boolean must be 'true' or 'false', got '{value}'."
    raise InfrastructureError(message)


class ProvisionInfra:
    """Create resources on LocalStack and push Docker images."""

    def __init__(
        self,
        commands: CommandRunner | None = None,
        *,
        localstack: LocalStack | None = None,
    ) -> None:
        """Initialize the provisioner.

        Args:
            commands (CommandRunner, optional): Command runner instance.
            localstack (LocalStack, optional): LocalStack manager instance.

        """
        self.root_dir = Path(__file__).resolve().parent.parent.parent
        self.infra_dir = self.root_dir / "infrastructure"
        self.live_dir = self.infra_dir / "live"
        self.env_path = self.infra_dir / ".env"
        self.commands = commands or CommandRunner()
        self.localstack = localstack or LocalStack(self.commands)

    def run(self) -> None:
        """Provision resources on LocalStack and push the backend/frontend images.

        Raises:
            CommandNotFoundError: If a required executable is missing.
            InfrastructureError: If provisioning fails.

        """
        self.commands.require(TFLOCAL)
        self.commands.require(DOCKER)

        logger.info("Waiting for LocalStack to become ready...")
        self.localstack.wait_ready()

        tag = self._image_tag()
        logger.info("Using image tag: %s", tag)

        db_password = self._db_password()

        self._remove_stale_override()
        self._terraform_init()
        self._terraform_apply(self.tfvars(tag, db_password))
        outputs = self._terraform_outputs()
        self._upload_fixtures(outputs["fixtures_bucket_name"])
        self._push_images(
            outputs["backend_ecr_repository_url"],
            outputs["frontend_ecr_repository_url"],
            tag,
        )
        self._log_summary(outputs, tag)

    def _image_tag(self) -> str:
        """Return the image tag derived from the git SHA and a timestamp."""
        try:
            result = self.commands.run(
                "git",
                "rev-parse",
                "--short",
                "HEAD",
                capture_output=True,
                check=False,
            )
        except CommandNotFoundError:
            result = None
        git_sha = result.stdout.strip() if result is not None and result.returncode == 0 else ""
        timestamp = datetime.datetime.now(UTC).strftime("%Y%m%d%H%M%S")
        return f"{git_sha}-{timestamp}" if git_sha else timestamp

    def _db_password(self) -> str:
        """Return the DB password, generating and persisting it if not set."""
        password = os.environ.get("DB_PASSWORD")
        if password:
            return password

        password = secrets.token_urlsafe(24)
        header = (
            f"\n# Generated by provision-infra.py on {datetime.datetime.now(UTC)}\n"
            f"DB_PASSWORD={password}\n"
        )
        self.env_path.parent.mkdir(parents=True, exist_ok=True)
        self.env_path.touch(exist_ok=True)
        with self.env_path.open("a", encoding="utf-8") as handle:
            handle.write(header)
        logger.info("Generated DB_PASSWORD and saved to %s", self.env_path)
        return password

    def tfvars(self, tag: str, db_password: str) -> dict:
        """Return the Terraform variables for the local environment.

        Args:
            tag (str): The image tag for the backend and frontend images.
            db_password (str): The database password.

        Returns:
            dict: The Terraform variables.

        """
        env = os.environ
        return {
            "environment": env.get("ENVIRONMENT", "local"),
            "backend_image_tag": tag,
            "frontend_image_tag": tag,
            # The images are pushed after ``terraform apply``, and the SSM runtime
            # parameters are only fixed by ``deploy-services``. Creating the services
            # with zero desired tasks avoids LocalStack firing a task at apply time
            # that cannot find its image yet; ``deploy-services`` scales them up.
            "backend_desired_count": 0,
            "frontend_desired_count": 0,
            "django_configuration": env.get("DJANGO_CONFIGURATION", "Local"),
            "django_settings_module": env.get("DJANGO_SETTINGS_MODULE", "settings.local"),
            "domain_name": env.get("DOMAIN_NAME", "localhost"),
            "enable_cron_tasks": _bool(env.get("ENABLE_CRON_TASKS", "false")),
            "force_new_deployment": _bool(env.get("FORCE_NEW_DEPLOYMENT", "true")),
            "db_password": db_password,
            "db_deletion_protection": False,
            "db_skip_final_snapshot": True,
            "enable_nat_gateway": False,
            "django_redis_use_tls": False,
            "django_redis_auth_enabled": False,
        }

    def _tf_env(self, tfvars: dict) -> dict[str, str]:
        """Render Terraform variables as ``TF_VAR_*`` environment entries.

        Args:
            tfvars (dict): The Terraform variables.

        Returns:
            dict[str, str]: A ``TF_VAR_<name>`` to rendered value mapping.

        """
        return {
            f"TF_VAR_{name}": json.dumps(value) if isinstance(value, bool) else str(value)
            for name, value in tfvars.items()
        }

    def _remove_stale_override(self) -> None:
        """Remove a stale provider override file from a previous run."""
        path = self.live_dir / OVERRIDE_FILE
        if path.exists():
            logger.info("Removing stale %s from previous run...", OVERRIDE_FILE)
            path.unlink()

    def _terraform_init(self) -> None:
        """Initialize Terraform with tflocal."""
        logger.info("Initializing Terraform with tflocal...")
        self.commands.run(TFLOCAL, "init", "--reconfigure", cwd=self.live_dir, check=True)

    def _terraform_apply(self, tfvars: dict) -> None:
        """Apply the Terraform configuration.

        Args:
            tfvars (dict): The Terraform variables.

        """
        logger.info("Applying Terraform...")
        self.commands.run(
            TFLOCAL,
            "apply",
            "-auto-approve",
            cwd=self.live_dir,
            env=self._tf_env(tfvars),
            check=True,
        )

    def _terraform_outputs(self) -> dict:
        """Return the Terraform outputs as a dict.

        Returns:
            dict: A mapping of output name to its value.

        Raises:
            InfrastructureError: If the outputs cannot be parsed.

        """
        result = self.commands.run(
            TFLOCAL,
            "output",
            "-json",
            cwd=self.live_dir,
            capture_output=True,
            check=True,
        )
        try:
            raw = json.loads(result.stdout)
        except json.JSONDecodeError as exc:
            message = "Failed to parse 'tflocal output -json'."
            raise InfrastructureError(message) from exc
        return {name: entry["value"] for name, entry in raw.items()}

    def _upload_fixtures(self, bucket: str) -> None:
        """Upload the nest dump to the fixtures bucket.

        Args:
            bucket (str): The fixtures bucket name.

        """
        dump_path = self.root_dir / "backend" / "data" / FIXTURES_OBJECT_KEY
        if not dump_path.exists():
            logger.info("Downloading %s from public S3...", FIXTURES_OBJECT_KEY)
            self._fetch_nest_dump()

        logger.info("Uploading %s to fixtures bucket...", FIXTURES_OBJECT_KEY)
        s3 = aws_client("s3", localstack=self.localstack)
        s3.upload_file(str(dump_path), bucket, FIXTURES_OBJECT_KEY)

    def _fetch_nest_dump(self) -> None:
        """Fetch the nest dump using the backend fetch script."""
        self.commands.run(
            DOCKER,
            "compose",
            "-f",
            "docker-compose/e2e/compose.yaml",
            "run",
            "--no-deps",
            "--rm",
            "backend",
            "python",
            "-m",
            "scripts.fetch_nest_dump",
            cwd=self.root_dir,
            check=True,
        )

    def _push_images(self, backend_ecr: str, frontend_ecr: str, tag: str) -> None:
        """Log into local ECR and push the backend/frontend images.

        Args:
            backend_ecr (str): The backend ECR repository URL.
            frontend_ecr (str): The frontend ECR repository URL.
            tag (str): The image tag.

        """
        registry = backend_ecr.partition("/")[0]
        logger.info("Logging into local ECR at %s...", registry)
        self._docker_login(registry)
        self._build_backend_image(backend_ecr, tag)
        self._build_frontend_image(frontend_ecr, tag)

    def _docker_login(self, registry: str) -> None:
        """Log into the local ECR registry using the authorization token.

        Args:
            registry (str): The ECR registry host.

        """
        ecr = aws_client("ecr", localstack=self.localstack)
        token = ecr.get_authorization_token()["authorizationData"][0]["authorizationToken"]
        password = base64.b64decode(token).decode("utf-8").removeprefix("AWS:")
        self.commands.run(
            DOCKER,
            "login",
            "--username",
            "AWS",
            "--password-stdin",
            registry,
            input_data=password,
            check=True,
        )

    def _build_backend_image(self, backend_ecr: str, tag: str) -> None:
        """Build and push the backend image.

        Args:
            backend_ecr (str): The backend ECR repository URL.
            tag (str): The image tag.

        """
        image_ref = f"{backend_ecr}:{tag}"
        logger.info("Building backend image...")
        self.commands.run(
            DOCKER,
            "build",
            "--target",
            BACKEND_BUILD_TARGET,
            "-f",
            str(self.root_dir / "docker" / "backend" / "Dockerfile"),
            "-t",
            image_ref,
            str(self.root_dir / "backend"),
            check=True,
        )
        logger.info("Pushing backend image to local ECR...")
        self.commands.run(DOCKER, "push", image_ref, check=True)

    def _build_frontend_image(self, frontend_ecr: str, tag: str) -> None:
        """Build and push the frontend image.

        Args:
            frontend_ecr (str): The frontend ECR repository URL.
            tag (str): The image tag.

        """
        image_ref = f"{frontend_ecr}:{tag}"
        logger.info("Building frontend image...")
        self.commands.run(
            DOCKER,
            "build",
            "-f",
            str(self.root_dir / "docker" / "frontend" / "Dockerfile"),
            "--build-arg",
            FRONTEND_BUILD_ARGS[0],
            "--build-arg",
            FRONTEND_BUILD_ARGS[1],
            "-t",
            image_ref,
            str(self.root_dir / "frontend"),
            check=True,
        )
        logger.info("Pushing frontend image to local ECR...")
        self.commands.run(DOCKER, "push", image_ref, check=True)

    def _log_summary(self, outputs: dict, tag: str) -> None:
        """Log a summary of the provisioning run.

        Args:
            outputs (dict): The Terraform outputs.
            tag (str): The image tag.

        """
        logger.info("Provisioning complete.")
        logger.info("  Tag:              %s", tag)
        logger.info("  Backend ECR:      %s:%s", outputs["backend_ecr_repository_url"], tag)
        logger.info("  Frontend ECR:     %s:%s", outputs["frontend_ecr_repository_url"], tag)
        logger.info("  Django config:    %s", os.environ.get("DJANGO_CONFIGURATION", "Local"))
        logger.info("  Domain:           %s", os.environ.get("DOMAIN_NAME", "localhost"))
