'use client'
import { faGithub } from '@fortawesome/free-brands-svg-icons'
import { useSearchPage } from 'hooks/useSearchPage'
import React, { useState } from 'react'

import FontAwesomeIconWrapper from 'wrappers/FontAwesomeIconWrapper'
import type { Issue } from 'types/issue'
import { getFilteredIcons } from 'utils/utility'

import Card from 'components/Card'
import DialogComp from 'components/Modal'
import PageLayout from 'components/PageLayout'
import SearchPageLayout from 'components/SearchPageLayout'

const ContributePage = () => {
  const {
    items: issues,
    isLoaded,
    currentPage,
    totalPages,
    searchQuery,
    handleSearch,
    handlePageChange,
  } = useSearchPage<Issue>({
    indexName: 'issues',
    pageTitle: 'OWASP Issues',
  })

  const [modalOpenIndex, setModalOpenIndex] = useState<number | null>(null)

  const renderContributeCard = (issue: Issue, index: number) => {
    const params: string[] = ['createdAt', 'commentsCount']
    const filteredIcons = getFilteredIcons(issue, params)

    const SubmitButton = {
      label: 'Read More',
      icon: <FontAwesomeIconWrapper icon="fa-solid fa-wand-magic-sparkles" />,
      onclick: () => setModalOpenIndex(index),
    }

    const viewIssueButton = {
      label: 'View Issue',
      icon: <FontAwesomeIconWrapper icon={faGithub} />,
      url: issue.url,
    }

    return (
      <React.Fragment key={issue.objectID}>
        <Card
          key={issue.objectID}
          title={issue.title}
          url={issue.url}
          projectName={issue.projectName}
          projectLink={issue.projectUrl}
          summary={issue.summary}
          icons={filteredIcons}
          button={SubmitButton}
        />
        <DialogComp
          key={`modal-${index}`}
          isOpen={modalOpenIndex === index}
          onClose={() => setModalOpenIndex(null)}
          title={issue.title}
          summary={issue.summary}
          hint={issue.hint}
          button={viewIssueButton}
          description="The issue summary and the recommended steps to address it have been generated by AI"
        ></DialogComp>
      </React.Fragment>
    )
  }

  return (
    <PageLayout>
      <SearchPageLayout
        currentPage={currentPage}
        empty="No issues found"
        indexName="issues"
        isLoaded={isLoaded}
        onPageChange={handlePageChange}
        onSearch={handleSearch}
        searchPlaceholder="Search for issues..."
        searchQuery={searchQuery}
        totalPages={totalPages}
      >
        {issues && issues.map(renderContributeCard)}
      </SearchPageLayout>
    </PageLayout>
  )
}

export default ContributePage
