'use client'
import { useSearchPage } from 'hooks/useSearchPage'
import React, { useState } from 'react'
import { FaGithub, FaWandMagicSparkles } from 'react-icons/fa6'
import type { Issue } from 'types/issue'
import { getFilteredIcons } from 'utils/utility'
import Card from 'components/Card'
import DialogComp from 'components/Modal'
import SearchPageLayout from 'components/SearchPageLayout'

const ContributePage = () => {
  const {
    items: issues,
    isLoaded,
    currentPage,
    totalPages,
    searchQuery,
    handleSearch,
    handlePageChange,
  } = useSearchPage<Issue>({
    indexName: 'issues',
    pageTitle: 'OWASP Issues',
  })

  const [modalOpenIndex, setModalOpenIndex] = useState<number | null>(null)

  const renderContributeCard = (issue: Issue, index: number) => {
    const params: string[] = ['createdAt', 'commentsCount']
    const filteredIcons = getFilteredIcons(issue, params)

    const SubmitButton = {
      label: 'Read More',
      icon: <FaWandMagicSparkles className="h-4 w-4" />,
      onclick: () => setModalOpenIndex(index),
    }

    const viewIssueButton = {
      label: 'View Issue',
      icon: <FaGithub className="h-4 w-4" />,
      url: issue.url,
    }

    return (
      <React.Fragment key={issue.objectID}>
        <Card
          key={issue.objectID}
          cardKey={issue.objectID}
          title={issue.title}
          url={issue.url}
          projectName={issue.projectName}
          projectLink={issue.projectUrl}
          summary={issue.summary}
          icons={filteredIcons}
          button={SubmitButton}
          labels={issue.labels}
        />
        <DialogComp
          key={`modal-${issue.objectID}`}
          isOpen={modalOpenIndex === index}
          onClose={() => setModalOpenIndex(null)}
          title={issue.title}
          summary={issue.summary}
          hint={issue.hint}
          button={viewIssueButton}
          description="The issue summary and the recommended steps to address it have been generated by AI"
        ></DialogComp>
      </React.Fragment>
    )
  }

  return (
    <SearchPageLayout
      currentPage={currentPage}
      empty="No issues found"
      indexName="issues"
      isLoaded={isLoaded}
      onPageChange={handlePageChange}
      onSearch={handleSearch}
      searchPlaceholder="Search for issues..."
      searchQuery={searchQuery}
      totalPages={totalPages}
    >
      {issues?.map(renderContributeCard)}
    </SearchPageLayout>
  )
}

export default ContributePage
