# Generated by Django 5.1.5 on 2025-03-16 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("github", "0016_user_is_bot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[("EUR", "Euro"), ("USD", "US Dollar")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.FloatField()),
                ("slack_user_id", models.CharField(max_length=100)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsorships",
                        to="github.issue",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sponsorships",
                "db_table": "nest_sponsorships",
            },
        ),
    ]
