# Generated by Django 5.2.3 on 2025-06-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('contributor', 'Contributor'), ('mentor', 'Mentor')], default='contributor', max_length=20, verbose_name='User Role'),
        ),
    ]
