# Generated by Django 5.2.5 on 2025-08-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0033_alter_release_published_at"),
        ("nest", "0002_apikey"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Badge type name (e.g., 'WASPY Award Winner')",
                        max_length=100,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of what this badge represents",
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="🏆",
                        help_text="Icon class or emoji for the badge",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="#FFD700",
                        help_text="Badge color (hex code or CSS color name)",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this badge type is currently active",
                        verbose_name="Is Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge Type",
                "verbose_name_plural": "Badge Types",
                "db_table": "nest_badge_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "earned_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the badge was earned",
                        verbose_name="Earned At",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reason or context for earning this badge",
                        verbose_name="Reason",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the badge (e.g., award details)",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "badge_type",
                    models.ForeignKey(
                        help_text="The type of badge earned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to="nest.badgetype",
                        verbose_name="Badge Type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who earned this badge",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="github.user",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Badge",
                "verbose_name_plural": "User Badges",
                "db_table": "nest_user_badges",
                "ordering": ["-earned_at"],
                "indexes": [
                    models.Index(fields=["user"], name="nest_user_badge_user_idx"),
                    models.Index(fields=["badge_type"], name="nest_user_badge_type_idx"),
                    models.Index(fields=["earned_at"], name="nest_user_badge_earned_at_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "badge_type"), name="unique_user_badge_type"
                    )
                ],
            },
        ),
    ]
