# Generated by Django 5.2.4 on 2025-08-20 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0003_badge"),
        ("slack", "0023_delete_googleauth"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberGoogleCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("access_token", models.BinaryField(null=True, verbose_name="Access Token")),
                ("refresh_token", models.BinaryField(null=True, verbose_name="Refresh Token")),
                ("expires_at", models.DateTimeField(null=True, verbose_name="Token Expiry")),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_auth",
                        to="slack.member",
                        verbose_name="Slack Member",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Google Auths",
                "db_table": "slack_google_auths",
            },
        ),
    ]
