# Generated by Django 5.2.5 on 2025-08-27 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0034_merge_20250804_1817"),
        ("nest", "0004_userbadge_user_badges"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userbadge",
            options={"verbose_name_plural": "User badges"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="badges",
        ),
        migrations.RemoveField(
            model_name="userbadge",
            name="awarded_at",
        ),
        migrations.RemoveField(
            model_name="userbadge",
            name="awarded_by",
        ),
        migrations.RemoveField(
            model_name="userbadge",
            name="notes",
        ),
        migrations.AlterField(
            model_name="userbadge",
            name="badge",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="nest.badge"),
        ),
        migrations.AlterField(
            model_name="userbadge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="GithubUserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nest.badge"
                    ),
                ),
                (
                    "github_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="github.user"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "GitHub user badges",
                "db_table": "nest_github_user_badges",
                "unique_together": {("github_user", "badge")},
            },
        ),
    ]
