# Generated by Django 5.2.5 on 2025-08-18 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0004_userbadge"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userbadge",
            name="uq_userbadge_user_badge",
        ),
    ]
