# Generated by Django 5.2.4 on 2025-08-22 05:35

import django.db.models.deletion
from django.db import migrations, models

import apps.common.model_fields


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0004_googleaccountauthorization"),
        ("slack", "0018_conversation_sync_messages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="googleaccountauthorization",
            old_name="scopes",
            new_name="scope",
        ),
        migrations.AlterField(
            model_name="googleaccountauthorization",
            name="access_token",
            field=apps.common.model_fields.KmsEncryptedField(verbose_name="Access Token"),
        ),
        migrations.AlterField(
            model_name="googleaccountauthorization",
            name="expires_at",
            field=models.DateTimeField(verbose_name="Token Expiry"),
        ),
        migrations.AlterField(
            model_name="googleaccountauthorization",
            name="member",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_account_authorization",
                to="slack.member",
                verbose_name="Slack Member",
            ),
        ),
        migrations.AlterField(
            model_name="googleaccountauthorization",
            name="refresh_token",
            field=apps.common.model_fields.KmsEncryptedField(verbose_name="Refresh Token"),
        ),
        migrations.AlterModelTable(
            name="googleaccountauthorization",
            table="nest_google_account_authorizations",
        ),
    ]
