# Generated by Django 5.2.4 on 2025-08-20 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0004_membergooglecredentials"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membergooglecredentials",
            options={"verbose_name_plural": "Member's Google Credentials"},
        ),
        migrations.AlterModelTable(
            name="membergooglecredentials",
            table="nest_member_google_credentials",
        ),
    ]
