# Generated by Django 5.2.5 on 2025-09-06 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0035_alter_user_bio_alter_user_is_owasp_staff"),
        ("nest", "0004_userbadge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbadge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_badges",
                to="github.user",
                verbose_name="User",
            ),
        ),
    ]
