# Generated by Django 5.2.4 on 2025-08-20 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0005_alter_membergooglecredentials_options_and_more"),
        ("slack", "0023_delete_googleauth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membergooglecredentials",
            name="member",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_google_credentials",
                to="slack.member",
                verbose_name="Slack Member",
            ),
        ),
    ]
