# Generated by Django 5.2.5 on 2025-09-09 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0005_alter_userbadge_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApiKey",
        ),
    ]
