# Generated by Django 5.2.5 on 2025-08-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0035_alter_user_bio_alter_user_is_owasp_staff"),
        ("nest", "0005_remove_userbadge_uq_userbadge_user_badge"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userbadge",
            constraint=models.UniqueConstraint(
                fields=("user", "badge"), name="uq_userbadge_user_badge"
            ),
        ),
    ]
