# Generated by Django 5.2.4 on 2025-08-30 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0004_userbadge"),
        ("nest", "0005_rename_scopes_googleaccountauthorization_scope_and_more"),
    ]

    operations = []
