# Generated by Django 5.2.5 on 2025-08-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0006_userbadge_uq_userbadge_user_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbadge',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the badge assignment is active.', verbose_name='Is active'),
        ),
    ]
