# Generated by Django 5.2.4 on 2025-08-20 20:26

from django.db import migrations

import apps.common.model_fields


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0006_alter_membergooglecredentials_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membergooglecredentials",
            name="access_token",
            field=apps.common.model_fields.KmsEncryptedField(
                null=True, verbose_name="Access Token"
            ),
        ),
        migrations.AlterField(
            model_name="membergooglecredentials",
            name="refresh_token",
            field=apps.common.model_fields.KmsEncryptedField(
                null=True, verbose_name="Refresh Token"
            ),
        ),
    ]
