# Generated by Django 5.2.4 on 2025-08-30 03:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0006_merge_20250830_0323"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="googleaccountauthorization",
            options={"verbose_name_plural": "Google Account Authorizations"},
        ),
        migrations.AlterField(
            model_name="googleaccountauthorization",
            name="scope",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
                verbose_name="OAuth Scopes",
            ),
        ),
    ]
