# Generated by Django 5.2.4 on 2025-09-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0007_alter_googleaccountauthorization_options_and_more"),
        ("slack", "0018_conversation_sync_messages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(default="", max_length=15, verbose_name="Channel ID"),
                ),
                ("message", models.TextField(verbose_name="Reminder Message")),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders",
                        to="slack.member",
                        verbose_name="Slack Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nest Reminder",
                "verbose_name_plural": "Nest Reminders",
                "db_table": "nest_reminders",
            },
        ),
        migrations.CreateModel(
            name="ReminderSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scheduled_time", models.DateTimeField(verbose_name="Scheduled Time")),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("once", "Once"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="once",
                        max_length=50,
                        verbose_name="Recurrence",
                    ),
                ),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="nest.reminder",
                        verbose_name="Nest Reminder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nest Reminder Schedule",
                "verbose_name_plural": "Nest Reminder Schedules",
                "db_table": "nest_reminder_schedules",
            },
        ),
    ]
