# Generated by Django 5.2.4 on 2025-08-21 12:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import apps.common.model_fields


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0007_alter_membergooglecredentials_access_token_and_more"),
        ("slack", "0023_delete_googleauth"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAccountAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "access_token",
                    apps.common.model_fields.KmsEncryptedField(
                        null=True, verbose_name="Access Token"
                    ),
                ),
                (
                    "refresh_token",
                    apps.common.model_fields.KmsEncryptedField(
                        null=True, verbose_name="Refresh Token"
                    ),
                ),
                ("expires_at", models.DateTimeField(null=True, verbose_name="Token Expiry")),
                (
                    "scopes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_account_authorization",
                        to="slack.member",
                        verbose_name="Slack Member",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Google Accounts Authorizations",
                "db_table": "nest_google_accounts_authorizations",
            },
        ),
        migrations.DeleteModel(
            name="MemberGoogleCredentials",
        ),
    ]
