# Generated by Django 5.2.7 on 2025-10-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0007_alter_badge_css_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="css_class",
            field=models.CharField(
                choices=[
                    ("award", "Award"),
                    ("bug_slash", "Bug Slash"),
                    ("certificate", "Certificate"),
                    ("medal", "Medal"),
                    ("ribbon", "Ribbon"),
                    ("star", "Star"),
                ],
                default="medal",
                max_length=255,
                verbose_name="CSS Class",
            ),
        ),
    ]
