# Generated by Django 5.2.4 on 2025-09-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0008_reminder_reminderschedule"),
        ("owasp", "0052_remove_event_calendar_id_event_google_calendar_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reminders",
                to="owasp.event",
                verbose_name="Event",
            ),
        ),
    ]
