# Generated by Django 5.2.4 on 2025-09-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0009_reminder_event"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reminderschedule",
            constraint=models.UniqueConstraint(
                fields=("reminder", "scheduled_time"), name="unique_reminder_schedule"
            ),
        ),
    ]
