# Generated by Django 5.2.4 on 2025-09-08 05:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0005_alter_userbadge_user"),
        ("nest", "0010_reminderschedule_unique_reminder_schedule"),
    ]

    operations = []
