# Generated by Django 5.2.6 on 2025-09-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0011_merge_20250908_0548"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminderschedule",
            name="job_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the scheduled job in the task queue.",
                max_length=255,
                verbose_name="Job ID",
            ),
        ),
    ]
