# Generated by Django 5.2.6 on 2025-09-15 04:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0006_delete_apikey"),
        ("nest", "0012_reminderschedule_job_id"),
    ]

    operations = []
