# Generated by Django 5.2.6 on 2025-10-08 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0013_merge_0006_delete_apikey_0012_reminderschedule_job_id"),
        ("owasp", "0055_merge_20251008_1253"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="channel_id",
        ),
        migrations.AddField(
            model_name="reminder",
            name="entity_channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="owasp.entitychannel",
                verbose_name="Channel",
            ),
        ),
    ]
