# Generated by Django 5.2.6 on 2025-10-09 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nest", "0014_remove_reminder_channel_id_reminder_entity_channel"),
        ("owasp", "0055_merge_20251008_1253"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="entity_channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="owasp.entitychannel",
                verbose_name="Channel",
            ),
        ),
    ]
