[build-system]
build-backend = "poetry.core.masonry.api"
requires = [ "poetry-core" ]

[tool.poetry]
name = "owasp-nest-infrastructure"
version = "0.1.0"
description = "OWASP Nest infrastructure tooling"
license = "MIT"
authors = [ "Arkadii Yakovets <arkadii.yakovets@owasp.org>" ]
packages = [ { include = "scripts" } ]
dependencies.python = "^3.13"
dependencies.awscli-local = "0.22.2"
dependencies.docker = "7.2.0"
dependencies.terraform-local = "0.26.0"
group.test.dependencies.pytest = "9.0.3"

[tool.pytest]
ini_options.testpaths = [ "tests" ]
