"""Nest app views."""

from django.conf import settings
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.views.decorators.http import require_GET

from apps.nest.models.google_account_authorization import GoogleAccountAuthorization


@require_GET
def google_auth_callback(request):
    """Handle Google OAuth callback.

    Args:
        request (HttpRequest): The HTTP request object from Google.

    Returns:
        HttpResponse: The response generated by the Google OAuth flow.

    """
    # Handle the Google OAuth callback logic here
    auth_response = request.build_absolute_uri()
    # Google OAuth will raise an error if the redirect URI protocol is http,
    # so we need to ensure it's https in the local environment
    if settings.IS_LOCAL_ENVIRONMENT:
        auth_response = auth_response.replace("http://", "https://")  # NOSONAR
    try:
        GoogleAccountAuthorization.authorize_callback(auth_response)
    except (ValueError, ValidationError):
        return HttpResponse("Error during Google sign-in", status=400)
    return HttpResponse(
        "You are successfully signed in with Google.<br>You can now close the page.", status=200
    )
