ARG OWASP_GID=1000
ARG OWASP_UID=1000

FROM python:3.13.15-alpine3.23@sha256:75f27d686432419c9d42420b2b9ef605868c7a0682a6be10a6601fad46c2df01 AS builder

ARG OWASP_GID
ARG OWASP_UID

SHELL ["/bin/sh", "-o", "pipefail", "-c"]

ENV APK_CACHE_DIR="/home/owasp/.cache/apk-docs-test" \
    APK_SYMLINK_DIR="/etc/apk/cache" \
    OWASP_GID=${OWASP_GID} \
    OWASP_UID=${OWASP_UID} \
    PIP_CACHE_DIR="/home/owasp/.cache/pip" \
    POETRY_CACHE_DIR="/home/owasp/.cache/pypoetry" \
    PYTHONUNBUFFERED=1

RUN mkdir -p ${APK_CACHE_DIR} ${POETRY_CACHE_DIR} && \
    ln -fns ${APK_CACHE_DIR} ${APK_SYMLINK_DIR}

RUN --mount=type=cache,target=${APK_CACHE_DIR} \
    apk --no-cache update && \
    apk --no-cache upgrade && \
    addgroup -S -g ${OWASP_GID} owasp && \
    adduser -S -h /home/owasp -u ${OWASP_UID} -G owasp owasp && \
    chown -R owasp:owasp /home/owasp

COPY --chmod=444 --chown=root:root backend/requirements/build.txt /tmp/
RUN --mount=type=cache,target=${PIP_CACHE_DIR} \
    python -m pip install --require-hashes --requirement /tmp/build.txt

RUN mkdir -p /home/owasp/docs && \
    chown -R owasp:owasp /home/owasp/docs
WORKDIR /home/owasp/docs
USER owasp

COPY --chmod=444 --chown=owasp:owasp docs/poetry.lock docs/poetry.toml docs/pyproject.toml ./
RUN --mount=type=cache,target=${POETRY_CACHE_DIR},uid=${OWASP_UID},gid=${OWASP_GID} \
    poetry install --no-root --verbose --with test

FROM python:3.13.15-alpine3.23@sha256:75f27d686432419c9d42420b2b9ef605868c7a0682a6be10a6601fad46c2df01

ARG OWASP_GID
ARG OWASP_UID

SHELL ["/bin/sh", "-o", "pipefail", "-c"]

RUN addgroup -S -g ${OWASP_GID} owasp && \
    adduser -S -h /home/owasp -u ${OWASP_UID} -G owasp owasp && \
    mkdir -p /home/owasp/.cache/pycache /home/owasp/docs/tests && \
    chown -R owasp:owasp /home/owasp

ENV FORCE_COLOR=1 \
    PATH="/home/owasp/docs/.venv/bin:$PATH" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONPYCACHEPREFIX=/home/owasp/.cache/pycache \
    PYTHONUNBUFFERED=1

USER owasp
WORKDIR /home/owasp/docs

COPY --from=builder --chmod=555 --chown=root:root /home/owasp/docs /home/owasp/docs
COPY --chmod=444 --chown=root:root docs/serve.py ./
COPY --chmod=444 --chown=root:root docs/tests/serve_test.py tests/serve_test.py

CMD ["pytest"]
