- name: Run Nest Staging Data Update
  hosts: nest_staging
  tasks:
    - name: Update Nest data
      async: 21600 # 6 hours
      poll: 600 # 10 minutes
      register: update_data
      shell:
        cmd: 'make update'

    - name: Print job output
      debug:
        var: update_data
