FROM python:3.13-slim AS builder

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libpq-dev && \
    rm -rf /var/lib/apt/lists/* && \
    groupadd --system owasp && \
    useradd --system --create-home --home-dir /home/owasp -g owasp owasp && \
    python -m pip install --no-cache-dir poetry

ENV FORCE_COLOR=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    PYTHONUNBUFFERED=1

WORKDIR /home/owasp
USER owasp

COPY poetry.lock pyproject.toml ./
RUN poetry install --no-root

COPY *.json ./
COPY tests tests
COPY utils utils

FROM python:3.13-slim

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update && \
    apt-get install -y --no-install-recommends libpq-dev && \
    rm -rf /var/lib/apt/lists/* && \
    groupadd --system owasp && \
    useradd --system --create-home --home-dir /home/owasp -g owasp owasp

ENV FORCE_COLOR=1 \
    PATH="/home/owasp/.venv/bin:$PATH" \
    PYTHONUNBUFFERED=1

WORKDIR /home/owasp
USER owasp

COPY --from=builder /home/owasp /home/owasp
