ARG OWASP_GID=1000
ARG OWASP_UID=1000

FROM hashicorp/terraform:1.15.7 AS terraform

FROM python:3.13.14-alpine3.23@sha256:9fdbf2e3e82628351513560b121e2ee6ce31cac212be9e070c5a5e2769fb5e76 AS builder

ARG OWASP_GID
ARG OWASP_UID

ENV APK_CACHE_DIR="/home/owasp/.cache/apk-infrastructure-test" \
    APK_SYMLINK_DIR="/etc/apk/cache" \
    OWASP_GID=${OWASP_GID} \
    OWASP_UID=${OWASP_UID} \
    PIP_CACHE_DIR="/home/owasp/.cache/pip" \
    POETRY_CACHE_DIR="/home/owasp/.cache/pypoetry" \
    PYTHONUNBUFFERED=1

RUN mkdir -p ${APK_CACHE_DIR} ${POETRY_CACHE_DIR} && \
    ln -fns ${APK_CACHE_DIR} ${APK_SYMLINK_DIR}

RUN --mount=type=cache,target=${APK_CACHE_DIR} \
    apk --no-cache update && \
    apk --no-cache upgrade && \
    addgroup -S -g ${OWASP_GID} owasp && \
    adduser -S -h /home/owasp -u ${OWASP_UID} -G owasp owasp && \
    chown -R owasp:owasp /home/owasp

COPY --chmod=444 --chown=root:root backend/requirements/build.txt /tmp/
RUN --mount=type=cache,target=${PIP_CACHE_DIR} \
    python -m pip install --require-hashes --requirement /tmp/build.txt

RUN mkdir -p /home/owasp/infrastructure && \
    chown -R owasp:owasp /home/owasp/infrastructure
WORKDIR /home/owasp/infrastructure
USER owasp

COPY --chmod=444 --chown=owasp:owasp infrastructure/poetry.lock infrastructure/poetry.toml infrastructure/pyproject.toml ./
RUN --mount=type=cache,target=${POETRY_CACHE_DIR},uid=${OWASP_UID},gid=${OWASP_GID} \
    poetry install --no-root --verbose --with test

FROM python:3.13.14-alpine3.23@sha256:9fdbf2e3e82628351513560b121e2ee6ce31cac212be9e070c5a5e2769fb5e76

ARG OWASP_GID
ARG OWASP_UID

RUN addgroup -S -g ${OWASP_GID} owasp && \
    adduser -S -h /home/owasp -u ${OWASP_UID} -G owasp owasp && \
    mkdir -p \
      /home/owasp/.cache/pycache \
      /home/owasp/.terraform.d/plugin-cache \
      /home/owasp/infrastructure/bootstrap \
      /home/owasp/infrastructure/modules \
      /home/owasp/infrastructure/scripts \
      /home/owasp/infrastructure/tests && \
    chown -R owasp:owasp /home/owasp

ENV FORCE_COLOR=1 \
    PATH="/home/owasp/infrastructure/.venv/bin:/usr/local/bin:$PATH" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONPYCACHEPREFIX=/home/owasp/.cache/pycache \
    PYTHONUNBUFFERED=1 \
    TF_PLUGIN_CACHE_DIR="/home/owasp/.terraform.d/plugin-cache"

WORKDIR /home/owasp
USER owasp

COPY --from=terraform --chmod=555 --chown=root:root /bin/terraform /usr/local/bin/terraform
COPY --from=builder --chown=owasp:owasp /home/owasp /home/owasp

WORKDIR /home/owasp/infrastructure

CMD ["sh", "-c", "pytest && python -m scripts.run_tests --unit"]
