nest:
  hosts:
    production_nest:
      ansible_host: "{{ lookup('env', 'NEST_HOST_IP_ADDRESS') }}"
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: "{{ lookup('env', 'NEST_SSH_PRIVATE_KEY_PATH') }}"
      ansible_user: production

    production_nest_proxy:
      ansible_host: "{{ lookup('env', 'PROXY_HOST_IP_ADDRESS') }}"
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: "{{ lookup('env', 'PROXY_SSH_PRIVATE_KEY_PATH') }}"
      ansible_user: proxy

    staging_nest:
      ansible_host: "{{ lookup('env', 'NEST_HOST_IP_ADDRESS') }}"
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: "{{ lookup('env', 'NEST_SSH_PRIVATE_KEY_PATH') }}"
      ansible_user: staging

    staging_nest_proxy:
      ansible_host: "{{ lookup('env', 'PROXY_HOST_IP_ADDRESS') }}"
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: "{{ lookup('env', 'PROXY_SSH_PRIVATE_KEY_PATH') }}"
      ansible_user: proxy
