nest:
  hosts:
    nest_production:
      ansible_host: "{{ lookup('env', 'PRODUCTION_HOST_IP_ADDRESS') }}"
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: "{{ lookup('env', 'PRODUCTION_SSH_PRIVATE_KEY_PATH') }}"
      ansible_user: production

    nest_staging:
      ansible_host: "{{ lookup('env', 'STAGING_HOST_IP_ADDRESS') }}"
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: "{{ lookup('env', 'STAGING_SSH_PRIVATE_KEY_PATH') }}"
      ansible_user: staging
