# Generated by Django 5.2.3 on 2025-06-21 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github', '0030_alter_organization_is_owasp_related_organization'),
        ('owasp', '0043_projecthealthmetrics_unique_daily_project_health_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nest_created_at', models.DateTimeField(auto_now_add=True)),
                ('nest_updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Technology tags (e.g., languages, frameworks)')),
                ('domains', models.JSONField(blank=True, default=list, verbose_name='Relevant domains or topics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentee', to='github.user', verbose_name='GitHub user')),
            ],
            options={
                'verbose_name_plural': 'Mentees',
                'db_table': 'mentorship_mentees',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='Skill level in this program')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='mentorship.mentee', verbose_name='Mentee')),
            ],
            options={
                'verbose_name_plural': 'Enrollments',
                'db_table': 'mentorship_enrollments',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nest_created_at', models.DateTimeField(auto_now_add=True)),
                ('nest_updated_at', models.DateTimeField(auto_now=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Years of experience')),
                ('domain', models.JSONField(default=list, verbose_name='Primary domain(s)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='github.user', verbose_name='GitHub user')),
            ],
            options={
                'verbose_name_plural': 'Mentors',
                'db_table': 'mentorship_mentors',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nest_created_at', models.DateTimeField(auto_now_add=True)),
                ('nest_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Module name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Module description')),
                ('mentees', models.ManyToManyField(blank=True, related_name='modules', to='mentorship.mentee', verbose_name='Mentees')),
                ('mentors', models.ManyToManyField(blank=True, related_name='modules', to='mentorship.mentor', verbose_name='Mentors')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='owasp.project', verbose_name='Associated project')),
            ],
            options={
                'verbose_name_plural': 'Modules',
                'db_table': 'mentorship_modules',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nest_created_at', models.DateTimeField(auto_now_add=True)),
                ('nest_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Program name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Program description')),
                ('preferred_mentee_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='Skill level in this program')),
                ('mentee_limit', models.PositiveIntegerField(default=1, help_text='Maximum number of mentees allowed in this program', verbose_name='Mentee limit')),
                ('active_mentees', models.PositiveIntegerField(default=0, help_text='Current number of active mentees enrolled', verbose_name='Active mentees')),
                ('is_available', models.BooleanField(default=True, help_text='Whether this program is currently accepting new mentees', verbose_name='Currently available')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Technology tags (e.g., languages, frameworks)')),
                ('domains', models.JSONField(blank=True, default=list, verbose_name='Relevant domains or topics')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='Program status')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('owners', models.ManyToManyField(blank=True, related_name='owned_programs', to='mentorship.mentor', verbose_name='Program owners')),
            ],
            options={
                'verbose_name_plural': 'Programs',
                'db_table': 'mentorship_programs',
            },
        ),
        migrations.AddField(
            model_name='mentee',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='mentees', through='mentorship.Enrollment', to='mentorship.program', verbose_name='Enrolled programs'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='mentorship.program', verbose_name='Program'),
        ),
        migrations.CreateModel(
            name='ProgramModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, help_text="Defaults to the program's start date if not specified.", null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, help_text="Defaults to the program's end date if not specified.", null=True, verbose_name='End date')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_programs', to='mentorship.module', verbose_name='Associated module')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_modules', to='mentorship.program', verbose_name='Associated program')),
            ],
            options={
                'verbose_name': 'Program Module Link',
                'verbose_name_plural': 'Program Module Links',
                'db_table': 'mentorship_program_modules',
                'unique_together': {('program', 'module')},
            },
        ),
        migrations.AddField(
            model_name='program',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='linked_programs', through='mentorship.ProgramModule', to='mentorship.module', verbose_name='Modules'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('mentee', 'program')},
        ),
    ]
