# Generated by Django 5.2.3 on 2025-06-22 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("owasp", "0043_projecthealthmetrics_unique_daily_project_health_metrics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mentee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=12,
                        verbose_name="Experience level",
                    ),
                ),
                (
                    "domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Domain expertise (e.g., Application Security, Threat Modeling, etc)",
                        verbose_name="Domains",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Technologies, languages, frameworks, etc",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nest user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mentees",
                "db_table": "mentorship_mentees",
            },
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=12,
                        verbose_name="Experience level",
                    ),
                ),
                (
                    "domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Domain expertise (e.g., Application Security, Threat Modeling, etc)",
                        verbose_name="Domains",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Technologies, languages, frameworks, etc",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nest user",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mentors",
                "db_table": "mentorship_mentors",
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Description"),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=200, verbose_name="Name"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="owasp.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Modules",
                "db_table": "mentorship_modules",
            },
        ),
        migrations.CreateModel(
            name="MentorModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=12,
                        verbose_name="Experience level",
                    ),
                ),
                (
                    "domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Domain expertise (e.g., Application Security, Threat Modeling, etc)",
                        verbose_name="Domains",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Technologies, languages, frameworks, etc",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.mentor",
                        verbose_name="Program",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.module",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentor module",
                "verbose_name_plural": "Mentor modules",
                "db_table": "mentorship_mentor_modules",
                "unique_together": {("mentor", "module")},
            },
        ),
        migrations.AddField(
            model_name="mentor",
            name="modules",
            field=models.ManyToManyField(
                blank=True,
                through="mentorship.MentorModule",
                to="mentorship.module",
                verbose_name="Modules",
            ),
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=12,
                        verbose_name="Experience level",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Description"),
                ),
                ("end_date", models.DateField(verbose_name="End date")),
                (
                    "mentees_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of mentees allowed in this program",
                        null=True,
                        verbose_name="Mentees limit",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="Name")),
                ("start_date", models.DateField(verbose_name="Start date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=9,
                        verbose_name="Status",
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="owned_programs",
                        to="mentorship.mentor",
                        verbose_name="Owners",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Programs",
                "db_table": "mentorship_programs",
            },
        ),
        migrations.CreateModel(
            name="MenteeProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=12,
                        verbose_name="Experience level",
                    ),
                ),
                (
                    "domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Domain expertise (e.g., Application Security, Threat Modeling, etc)",
                        verbose_name="Domains",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Technologies, languages, frameworks, etc",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.mentee",
                        verbose_name="Mentee",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.program",
                        verbose_name="Program",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mentee programs",
                "db_table": "mentorship_mentee_programs",
                "unique_together": {("mentee", "program")},
            },
        ),
        migrations.AddField(
            model_name="mentee",
            name="programs",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentees",
                through="mentorship.MenteeProgram",
                to="mentorship.program",
                verbose_name="Enrolled programs",
            ),
        ),
        migrations.CreateModel(
            name="ProgramModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Defaults to the program's end date if not specified.",
                        verbose_name="End date",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Defaults to the program's start date if not specified.",
                        verbose_name="Start date",
                    ),
                ),
                (
                    "module",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.module",
                        verbose_name="Module",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.program",
                        verbose_name="Program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program module link",
                "verbose_name_plural": "Program module links",
                "db_table": "mentorship_program_modules",
                "unique_together": {("program", "module")},
            },
        ),
        migrations.AddField(
            model_name="program",
            name="modules",
            field=models.ManyToManyField(
                blank=True,
                related_name="programs",
                through="mentorship.ProgramModule",
                to="mentorship.module",
                verbose_name="Modules",
            ),
        ),
    ]
