# Generated by Django 5.2.4 on 2025-07-23 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0032_user_github_user_created_at_desc_and_more"),
        ("mentorship", "0001_initial"),
    ]
    operations = [
        migrations.AddField(
            model_name="module",
            name="labels",
            field=models.JSONField(blank=True, default=list, verbose_name="Labels"),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the task was assigned to the mentee.",
                    ),
                ),
                (
                    "deadline_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional deadline for the task.",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, help_text="Optional data"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "To Do"),
                            ("IN_PROGRESS", "In Progress"),
                            ("IN_REVIEW", "In Review"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="TODO",
                        max_length=20,
                        verbose_name="Task status",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="The mentee assigned to this task.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="github.user",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        help_text="The GitHub issue this task corresponds to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mentorship_tasks",
                        to="github.issue",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        help_text="The module this task is part of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="mentorship.module",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tasks",
                "db_table": "mentorship_tasks",
                "ordering": ["deadline_at"],
                "unique_together": {("issue", "assignee")},
            },
        ),
    ]
