# Generated by Django 5.2.2 on 2025-06-14 16:31

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0028_merge_20250510_1542'),
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nest_created_at', models.DateTimeField(auto_now_add=True)),
                ('nest_updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveIntegerField(verbose_name='Mentee level')),
                ('top_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None, verbose_name='Top skills (languages/frameworks)')),
                ('preferred_tech_stack', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None, verbose_name='Preferred tech stack')),
                ('interested_domains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None, verbose_name='Interested domains')),
                ('issues_worked_on', models.PositiveIntegerField(default=0, verbose_name='Number of issues worked on')),
                ('prs_opened', models.PositiveIntegerField(default=0, verbose_name='Number of PRs opened')),
                ('prs_merged', models.PositiveIntegerField(default=0, verbose_name='Number of PRs merged')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentee', to='github.user', verbose_name='GitHub user')),
            ],
            options={
                'verbose_name_plural': 'Mentees',
                'db_table': 'mentorship_mentees',
            },
        ),
    ]
