# Generated by Django 5.2.3 on 2025-07-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="key",
            field=models.CharField(
                default="default", max_length=200, unique=True, verbose_name="Key"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="program",
            name="key",
            field=models.CharField(
                default="temp-key", max_length=200, unique=True, verbose_name="Key"
            ),
            preserve_default=False,
        ),
    ]
