# Generated by Django 5.2.4 on 2025-07-23 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0032_user_github_user_created_at_desc_and_more"),
        ("mentorship", "0002_module_labels_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                help_text="The mentee assigned to this task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="github.user",
            ),
        ),
        migrations.CreateModel(
            name="TaskLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Description"),
                ),
                (
                    "github_labels",
                    models.JSONField(blank=True, default=list, verbose_name="GitHub Labels"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_levels",
                        to="mentorship.module",
                        verbose_name="Module",
                    ),
                ),
                (
                    "needs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="required_by",
                        to="mentorship.tasklevel",
                        verbose_name="Prerequisite Levels",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Task Levels",
                "db_table": "mentorship_task_levels",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="level",
            field=models.ForeignKey(
                blank=True,
                help_text="The difficulty level of this task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="mentorship.tasklevel",
            ),
        ),
    ]
