# Generated by Django 5.2.4 on 2025-08-04 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0002_module_labels_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Description"),
                ),
                ("labels", models.JSONField(blank=True, default=list, verbose_name="Labels")),
                ("name", models.CharField(default="", max_length=200, verbose_name="Name")),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_levels",
                        to="mentorship.module",
                        verbose_name="Module",
                    ),
                ),
                (
                    "needs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="required_by",
                        to="mentorship.tasklevel",
                        verbose_name="Prerequisite Levels",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Task Levels",
                "db_table": "mentorship_task_levels",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="level",
            field=models.ForeignKey(
                blank=True,
                help_text="The difficulty level of this task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="mentorship.tasklevel",
            ),
        ),
        migrations.AddConstraint(
            model_name="tasklevel",
            constraint=models.UniqueConstraint(
                fields=("module", "name"), name="unique_module_tasklevel_name"
            ),
        ),
    ]
