# Generated by Django 5.2.2 on 2025-06-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0002_mentee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Program name")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Program description"),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Technology tags (e.g., languages, frameworks)",
                    ),
                ),
                (
                    "domains",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Relevant domains or topics"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Program status",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start date")),
                ("end_date", models.DateField(verbose_name="End date")),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="owned_programs",
                        to="mentorship.mentor",
                        verbose_name="Program owners",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Programs",
                "db_table": "mentorship_programs",
            },
        ),
    ]
