# Generated by Django 5.2.4 on 2025-07-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0002_module_labels_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="key",
            field=models.CharField(default="temp-key", max_length=200, verbose_name="Key"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="program",
            name="key",
            field=models.CharField(
                default="temp-key", max_length=200, unique=True, verbose_name="Key"
            ),
            preserve_default=False,
        ),
    ]
