# Generated by Django 5.2.2 on 2025-06-14 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0003_program'),
        ('owasp', '0034_alter_chapter_leaders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nest_created_at', models.DateTimeField(auto_now_add=True)),
                ('nest_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Module name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Module description')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('mentees', models.ManyToManyField(blank=True, related_name='modules', to='mentorship.mentee', verbose_name='Mentees')),
                ('mentors', models.ManyToManyField(blank=True, related_name='modules', to='mentorship.mentor', verbose_name='Mentors')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='owasp.project', verbose_name='Associated project')),
            ],
            options={
                'verbose_name_plural': 'Modules',
                'db_table': 'mentorship_modules',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='linked_programs', to='mentorship.module', verbose_name='Modules'),
        ),
    ]
