# Generated by Django 5.2.4 on 2025-08-20 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0034_issuecomment"),
        ("mentorship", "0003_tasklevel_task_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributorInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_interests",
                        to="github.issue",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="mentorship.module",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, related_name="mentorship_interests", to="github.user"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contributor Interests",
                "unique_together": {("module", "issue")},
            },
        ),
    ]
