# Generated by Django 5.2.4 on 2025-08-23 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0034_comment_issue_comments"),
        ("mentorship", "0003_tasklevel_task_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueUserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_interests",
                        to="github.issue",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="mentorship.module",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_interests",
                        to="github.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue User Interest",
                "verbose_name_plural": "Issue User Interests",
                "unique_together": {("module", "issue", "user")},
            },
        ),
    ]
