# Generated by Django 5.2.4 on 2025-08-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0034_merge_20250804_1817"),
        ("mentorship", "0004_module_key_program_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="issues",
            field=models.ManyToManyField(
                blank=True,
                help_text="Issues linked to this module via label matching.",
                related_name="mentorship_modules",
                to="github.issue",
                verbose_name="Linked Issues",
            ),
        ),
    ]
