# Generated by Django 5.2.5 on 2025-09-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0037_issue_level"),
        ("mentorship", "0004_module_key_program_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="level",
        ),
        migrations.AddField(
            model_name="module",
            name="issues",
            field=models.ManyToManyField(
                blank=True,
                help_text="Issues linked to this module via label matching.",
                related_name="mentorship_modules",
                to="github.issue",
                verbose_name="Linked Issues",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the task was assigned to the mentee.",
                null=True,
            ),
        ),
    ]
