# Generated by Django 5.2.8 on 2025-11-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0005_remove_task_level_module_issues_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menteemodule",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End date and time"),
        ),
    ]
