# Generated by Django 5.2.6 on 2025-11-16 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0005_issueuserinterest"),
        ("mentorship", "0005_remove_task_level_module_issues_and_more"),
    ]

    operations = []
