# Generated by Django 5.2.4 on 2025-08-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0005_module_issues"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="level",
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the task was assigned to the mentee.",
                null=True,
            ),
        ),
    ]
