# Generated by Django 6.0 on 2025-12-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0006_alter_menteemodule_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
    ]
