# Generated by Django 6.0.1 on 2026-01-12 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_program_admins_to_admin_model(apps, _schema_editor):
    """Migrate existing nest.User program admins to Admin model via ProgramAdmin."""
    program_model = apps.get_model("mentorship", "Program")
    admin_model = apps.get_model("mentorship", "Admin")
    program_admin_model = apps.get_model("mentorship", "ProgramAdmin")

    admins_to_create = []
    program_admins_to_create = []
    all_github_user_ids = set()

    programs = program_model.objects.all()

    for program in programs:
        old_admins = program.admins.all()

        for nest_user in old_admins:
            if not nest_user.github_user_id:
                continue

            github_user_id = nest_user.github_user_id
            all_github_user_ids.add(github_user_id)

            try:
                admin = admin_model.objects.get(github_user_id=github_user_id)
                if not admin.nest_user_id:
                    admin.nest_user_id = nest_user.id
                    admin.save(update_fields=["nest_user"])
            except admin_model.DoesNotExist:
                admins_to_create.append(
                    admin_model(github_user_id=github_user_id, nest_user_id=nest_user.id)
                )

    if admins_to_create:
        admin_model.objects.bulk_create(admins_to_create, ignore_conflicts=True)

    admins_by_github_user = {
        admin.github_user_id: admin
        for admin in admin_model.objects.filter(github_user_id__in=all_github_user_ids)
    }

    for program in programs:
        for nest_user in program.admins.all():
            if not nest_user.github_user_id:
                continue

            github_user_id = nest_user.github_user_id
            admin = admins_by_github_user.get(github_user_id)
            if admin:
                program_admins_to_create.append(
                    program_admin_model(program=program, admin=admin, role="owner")
                )

    if program_admins_to_create:
        program_admin_model.objects.bulk_create(program_admins_to_create, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0040_merge_20251117_0136'),
        ('mentorship', '0006_alter_menteemodule_ended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='github_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_github_user', to='github.user', verbose_name='GitHub user'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='nest_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_nest_user', to=settings.AUTH_USER_MODEL, verbose_name='Nest user'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nest_created_at', models.DateTimeField(auto_now_add=True)),
                ('nest_updated_at', models.DateTimeField(auto_now=True)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=12, verbose_name='Experience level')),
                ('domains', models.JSONField(blank=True, default=list, help_text='Domain expertise (e.g., Application Security, Threat Modeling, etc)', verbose_name='Domains')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Technologies, languages, frameworks, etc', verbose_name='Tags')),
                ('github_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_github_user', to='github.user', verbose_name='GitHub user')),
                ('nest_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_nest_user', to=settings.AUTH_USER_MODEL, verbose_name='Nest user')),
            ],
            options={
                'verbose_name_plural': 'Admins',
                'db_table': 'mentorship_admins',
            },
        ),
        migrations.CreateModel(
            name='ProgramAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nest_created_at', models.DateTimeField(auto_now_add=True)),
                ('nest_updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner')], default='owner', max_length=20, verbose_name='Role')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_admin_roles', to='mentorship.admin', verbose_name='Admin')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_admins', to='mentorship.program', verbose_name='Program')),
            ],
            options={
                'verbose_name_plural': 'Program admins',
                'db_table': 'mentorship_program_admins',
                'unique_together': {('program', 'admin')},
            },
        ),
        migrations.RunPython(
            migrate_program_admins_to_admin_model,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="program",
            name="admins",
        ),
        migrations.AddField(
            model_name="program",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="admin_programs",
                through="mentorship.ProgramAdmin",
                to="mentorship.Admin",
                verbose_name="Admins",
            ),
        ),
    ]
