# Generated by Django 6.0 on 2025-12-29 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_mentor_admins_to_users(apps, _schema_editor):
    """Migrate existing Mentor admins to nest.User admins via ProgramAdmin."""
    program_model = apps.get_model("mentorship", "Program")
    program_admin_model = apps.get_model("mentorship", "ProgramAdmin")
    user_model = apps.get_model("nest", "User")

    program_admins_to_create = []
    programs = program_model.objects.all()

    for program in programs:
        old_admins = program.admins.all()

        for admin in old_admins:
            if admin.nest_user_id:
                try:
                    nest_user = user_model.objects.get(pk=admin.nest_user_id)
                    program_admins_to_create.append(
                        program_admin_model(program=program, user=nest_user, role="owner")
                    )
                except user_model.DoesNotExist:
                    continue

    if program_admins_to_create:
        program_admin_model.objects.bulk_create(program_admins_to_create, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0006_alter_menteemodule_ended_at"),
        ("nest", "0001_initial"),  # Ensure nest app is available
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nest_created_at", models.DateTimeField(auto_now_add=True)),
                ("nest_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner")],
                        default="owner",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_admins",
                        to="mentorship.program",
                        verbose_name="Program",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_admin_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Program admins",
                "db_table": "mentorship_program_admins",
                "unique_together": {("program", "user")},
            },
        ),
        migrations.RunPython(
            migrate_mentor_admins_to_users,
        ),
        migrations.RemoveField(
            model_name="program",
            name="admins",
        ),
        migrations.AddField(
            model_name="program",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="admin_programs",
                through="mentorship.ProgramAdmin",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Admins",
            ),
        ),
    ]
