name: Check contribution

on:
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  check-contribution:
    if: github.event.pull_request.base.repo.full_name == github.repository
    permissions:
      contents: read
      issues: read
      pull-requests: write
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check contribution requirements
        uses: arkid15r/check-contribution-action@8d461a5dce23432339eaa12ce3c8d35013b038ab  # v0.1.6
        with:
          check_for: commit_sign_off, commit_signature, issue_assignee, issue_reference
          close_on: issue_assignee, issue_reference
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_users_file_path: .github/check-contribution-skip-usernames.txt
    timeout-minutes: 5
