name: Check contribution

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  check-contribution:
    if: github.event.repository.fork == false
    permissions:
      contents: read
      issues: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false

      - name: Check contribution requirements
        uses: arkid15r/check-contribution-action@f43cc6c6f4e390df58fc5c97b645cda8ba8b66fb  # v0.1.3
        with:
          check_for: commit_sign_off, commit_signature, issue_assignee, issue_reference
          close_on: issue_assignee
          github_token: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 5
