name: Check contribution

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions: {}

jobs:
  check-contribution:
    if: github.event.pull_request.head.repo.fork == false
    permissions:
      contents: read
      issues: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false

      - name: Check contribution requirements
        uses: arkid15r/check-contribution-action@054ada7a71ac5cea5c111dbd41ecb4f4e71c9872  # v0.1.0
        with:
          check_issue_reference: 'true'
          close_pr_on_assignee_mismatch: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          no_assignee_message: The linked issue must be assigned to the PR author.
          no_issue_message: The PR must be linked to an issue assigned to the PR author.
          require_assignee: 'true'
          skip_users_file_path: .github/check-contribution-skip-usernames.txt
    timeout-minutes: 5
