name: CI

on:
  merge_group:
  pull_request:
    branches:
      - dev
      - feature/**
      - main
  push:
    branches:
      - dev
      - feature/**
      - main

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
  run-code-checks-tests:
    name: Code checks tests
    permissions:
      actions: write
      contents: read
      id-token: write
    uses: ./.github/workflows/run-code-checks-tests.yaml
