name: CI

on:
  merge_group:
  pull_request:
    branches:
      - feature/**
      - main
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ci-${{ github.workflow }}-${{ github.ref }}

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
  run-code-checks:
    name: Code checks
    permissions:
      contents: read
    uses: ./.github/workflows/run-code-checks.yaml

  run-code-tests:
    name: Code tests
    needs:
      - run-code-checks
    permissions:
      actions: write
      contents: read
      id-token: write
    uses: ./.github/workflows/run-code-tests.yaml

  run-dependency-audit:
    name: Dependency audit
    permissions:
      contents: read
    uses: ./.github/workflows/run-dependency-audit.yaml
