name: CodeQL JavaScript/TypeScript

on:
  merge_group:
  pull_request:
    branches:
      - feature/**
      - main
    paths:
      - .github/actions/install-frontend-dependencies/**
      - .github/workflows/code-ql-javascript-typescript.yaml
      - '**/*.cjs'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.mjs'
      - '**/*.ts'
      - '**/*.tsx'
      - e2e/**
      - frontend/**
  push:
    branches:
      - main
    paths:
      - .github/actions/install-frontend-dependencies/**
      - .github/workflows/code-ql-javascript-typescript.yaml
      - '**/*.cjs'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.mjs'
      - '**/*.ts'
      - '**/*.tsx'
      - e2e/**
      - frontend/**

concurrency:
  cancel-in-progress: true
  group: code-ql-javascript-typescript-${{ github.ref }}

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
  run-code-ql:
    name: CodeQL JavaScript/TypeScript
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false

      - name: Initialize CodeQL
        uses: github/codeql-action/init@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a  # v4.36.3
        with:
          languages: javascript-typescript

      - name: Install frontend dependencies
        uses: ./.github/actions/install-frontend-dependencies

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a  # v4.36.3
        with:
          category: /language:javascript-typescript
    timeout-minutes: 5
