name: CodeQL Python

on:
  merge_group:
  pull_request:
    branches:
      - feature/**
      - main
    paths:
      - .github/actions/install-backend-dependencies/**
      - .github/actions/install-poetry/**
      - .github/workflows/code-ql-python.yaml
      - '**/*.py'
      - backend/**
  push:
    branches:
      - main
    paths:
      - .github/actions/install-backend-dependencies/**
      - .github/actions/install-poetry/**
      - .github/workflows/code-ql-python.yaml
      - '**/*.py'
      - backend/**

concurrency:
  cancel-in-progress: true
  group: code-ql-python-${{ github.ref }}

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
  run-code-ql:
    name: CodeQL Python
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false

      - name: Initialize CodeQL
        uses: github/codeql-action/init@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a  # v4.36.3
        with:
          languages: python

      - name: Install backend dependencies
        uses: ./.github/actions/install-backend-dependencies

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a  # v4.36.3
        with:
          category: /language:python
    timeout-minutes: 5
