name: CodeQL JavaScript/TypeScript

on:
  merge_group:
  pull_request:
    branches:
      - feature/**
      - main
    paths:
      - .github/actions/install-frontend-dependencies/**
      - .github/workflows/code-ql-javascript-typescript.yaml
      - '**/*.cjs'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.mjs'
      - '**/*.ts'
      - '**/*.tsx'
      - e2e/**
      - frontend/**

concurrency:
  cancel-in-progress: true
  group: code-ql-javascript-typescript-${{ github.ref }}

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
  run-code-ql:
    name: CodeQL JavaScript/TypeScript
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false

      - name: Initialize CodeQL
        uses: github/codeql-action/init@7211b7c8077ea37d8641b6271f6a365a22a5fbfa  # v4.36.0
        with:
          languages: javascript-typescript

      - name: Install frontend dependencies
        uses: ./.github/actions/install-frontend-dependencies

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@7211b7c8077ea37d8641b6271f6a365a22a5fbfa  # v4.36.0
        with:
          category: /language:javascript-typescript
    timeout-minutes: 5
