name: CodeQL Python

on:
  merge_group:
  pull_request:
    branches:
      - feature/**
      - main
    paths:
      - .github/actions/install-backend-dependencies/**
      - .github/actions/install-poetry/**
      - .github/workflows/code-ql-python.yaml
      - '**/*.py'
      - backend/**

concurrency:
  cancel-in-progress: true
  group: code-ql-python-${{ github.ref }}

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
  run-code-ql:
    name: CodeQL Python
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false

      - name: Initialize CodeQL
        uses: github/codeql-action/init@7211b7c8077ea37d8641b6271f6a365a22a5fbfa  # v4.36.0
        with:
          languages: python

      - name: Install backend dependencies
        uses: ./.github/actions/install-backend-dependencies

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@7211b7c8077ea37d8641b6271f6a365a22a5fbfa  # v4.36.0
        with:
          category: /language:python
    timeout-minutes: 5
