name: Generate Models Graph

on:
  push:
    paths:
      - "backend/apps/**/models/**"
      - "pyproject.toml"
      - "README.md"
  workflow_dispatch:

jobs:
  generate-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y graphviz graphviz-dev

      - name: Prepare secrets
        run: |
          echo "DJANGO_SENTRY_DSN=${{ secrets.DJANGO_SENTRY_DSN }}" > backend/.env.backend
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> backend/.env.backend
          echo "DJANGO_SETTINGS_MODULE=settings.test" >> backend/.env.backend
          echo "DJANGO_CONFIGURATION=${{ secrets.DJANGO_CONFIGURATION }}" >> backend/.env.backend
          echo "DJANGO_RELEASE_VERSION=$(date '+%y.%-m.%-d')-${GITHUB_SHA:0:7}" >> backend/.env.backend
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> backend/.env.backend

      - name: Install dependencies
        run: |
          cd backend
          export $(grep -v '^#' .env.backend | xargs)
          poetry install --no-interaction --no-root --with dev

      - name: Verify `django-extensions` is installed
        run: |
          cd backend
          export $(grep -v '^#' .env.backend | xargs)
          poetry run python -m pip show django-extensions || poetry run pip install django-extensions

      - name: Generate Models Graph
        run: |
          cd backend
          set -a
          source .env.backend
          set +a
          poetry run python manage.py graph_models -a -g -o backend_models.png


      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add backend/backend_models.png README.md
          git commit -m "Update model diagram" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git ${{ github.ref }} || echo "No changes to push"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-models-graph
          path: backend/backend_models.png
