name: Generate Models Graph

on:
  push:
    paths:
      - "backend/apps/**/models/**"
      - "pyproject.toml"
      - "README.md"
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y graphviz graphviz-dev

      - name: Install dependencies
        run: |
          cd backend
          poetry install --no-interaction --no-root

      - name: Generate Models Graph
        run: |
          cd backend
          poetry run python manage.py graph_models -a -g -o backend_models.png

      - name: Commit and Push Updated Image
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add backend/backend_models.png
          git commit -m "chore: update Django models graph [CI skip]" || echo "No changes to commit"
          git push origin ${{ github.ref }} || echo "No changes to push"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-models-graph
          path: backend/backend_models.png
