name: Generate Models Graph

on:
  push:
    paths:
      - "backend/apps/**/models/**"
      - "pyproject.toml"
      - "README.md"
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y graphviz graphviz-dev

      - name: Set Environment Variables
        run: |
          echo "DJANGO_SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> $GITHUB_ENV
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV
          echo "DJANGO_DEBUG=False" >> $GITHUB_ENV

      - name: Install dependencies
        env:
          POETRY_HTTP_BASIC_USERNAME: ${{ secrets.POETRY_HTTP_BASIC_USERNAME }}
          POETRY_HTTP_BASIC_PASSWORD: ${{ secrets.POETRY_HTTP_BASIC_PASSWORD }}
        run: |
          cd backend
          poetry install --no-interaction --no-root

      - name: Generate Models Graph
        run: |
          cd backend
          poetry run python manage.py graph_models -a -g -o backend_models.png

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add backend/backend_models.png README.md
          git commit -m "Update model diagram" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git ${{ github.ref }} || echo "No changes to push"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-models-graph
          path: backend/backend_models.png
