name: Generate Model Diagram

on:
  push:
    paths:
      - '../../backend/apps/github/models/**' # Trigger on changes in the models directory
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  generate-erd:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django graphviz django-extensions psycopg2-binary

    # Step 4: Generate the model diagram
    - name: Generate model diagram
      run: |
        python manage.py graph_models -a > models.dot
        dot -Tpng models.dot -o models.png

    # Step 5: Update README.md with the new model diagram
    - name: Update README.md
      run: |
        echo "![Model Diagram](models.png)" > README.md

    # Step 6: Commit and push changes
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add models.png README.md
        git commit -m "Update model diagram"
        git push
