name: Test OWASP Schema

on:
  merge_group:
  pull_request:
    branches:
      - main
    paths:
      - schema/**
  push:
    branches:
      - main
    paths:
      - schema/**
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}

env:
  FORCE_COLOR: 1

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          cache: poetry
          cache-dependency-path: schema/poetry.lock
          python-version: '3.13'

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd

      - name: Check for uncommitted changes
        run: |
          git diff --exit-code || (echo 'Unstaged changes detected. \
          Run `make check` and use `git add` to address it.' && exit 1)

  code-ql:
    name: CodeQL
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language:
          - python
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Initialize CodeQL
        uses: github/codeql-action/init@51f77329afa6477de8c49fc9c7046c15b9a4e79d
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@51f77329afa6477de8c49fc9c7046c15b9a4e79d
        with:
          category: /language:${{ matrix.language }}

  spellcheck:
    name: Run spell check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run cspell
        run: |
          make check-spelling

  run-schema-tests:
    name: Run schema tests
    needs:
      - pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: Build schema test image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          cache-from: |
            type=gha
            type=registry,ref=owasp/nest:test-schema-cache
          cache-to: |
            type=gha,compression=zstd
          context: .
          file: schema/docker/Dockerfile.test
          load: true
          platforms: linux/amd64
          tags: owasp/nest:test-schema-latest

      - name: Run schema tests
        run: |
          docker run --rm owasp/nest:test-schema-latest pytest

  publish-schema-package:
    name: Publish to PyPI
    needs:
      - run-schema-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: |
          cd schema
          poetry install

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump version
        run: |
          cd schema
          poetry run bump2version patch --commit --tag --allow-dirty
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        run: |
          git push
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with new version
        run: |
          cd schema
          poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automated release for OWASP Schema package.

            Changes in this release:
            - Updated schema files
            - Automated build and publish

            Package: https://pypi.org/project/owasp-schema/
          draft: false
          prerelease: false
