name: Run staging workflow

on:
  schedule:
    - cron: 0 2 * * *
  workflow_dispatch:

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
  run-environment:
    name: Run staging environment
    permissions:
      actions: write
      contents: write
      id-token: write
    uses: ./.github/workflows/run-environment.yaml
    with:
      backend_gid: '1001'
      backend_uid: '1001'
      backend_use_fargate_spot: true
      base_url: https://nest.owasp.dev
      django_configuration: Staging
      django_settings_module: settings.staging
      enable_cron_tasks: false
      enable_nat_gateway: false
      enable_rds_proxy: false
      env_display: Staging
      environment: staging
      frontend_use_fargate_spot: true
      tasks_use_fargate_spot: true
