name: Run production jobs

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
  run-environment:
    name: Run production environment
    permissions:
      actions: write
      contents: write
    uses: ./.github/workflows/run-environment.yaml
    with:
      backend_gid: '1002'
      backend_uid: '1002'
      backend_use_fargate_spot: false
      base_url: https://nest.owasp.org
      django_configuration: Production
      django_settings_module: settings.production
      enable_additional_parameters: true
      enable_cron_tasks: true
      enable_nat_gateway: true
      enable_rds_proxy: true
      env_display: Production
      environment: production
      frontend_use_fargate_spot: false
      release_tag: ${{ github.event.release.tag_name }}
      tasks_use_fargate_spot: false
