name: Dependency checks

on:
  workflow_call:

env:
  FORCE_COLOR: 1

permissions: {}

jobs:
  run-dependency-audit:
    name: Dependency audit
    continue-on-error: true
    permissions:
      contents: read
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false

      - name: Audit dependencies
        run: make security-dependency-audit
    timeout-minutes: 5

  run-dependency-scan:
    name: Dependency scan
    continue-on-error: true
    permissions:
      contents: read
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false

      - name: Run Trivy vulnerability scan
        uses: ./.github/actions/run-trivy-scan
        with:
          command: make security-vulnerability-scan-trivy
    timeout-minutes: 5
