name: Code checks tests

on:
  workflow_call:

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
  run-code-checks:
    name: Code checks
    permissions:
      contents: read
    uses: ./.github/workflows/run-code-checks.yaml

  run-backend-tests:
    name: Backend tests
    needs:
      - run-code-checks
    permissions:
      actions: write
      contents: read
      id-token: write
    uses: ./.github/workflows/run-backend-tests.yaml

  run-frontend-tests:
    name: Frontend tests
    needs:
      - run-code-checks
    permissions:
      actions: read
      contents: read
      id-token: write
    uses: ./.github/workflows/run-frontend-tests.yaml

  run-e2e-tests:
    name: E2E tests
    needs:
      - run-code-checks
    permissions:
      contents: read
    uses: ./.github/workflows/run-e2e-tests.yaml

  run-fuzz-graphql-tests:
    name: GraphQL fuzz tests
    if: false
    needs:
      - run-code-checks
    uses: ./.github/workflows/run-fuzz-tests.yaml
    with:
      test-file: graphql_test.py

  run-fuzz-rest-tests:
    name: REST fuzz tests
    needs:
      - run-code-checks
    uses: ./.github/workflows/run-fuzz-tests.yaml
    with:
      rest-url: http://localhost:9500/api/v0
      test-file: rest_test.py

  run-infrastructure-tests:
    name: Infrastructure tests
    needs:
      - run-code-checks
    permissions:
      contents: read
    uses: ./.github/workflows/run-infrastructure-tests.yaml
