name: Run staging workflow

on:
  workflow_call:
    inputs:
      release_version:
        description: The release version to set
        required: true
        type: string

env:
  FORCE_COLOR: 1

permissions: {}

jobs:
  run-environment:
    name: Run staging environment
    permissions:
      actions: write
      contents: write
    uses: ./.github/workflows/run-environment.yaml
    with:
      environment: staging
      env_display: Staging
      release_version: ${{ inputs.release_version }}
      base_url: https://nest.owasp.dev
      backend_uid: '1001'
      backend_gid: '1001'
      backend_use_fargate_spot: true
      django_configuration: Staging
      django_settings_module: settings.staging
      enable_cron_tasks: false
      enable_nat_gateway: false
      enable_rds_proxy: false
      frontend_use_fargate_spot: true
      tasks_use_fargate_spot: true
