name: Run fuzz tests

on:
  workflow_call:
    inputs:
      test-file:
        description: The test file to run fuzz tests on
        required: true
        type: string
      rest-url:
        description: The REST API URL to test against
        required: false
        type: string
        default: http://localhost:9500/api/v0

jobs:
  run-fuzz-tests:
    name: Run Fuzz Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    services:
      db:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_DB: nest_db_fuzz
          POSTGRES_PASSWORD: nest_user_fuzz_password
          POSTGRES_USER: nest_user_fuzz
        options: >-
          --health-cmd="pg_isready -U nest_user_fuzz -d nest_db_fuzz -h localhost -p 5432"
          --health-interval=5s
          --health-retries=5
          --health-timeout=5s
        ports:
          - 5432:5432
      cache:
        image: redis:8.0.5-alpine3.21
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=5s
          --health-retries=5
          --health-timeout=5s
        ports:
          - 6379:6379
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup Backend environment
        uses: ./.github/workflows/setup-backend-environment
        with:
          db_username: nest_user_fuzz
          db_name: nest_db_fuzz
          db_password: nest_user_fuzz_password
          env_file: backend/.env.fuzz.example
          backend_port: 9500

      - name: Run fuzz tests
        env:
          TEST_FILE: ${{ inputs.test-file }}
          REST_URL: ${{ inputs.rest-url }}
        run: |
          set -a && source backend/.env.fuzz.example && set +a
          export BASE_URL=http://localhost:9500
          export CI=true
          export PYTEST_ADDOPTS="--no-cov"
          export REST_URL="$REST_URL"
          export TEST_FILE="fuzz/$TEST_FILE"
          source backend/.venv/bin/activate
          cd backend && sh ./entrypoint.fuzz.sh
