name: Infrastructure tests

on:
  workflow_call:

env:
  FORCE_COLOR: 1
  TF_PLUGIN_CACHE_DIR: /home/runner/.terraform.d/plugin-cache

permissions: {}

jobs:
  run-infrastructure-tests:
    name: Infrastructure tests
    permissions:
      contents: read
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false

      - name: Install Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e  # v4.0.1
        with:
          terraform_version: 1.14

      - name: Create plugin cache directory
        run: mkdir -p "$TF_PLUGIN_CACHE_DIR"

      - name: Cache Terraform plugins
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
        with:
          key: ${{ runner.os }}-${{ runner.arch }}-terraform-${{ hashFiles('infrastructure/**/.terraform.lock.hcl') }}
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}

      - name: Run tests
        run: make test-infrastructure
    timeout-minutes: 10
