name: Run fuzz tests

on:
  workflow_call:
    inputs:
      test-file:
        description: The test file to run fuzz tests on
        required: true
        type: string
      rest-url:
        description: The REST API URL to test against
        required: false
        type: string
        default: http://localhost:9500/api/v0

jobs:
  run-fuzz-tests:
    name: Run Fuzz Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    services:
      db:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_DB: nest_db_fuzz
          POSTGRES_PASSWORD: nest_user_fuzz_password
          POSTGRES_USER: nest_user_fuzz
        options: >-
          --health-cmd="pg_isready -U nest_user_fuzz -d nest_db_fuzz -h localhost -p 5432"
          --health-interval=5s
          --health-retries=5
          --health-timeout=5s
        ports:
          - 5432:5432
      cache:
        image: redis:8.0.5-alpine3.21
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=5s
          --health-retries=5
          --health-timeout=5s
        ports:
          - 6379:6379
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup Backend environment
        uses: ./.github/workflows/setup-backend-environment
        with:
          db_username: nest_user_fuzz
          db_name: nest_db_fuzz

      - name: Run backend with fuzz environment variables
        run: |
          set -euo pipefail && set -a && source backend/.env.fuzz.example && set +a
          export DJANGO_DB_HOST=localhost
          export DJANGO_REDIS_AUTH_ENABLED=False
          export DJANGO_REDIS_HOST=localhost
          export DJANGO_REDIS_PASSWORD=
          cd backend && poetry run python manage.py migrate
          poetry run gunicorn wsgi:application --bind 0.0.0.0:9500 &

      - name: Waiting for the backend to be ready
        run: |
          timeout 5m bash -c '
            until wget --spider http://localhost:9500/a; do
              echo "Waiting for backend..."
              sleep 5
            done
          '
          echo "Backend is up!"

      - name: Load Postgres data
        env:
          PGPASSWORD: nest_user_fuzz_password
        run: |
          set -euo pipefail
          if ! pg_restore -h localhost -U nest_user_fuzz -d nest_db_fuzz < backend/data/nest.dump; then
            echo "Data loading failed"
            exit 1
          fi
          echo "Data loading completed."

      - name: Run fuzz tests
        env:
          TEST_FILE: ${{ inputs.test-file }}
          REST_URL: ${{ inputs.rest-url }}
        run: |
          export BASE_URL=http://localhost:9500
          export CI=true
          export REST_URL="$REST_URL"
          export TEST_FILE="fuzz/$TEST_FILE"
          cd backend && sh ./entrypoint.fuzz.sh
