name: Backend tests

on:
  workflow_call:

env:
  FORCE_COLOR: 1

permissions: {}

jobs:
  run-unit-tests:
    name: Unit tests
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.13'

      - name: Install Poetry
        uses: ./.github/actions/install-poetry

      - name: Set up backend dependencies cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
        with:
          key: poetry-venv-${{ runner.os }}-${{ hashFiles('backend/poetry.lock') }}
          path: backend/.venv

      - name: Install backend dependencies
        run: poetry install --no-interaction --no-root
        working-directory: backend

      - name: Run backend tests
        run: set -a && source .env.unit-tests && set +a && poetry run pytest tests/unit
        working-directory: backend

      - name: Upload coverage artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          if-no-files-found: error
          name: coverage-xml
          path: backend/coverage.xml
    timeout-minutes: 5

  run-coverage-upload:
    name: Coverage upload
    needs: run-unit-tests
    permissions:
      actions: read
      contents: read
      id-token: write
    uses: ./.github/workflows/run-coverage-upload.yaml
    with:
      artifact_name: coverage-xml
      artifact_path: backend
      coverage_path: backend/coverage.xml
      coverage_flags: backend
