name: Coverage upload

on:
  workflow_call:
    inputs:
      artifact_name:
        description: Coverage artifact name
        required: true
        type: string
      artifact_path:
        description: Coverage artifact download path
        required: true
        type: string
      coverage_flags:
        description: Codecov flags
        required: false
        type: string
        default: ''
      coverage_path:
        description: Coverage report file path
        required: true
        type: string


permissions: {}

jobs:
  run-coverage-upload:
    name: Coverage upload
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Download coverage report
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131  # v7.0.0
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2  # v6.0.0
        with:
          fail_ci_if_error: true
          files: ${{ inputs.coverage_path }}
          flags: ${{ inputs.coverage_flags }}
          use_oidc: true
    timeout-minutes: 5
