name: Run CI/CD

on:
  merge_group:
  pull_request:
    branches:
      - dev
      - feature/**
      - main
  push:
    branches:
      - dev
      - feature/**
      - main
  release:
    types:
      - published
  schedule:
    - cron: 0 2 * * *  # Run staging deploy daily at 2am UTC.
  workflow_dispatch:

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
  run-code-quality-checks:
    name: Run code quality checks
    permissions:
      contents: read
    uses: ./.github/workflows/run-code-quality-checks.yaml

  run-backend-tests:
    name: Run backend tests
    needs:
      - run-code-quality-checks
    permissions:
      actions: write
      contents: read
      id-token: write
    uses: ./.github/workflows/run-backend-tests.yaml

  run-frontend-tests:
    name: Run frontend tests
    needs:
      - run-code-quality-checks
    permissions:
      actions: read
      contents: read
      id-token: write
    uses: ./.github/workflows/run-frontend-tests.yaml

  run-e2e-tests:
    name: Run e2e tests
    needs:
      - run-code-quality-checks
    permissions:
      contents: read
    uses: ./.github/workflows/run-e2e-tests.yaml

  run-graphql-fuzz-tests:
    name: Run GraphQL fuzz tests
    if: false
    needs:
      - run-code-quality-checks
    uses: ./.github/workflows/run-fuzz-tests.yaml
    with:
      test-file: graphql_test.py

  run-rest-fuzz-tests:
    name: Run REST fuzz tests
    needs:
      - run-code-quality-checks
    uses: ./.github/workflows/run-fuzz-tests.yaml
    with:
      test-file: rest_test.py
      rest-url: http://localhost:9500/api/v0

  run-infrastructure-tests:
    name: Run Infrastructure tests
    needs:
      - run-code-quality-checks
    permissions:
      contents: read
    uses: ./.github/workflows/run-infrastructure-tests.yaml

  set-release-version:
    name: Set release version
    if: |
      github.repository == 'OWASP/Nest' &&
      (
        github.event_name == 'schedule' ||
        github.event_name == 'workflow_dispatch' ||
        (github.event_name == 'release' && github.event.action == 'published')
      )
    needs:
      - run-backend-tests
      - run-e2e-tests
      - run-frontend-tests
      - run-infrastructure-tests
      - run-rest-fuzz-tests
    permissions: {}
    uses: ./.github/workflows/set-release-version.yaml

  build-staging-images:
    name: Build Staging Images
    if: |
      github.repository == 'OWASP/Nest' &&
      (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
    needs:
      - set-release-version
    permissions:
      contents: read
    uses: ./.github/workflows/build-images.yaml
    with:
      aws_role_name: nest-staging-terraform
      aws_role_session_name: GitHubActions-BuildStagingImages
      backend_ecr_cache_repo: nest-staging-backend-cache
      backend_ecr_repo: nest-staging-backend
      backend_uid: '1001'
      backend_gid: '1001'
      environment: staging
      frontend_ecr_cache_repo: nest-staging-frontend-cache
      frontend_ecr_repo: nest-staging-frontend
      release_version: ${{ needs.set-release-version.outputs.release_version }}

  scan-staging-images:
    name: Scan Staging Images
    needs:
      - build-staging-images
      - set-release-version
    permissions:
      actions: write
      contents: write
    uses: ./.github/workflows/scan-images.yaml
    with:
      aws_role_name: nest-staging-terraform
      aws_role_session_name: GitHubActions-ScanStagingImages
      backend_ecr_repo: nest-staging-backend
      environment: staging
      frontend_ecr_repo: nest-staging-frontend
      release_version: ${{ needs.set-release-version.outputs.release_version }}

  bootstrap-nest-staging-infrastructure:
    name: Bootstrap Nest Staging Infrastructure
    if: |
      (github.repository == 'OWASP/Nest' &&
      (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'))
    needs:
      - scan-staging-images
    permissions:
      contents: read
    uses: ./.github/workflows/bootstrap-infrastructure.yaml
    with:
      environment: staging

  deploy-staging-nest:
    name: Deploy Nest to Staging
    if: |
      github.repository == 'OWASP/Nest' &&
      (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
    needs:
      - bootstrap-nest-staging-infrastructure
      - set-release-version
    permissions:
      contents: read
    uses: ./.github/workflows/deploy-nest.yaml
    with:
      aws_role_name: nest-staging-terraform
      aws_role_session_name: GitHubActions-StagingDeploy
      backend_use_fargate_spot: true
      django_configuration: Staging
      django_settings_module: settings.staging
      enable_cron_tasks: false
      enable_nat_gateway: false
      enable_rds_proxy: false
      environment: staging
      frontend_use_fargate_spot: true
      index_task_definition: nest-staging-index-data
      migrate_task_definition: nest-staging-migrate
      release_version: ${{ needs.set-release-version.outputs.release_version }}
      tasks_use_fargate_spot: true
      tf_state_key: staging/terraform.tfstate

  run-staging-lighthouse-ci:
    name: Run staging Lighthouse CI
    needs:
      - deploy-staging-nest
    permissions:
      contents: read
    uses: ./.github/workflows/run-lighthouse-ci.yaml
    with:
      base_url: https://nest.owasp.dev

  run-staging-zap-baseline-scan:
    name: Run staging ZAP baseline scan
    needs:
      - deploy-staging-nest
    permissions:
      contents: read
    uses: ./.github/workflows/run-zap-baseline-scan.yaml
    with:
      base_url: https://nest.owasp.dev

  run-production:
    name: Run production jobs
    if: |
      github.repository == 'OWASP/Nest' &&
      github.event_name == 'release' &&
      github.event.action == 'published'
    needs:
      - set-release-version
    permissions:
      actions: write
      contents: write
    uses: ./.github/workflows/run-production.yaml
    with:
      release_version: ${{ needs.set-release-version.outputs.release_version }}
      release_tag: ${{ github.event.release.tag_name }}
