name: Run environment workflow

on:
  workflow_call:
    inputs:
      backend_gid:
        description: Backend GID for Docker build
        required: true
        type: string
      backend_uid:
        description: Backend UID for Docker build
        required: true
        type: string
      backend_use_fargate_spot:
        description: Use Fargate spot for backend
        required: true
        type: boolean
      base_url:
        description: The base URL for Lighthouse and ZAP scans
        required: true
        type: string
      django_configuration:
        description: Django configuration string
        required: true
        type: string
      django_settings_module:
        description: Django settings module
        required: true
        type: string
      enable_additional_parameters:
        description: Enable additional SSM parameters
        required: false
        default: false
        type: boolean
      enable_cron_tasks:
        description: Enable cron tasks
        required: true
        type: boolean
      enable_nat_gateway:
        description: Enable NAT gateway
        required: true
        type: boolean
      enable_rds_proxy:
        description: Enable RDS proxy
        required: true
        type: boolean
      env_display:
        description: The display name of the environment (e.g., Staging, Production)
        required: true
        type: string
      environment:
        description: The environment name (e.g., staging, production)
        required: true
        type: string
      frontend_use_fargate_spot:
        description: Use Fargate spot for frontend
        required: true
        type: boolean
      release_tag:
        description: The release tag for SBOM uploads (production only)
        required: false
        type: string
        default: ''
      release_version:
        description: The release version to set
        required: true
        type: string
      tasks_use_fargate_spot:
        description: Use Fargate spot for tasks
        required: true
        type: boolean

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
  build-images:
    name: Build images
    permissions:
      contents: read
    uses: ./.github/workflows/build-images.yaml
    with:
      aws_role_name: nest-${{ inputs.environment }}-terraform
      aws_role_session_name: GitHubActions-Build${{ inputs.env_display }}Images
      backend_ecr_cache_repo: nest-${{ inputs.environment }}-backend-cache
      backend_ecr_repo: nest-${{ inputs.environment }}-backend
      backend_uid: ${{ inputs.backend_uid }}
      backend_gid: ${{ inputs.backend_gid }}
      environment: ${{ inputs.environment }}
      frontend_ecr_cache_repo: nest-${{ inputs.environment }}-frontend-cache
      frontend_ecr_repo: nest-${{ inputs.environment }}-frontend
      release_version: ${{ inputs.release_version }}

  scan-images:
    name: Scan images
    needs:
      - build-images
    permissions:
      actions: write
      contents: write
    uses: ./.github/workflows/scan-images.yaml
    with:
      aws_role_name: nest-${{ inputs.environment }}-terraform
      aws_role_session_name: GitHubActions-Scan${{ inputs.env_display }}Images
      backend_ecr_repo: nest-${{ inputs.environment }}-backend
      environment: ${{ inputs.environment }}
      frontend_ecr_repo: nest-${{ inputs.environment }}-frontend
      release_tag: ${{ inputs.release_tag }}
      release_version: ${{ inputs.release_version }}

  bootstrap-nest-infrastructure:
    name: Bootstrap Nest infrastructure
    needs:
      - scan-images
    permissions:
      contents: read
    uses: ./.github/workflows/bootstrap-infrastructure.yaml
    with:
      environment: ${{ inputs.environment }}

  deploy-nest:
    name: Deploy Nest
    needs:
      - bootstrap-nest-infrastructure
    permissions:
      contents: read
    uses: ./.github/workflows/deploy-nest.yaml
    with:
      aws_role_name: nest-${{ inputs.environment }}-terraform
      aws_role_session_name: GitHubActions-${{ inputs.env_display }}Deploy
      backend_use_fargate_spot: ${{ inputs.backend_use_fargate_spot }}
      django_configuration: ${{ inputs.django_configuration }}
      django_settings_module: ${{ inputs.django_settings_module }}
      enable_additional_parameters: ${{ inputs.enable_additional_parameters }}
      enable_cron_tasks: ${{ inputs.enable_cron_tasks }}
      enable_nat_gateway: ${{ inputs.enable_nat_gateway }}
      enable_rds_proxy: ${{ inputs.enable_rds_proxy }}
      environment: ${{ inputs.environment }}
      frontend_use_fargate_spot: ${{ inputs.frontend_use_fargate_spot }}
      index_task_definition: nest-${{ inputs.environment }}-index-data
      migrate_task_definition: nest-${{ inputs.environment }}-migrate
      release_version: ${{ inputs.release_version }}
      tasks_use_fargate_spot: ${{ inputs.tasks_use_fargate_spot }}
      tf_state_key: ${{ inputs.environment }}/terraform.tfstate

  run-lighthouse-ci:
    name: Run Lighthouse CI
    needs:
      - deploy-nest
    permissions:
      contents: read
    uses: ./.github/workflows/run-lighthouse-ci.yaml
    with:
      base_url: ${{ inputs.base_url }}

  run-zap-baseline-scan:
    name: Run ZAP baseline scan
    needs:
      - deploy-nest
    permissions:
      contents: read
    uses: ./.github/workflows/run-zap-baseline-scan.yaml
    with:
      base_url: ${{ inputs.base_url }}
