name: Run frontend tests

on:
  workflow_call:

env:
  FORCE_COLOR: 1

permissions: {}

jobs:
  run-unit-tests:
    name: Run unit tests
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup frontend environment
        uses: ./.github/actions/setup-frontend-environment

      - name: Run unit tests
        run: pnpm run test:unit
        working-directory: frontend

      - name: Upload coverage artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
        with:
          if-no-files-found: error
          name: coverage-lcov
          path: frontend/coverage/lcov.info
    timeout-minutes: 10

  upload-coverage-to-codecov:
    name: Upload coverage to Codecov
    needs: run-unit-tests
    permissions:
      actions: read
      contents: read
      id-token: write
    uses: ./.github/workflows/upload-coverage-to-codecov.yaml
    with:
      artifact_name: coverage-lcov
      artifact_path: frontend/coverage/lcov.info
      coverage_flags: frontend
      coverage_path: frontend/coverage/lcov.info

  run-a11y-tests:
    name: Run accessibility tests
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Setup frontend environment
        uses: ./.github/actions/setup-frontend-environment

      - name: Run frontend a11y tests
        run: pnpm run test:a11y
        working-directory: frontend
    timeout-minutes: 5
