name: Resolve release version

on:
  workflow_call:
    outputs:
      release_version:
        description: The resolved release version
        value: ${{ jobs.run-release-version-resolution.outputs.release_version }}

env:
  FORCE_COLOR: 1

permissions: {}

jobs:
  run-release-version-resolution:
    name: Resolve release version
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.release-version-resolution.outputs.release_version }}
    steps:
      - name: Resolve release version
        id: release-version-resolution
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          if [ -n "$RELEASE_TAG" ]; then
            echo "release_version=$RELEASE_TAG" >> "$GITHUB_OUTPUT"
          else
            echo "release_version=$(date '+%y.%-m.%-d')-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          fi
    timeout-minutes: 5
