name: Sync Nest data

on:
  schedule:
    - cron: '17 5 * * *'
  workflow_dispatch:

env:
  FORCE_COLOR: 1

jobs:
  update-data:
    name: Run data sync
    if: github.repository == 'OWASP/Nest'
    env:
      ANSIBLE_HOST_KEY_CHECKING: False
      NEST_HOST_IP_ADDRESS: '${{ secrets.NEST_HOST_IP_ADDRESS }}'
      NEST_SSH_PRIVATE_KEY_PATH: '${{ vars.NEST_SSH_PRIVATE_KEY_PATH }}'
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Prepare SSH key
        run: |
          mkdir -m 700 ~/.ssh
          echo "${{ secrets.NEST_SSH_PRIVATE_KEY }}" > ${{ env.NEST_SSH_PRIVATE_KEY_PATH }}
          chmod 400 ${{ env.NEST_SSH_PRIVATE_KEY_PATH }}

      - name: Run make sync-data
        working-directory: .github/ansible
        run: ansible-playbook -i inventory.yaml staging/sync-data.yaml
